// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_resource_ap_fixed_32_16_4_0_0_ap_fixed_32_16_5_3_0_config8_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        layer8_out_0,
        layer8_out_0_ap_vld,
        layer8_out_1,
        layer8_out_1_ap_vld,
        layer8_out_2,
        layer8_out_2_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [30:0] p_read;
input  [30:0] p_read1;
input  [30:0] p_read2;
input  [30:0] p_read3;
input  [30:0] p_read4;
input  [30:0] p_read5;
input  [30:0] p_read6;
input  [30:0] p_read7;
input  [30:0] p_read8;
input  [30:0] p_read9;
input  [30:0] p_read10;
input  [30:0] p_read11;
input  [30:0] p_read12;
input  [30:0] p_read13;
input  [30:0] p_read14;
input  [30:0] p_read15;
output  [31:0] layer8_out_0;
output   layer8_out_0_ap_vld;
output  [31:0] layer8_out_1;
output   layer8_out_1_ap_vld;
output  [31:0] layer8_out_2;
output   layer8_out_2_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] layer8_out_0;
reg layer8_out_0_ap_vld;
reg[31:0] layer8_out_1;
reg layer8_out_1_ap_vld;
reg[31:0] layer8_out_2;
reg layer8_out_2_ap_vld;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1;
wire   [31:0] add_ln53_1838_fu_1543_p2;
reg   [31:0] layer8_out_0_preg;
wire   [31:0] add_ln53_1854_fu_1664_p2;
reg   [31:0] layer8_out_1_preg;
wire   [31:0] add_ln53_1870_fu_1789_p2;
reg   [31:0] layer8_out_2_preg;
wire   [30:0] mul_i_i_7_i_fu_297_p0;
wire   [11:0] mul_i_i_7_i_fu_297_p1;
wire   [30:0] mul_i_i_14_i_fu_302_p0;
wire   [11:0] mul_i_i_14_i_fu_302_p1;
wire   [30:0] mul_i_i_2_i_fu_307_p0;
wire   [12:0] mul_i_i_2_i_fu_307_p1;
wire   [30:0] mul_i_i_47_i_fu_312_p0;
wire   [12:0] mul_i_i_47_i_fu_312_p1;
wire   [30:0] mul_i_i_6_i_fu_317_p0;
wire   [13:0] mul_i_i_6_i_fu_317_p1;
wire   [30:0] mul_i_i_8_i_fu_322_p0;
wire   [13:0] mul_i_i_8_i_fu_322_p1;
wire   [30:0] mul_i_i_10_i_fu_327_p0;
wire   [43:0] conv_i_i_10_i_cast_fu_828_p1;
wire   [13:0] mul_i_i_10_i_fu_327_p1;
wire   [30:0] mul_i_i_13_i_fu_332_p0;
wire   [13:0] mul_i_i_13_i_fu_332_p1;
wire   [30:0] mul_i_i_27_i_fu_337_p0;
wire   [13:0] mul_i_i_27_i_fu_337_p1;
wire   [30:0] mul_i_i_31_i_fu_342_p0;
wire   [13:0] mul_i_i_31_i_fu_342_p1;
wire   [30:0] mul_i_i_15_i_fu_347_p0;
wire   [14:0] mul_i_i_15_i_fu_347_p1;
wire   [30:0] mul_i_i_17_i_fu_352_p0;
wire   [14:0] mul_i_i_17_i_fu_352_p1;
wire   [30:0] mul_i_i_45_i_fu_357_p0;
wire   [14:0] mul_i_i_45_i_fu_357_p1;
wire   [30:0] mul_i_i_46_i_fu_362_p0;
wire   [14:0] mul_i_i_46_i_fu_362_p1;
wire   [30:0] mul_i_i_4_i_fu_367_p0;
wire   [15:0] mul_i_i_4_i_fu_367_p1;
wire   [30:0] mul_i_i_11_i_fu_372_p0;
wire   [45:0] conv_i_i_11_i_cast_fu_853_p1;
wire   [15:0] mul_i_i_11_i_fu_372_p1;
wire   [30:0] mul_i_i_18_i_fu_377_p0;
wire   [15:0] mul_i_i_18_i_fu_377_p1;
wire   [30:0] mul_i_i_19_i_fu_382_p0;
wire   [45:0] conv_i_i_3_i_cast5_fu_615_p1;
wire   [15:0] mul_i_i_19_i_fu_382_p1;
wire   [30:0] mul_i_i_25_i_fu_387_p0;
wire   [15:0] mul_i_i_25_i_fu_387_p1;
wire   [30:0] mul_i_i_29_i_fu_392_p0;
wire   [15:0] mul_i_i_29_i_fu_392_p1;
wire   [30:0] mul_i_i_35_i_fu_397_p0;
wire   [15:0] mul_i_i_35_i_fu_397_p1;
wire   [30:0] mul_i_i_39_i_fu_402_p0;
wire   [15:0] mul_i_i_39_i_fu_402_p1;
wire   [30:0] mul_i_i_42_i_fu_407_p0;
wire   [15:0] mul_i_i_42_i_fu_407_p1;
wire   [30:0] mul_i_i_43_i_fu_412_p0;
wire   [15:0] mul_i_i_43_i_fu_412_p1;
wire   [30:0] mul_i_i_1_i_fu_417_p0;
wire  signed [11:0] mul_i_i_1_i_fu_417_p1;
wire   [30:0] mul_i_i_21_i_fu_422_p0;
wire   [42:0] conv_i_i_5_i_cast7_fu_665_p1;
wire  signed [11:0] mul_i_i_21_i_fu_422_p1;
wire   [30:0] mul_i_i_37_i_fu_427_p0;
wire  signed [11:0] mul_i_i_37_i_fu_427_p1;
wire   [30:0] mul_i_i_44_i_fu_432_p0;
wire  signed [11:0] mul_i_i_44_i_fu_432_p1;
wire   [30:0] mul_i_i_26_i_fu_437_p0;
wire  signed [12:0] mul_i_i_26_i_fu_437_p1;
wire   [30:0] mul_i_i_34_i_fu_442_p0;
wire  signed [12:0] mul_i_i_34_i_fu_442_p1;
wire   [30:0] mul_i_i_22_i_fu_447_p0;
wire  signed [13:0] mul_i_i_22_i_fu_447_p1;
wire   [30:0] mul_i_i_i_fu_452_p0;
wire   [45:0] conv_i_i_i_cast_fu_537_p1;
wire  signed [14:0] mul_i_i_i_fu_452_p1;
wire   [30:0] mul_i_i_12_i_fu_457_p0;
wire   [45:0] conv_i_i_12_i_cast_fu_874_p1;
wire  signed [14:0] mul_i_i_12_i_fu_457_p1;
wire   [30:0] mul_i_i_24_i_fu_462_p0;
wire   [45:0] conv_i_i_8_i_cast10_fu_744_p1;
wire  signed [14:0] mul_i_i_24_i_fu_462_p1;
wire   [30:0] mul_i_i_28_i_fu_467_p0;
wire  signed [14:0] mul_i_i_28_i_fu_467_p1;
wire   [30:0] mul_i_i_32_i_fu_472_p0;
wire  signed [14:0] mul_i_i_32_i_fu_472_p1;
wire   [30:0] mul_i_i_38_i_fu_477_p0;
wire  signed [14:0] mul_i_i_38_i_fu_477_p1;
wire   [30:0] mul_i_i_40_i_fu_482_p0;
wire  signed [14:0] mul_i_i_40_i_fu_482_p1;
wire   [30:0] mul_i_i_3_i_fu_487_p0;
wire  signed [15:0] mul_i_i_3_i_fu_487_p1;
wire   [30:0] mul_i_i_5_i_fu_492_p0;
wire  signed [15:0] mul_i_i_5_i_fu_492_p1;
wire   [30:0] mul_i_i_16_i_fu_497_p0;
wire  signed [15:0] mul_i_i_16_i_fu_497_p1;
wire   [30:0] mul_i_i_23_i_fu_502_p0;
wire  signed [15:0] mul_i_i_23_i_fu_502_p1;
wire   [30:0] mul_i_i_30_i_fu_507_p0;
wire  signed [15:0] mul_i_i_30_i_fu_507_p1;
wire   [30:0] mul_i_i_33_i_fu_512_p0;
wire  signed [15:0] mul_i_i_33_i_fu_512_p1;
wire   [30:0] mul_i_i_36_i_fu_517_p0;
wire  signed [15:0] mul_i_i_36_i_fu_517_p1;
wire   [30:0] mul_i_i_41_i_fu_522_p0;
wire  signed [15:0] mul_i_i_41_i_fu_522_p1;
wire   [30:0] mul_i_i_20_i_fu_527_p0;
wire  signed [16:0] mul_i_i_20_i_fu_527_p1;
wire   [45:0] mul_i_i_i_fu_452_p2;
wire   [29:0] p_cast_fu_543_p4;
wire   [42:0] mul_i_i_1_i_fu_417_p2;
wire   [26:0] p_cast1_fu_572_p4;
wire   [42:0] mul_i_i_2_i_fu_307_p2;
wire   [26:0] tmp_fu_601_p4;
wire   [46:0] mul_i_i_3_i_fu_487_p2;
wire   [30:0] p_cast2_fu_626_p4;
wire   [45:0] mul_i_i_4_i_fu_367_p2;
wire   [46:0] mul_i_i_5_i_fu_492_p2;
wire   [30:0] p_cast3_fu_676_p4;
wire   [43:0] mul_i_i_6_i_fu_317_p2;
wire   [41:0] mul_i_i_7_i_fu_297_p2;
wire   [25:0] tmp_s_fu_730_p4;
wire   [43:0] mul_i_i_8_i_fu_322_p2;
wire   [27:0] tmp_19_fu_755_p4;
wire   [41:0] p_shl_fu_779_p3;
wire   [33:0] p_shl1_fu_791_p3;
wire   [42:0] p_shl1_cast_fu_799_p1;
wire   [42:0] p_shl_cast_fu_787_p1;
wire   [42:0] mul_i_i_9_i_fu_803_p2;
wire   [26:0] p_cast4_fu_809_p4;
wire   [43:0] mul_i_i_10_i_fu_327_p2;
wire   [27:0] tmp_20_fu_834_p4;
wire   [45:0] mul_i_i_11_i_fu_372_p2;
wire   [45:0] mul_i_i_12_i_fu_457_p2;
wire   [29:0] p_cast5_fu_880_p4;
wire   [43:0] mul_i_i_13_i_fu_332_p2;
wire   [27:0] tmp_21_fu_909_p4;
wire   [41:0] mul_i_i_14_i_fu_302_p2;
wire   [25:0] tmp_22_fu_938_p4;
wire   [44:0] mul_i_i_15_i_fu_347_p2;
wire   [46:0] mul_i_i_16_i_fu_497_p2;
wire   [30:0] p_cast6_fu_977_p4;
wire   [44:0] mul_i_i_17_i_fu_352_p2;
wire   [28:0] tmp_23_fu_991_p4;
wire   [45:0] mul_i_i_18_i_fu_377_p2;
wire   [45:0] mul_i_i_19_i_fu_382_p2;
wire   [29:0] tmp_24_fu_1015_p4;
wire   [47:0] mul_i_i_20_i_fu_527_p2;
wire   [42:0] mul_i_i_21_i_fu_422_p2;
wire   [26:0] p_cast7_fu_1039_p4;
wire   [44:0] mul_i_i_22_i_fu_447_p2;
wire   [28:0] p_cast8_fu_1053_p4;
wire   [46:0] mul_i_i_23_i_fu_502_p2;
wire   [30:0] p_cast9_fu_1067_p4;
wire   [45:0] mul_i_i_24_i_fu_462_p2;
wire   [29:0] p_cast10_fu_1081_p4;
wire   [45:0] mul_i_i_25_i_fu_387_p2;
wire   [29:0] tmp_25_fu_1095_p4;
wire   [43:0] mul_i_i_26_i_fu_437_p2;
wire   [27:0] p_cast11_fu_1109_p4;
wire   [43:0] mul_i_i_27_i_fu_337_p2;
wire   [27:0] tmp_26_fu_1123_p4;
wire   [45:0] mul_i_i_28_i_fu_467_p2;
wire   [29:0] p_cast12_fu_1137_p4;
wire   [45:0] mul_i_i_29_i_fu_392_p2;
wire   [29:0] tmp_27_fu_1151_p4;
wire   [46:0] mul_i_i_30_i_fu_507_p2;
wire   [30:0] p_cast13_fu_1165_p4;
wire   [43:0] mul_i_i_31_i_fu_342_p2;
wire   [27:0] tmp_28_fu_1179_p4;
wire   [45:0] mul_i_i_32_i_fu_472_p2;
wire   [29:0] p_cast14_fu_1193_p4;
wire   [46:0] mul_i_i_33_i_fu_512_p2;
wire   [30:0] p_cast15_fu_1207_p4;
wire   [43:0] mul_i_i_34_i_fu_442_p2;
wire   [27:0] p_cast16_fu_1221_p4;
wire   [45:0] mul_i_i_35_i_fu_397_p2;
wire   [29:0] tmp_29_fu_1235_p4;
wire   [46:0] mul_i_i_36_i_fu_517_p2;
wire   [30:0] p_cast17_fu_1249_p4;
wire   [42:0] mul_i_i_37_i_fu_427_p2;
wire   [26:0] p_cast18_fu_1263_p4;
wire   [45:0] mul_i_i_38_i_fu_477_p2;
wire   [29:0] p_cast19_fu_1277_p4;
wire   [45:0] mul_i_i_39_i_fu_402_p2;
wire   [29:0] tmp_30_fu_1291_p4;
wire   [45:0] mul_i_i_40_i_fu_482_p2;
wire   [29:0] p_cast20_fu_1305_p4;
wire   [46:0] mul_i_i_41_i_fu_522_p2;
wire   [30:0] p_cast21_fu_1319_p4;
wire   [45:0] mul_i_i_42_i_fu_407_p2;
wire   [29:0] tmp_31_fu_1333_p4;
wire   [45:0] mul_i_i_43_i_fu_412_p2;
wire   [29:0] tmp_32_fu_1347_p4;
wire   [42:0] mul_i_i_44_i_fu_432_p2;
wire   [26:0] p_cast22_fu_1361_p4;
wire   [44:0] mul_i_i_45_i_fu_357_p2;
wire   [28:0] tmp_33_fu_1375_p4;
wire   [44:0] mul_i_i_46_i_fu_362_p2;
wire   [28:0] tmp_34_fu_1389_p4;
wire   [42:0] mul_i_i_47_i_fu_312_p2;
wire   [26:0] tmp_35_fu_1403_p4;
wire   [29:0] conv_i_i_i_2_i_cast_cast_fu_611_p1;
wire   [29:0] conv_i_i_i_4_i_cast_fu_655_p4;
wire   [27:0] conv_i_i_i_6_i_cast_fu_705_p4;
wire   [27:0] conv_i_i_i_7_i_cast_cast_fu_740_p1;
wire   [27:0] add_ln53_1824_fu_1423_p2;
wire   [29:0] zext_ln53_fu_1429_p1;
wire   [29:0] add_ln53_fu_1417_p2;
wire   [29:0] add_ln53_1825_fu_1433_p2;
wire   [28:0] conv_i_i_i_8_i_cast_cast_fu_765_p1;
wire   [28:0] conv_i_i_i_10_i_cast_cast_fu_844_p1;
wire   [28:0] add_ln53_1826_fu_1443_p2;
wire   [29:0] conv_i_i_i_11_i_cast_fu_859_p4;
wire   [29:0] conv_i_i_i_13_i_cast_cast_fu_919_p1;
wire   [29:0] add_ln53_1827_fu_1453_p2;
wire   [30:0] zext_ln53_3_fu_1459_p1;
wire   [30:0] zext_ln53_2_fu_1449_p1;
wire   [30:0] add_ln53_1828_fu_1463_p2;
wire   [30:0] zext_ln53_1_fu_1439_p1;
wire   [30:0] add_ln53_1829_fu_1469_p2;
wire   [28:0] conv_i_i_i_14_i_cast_cast_fu_948_p1;
wire   [28:0] conv_i_i_i_15_i_cast_fu_967_p4;
wire   [28:0] add_ln53_1830_fu_1479_p2;
wire  signed [31:0] p_cast61_cast_fu_636_p1;
wire  signed [31:0] p_cast62_cast_fu_686_p1;
wire   [31:0] add_ln53_1831_fu_1489_p2;
wire   [31:0] zext_ln53_5_fu_1485_p1;
wire  signed [30:0] p_cast_cast_fu_553_p1;
wire  signed [30:0] p_cast64_cast_fu_890_p1;
wire   [30:0] add_ln53_1833_fu_1501_p2;
wire  signed [27:0] p_cast63_cast_fu_819_p1;
wire   [27:0] add_ln53_1834_fu_1511_p2;
wire  signed [28:0] sext_ln53_1274_fu_1517_p1;
wire  signed [28:0] p_cast60_cast_fu_582_p1;
wire   [28:0] add_ln53_1835_fu_1521_p2;
wire  signed [31:0] sext_ln53_1275_fu_1527_p1;
wire  signed [31:0] sext_ln53_fu_1507_p1;
wire   [31:0] add_ln53_1836_fu_1531_p2;
wire   [31:0] add_ln53_1832_fu_1495_p2;
wire   [31:0] add_ln53_1837_fu_1537_p2;
wire   [31:0] zext_ln53_4_fu_1475_p1;
wire   [29:0] conv_i_i_i_17_i_cast_cast_fu_1001_p1;
wire   [29:0] conv_i_i_i_18_i_cast_fu_1005_p4;
wire   [29:0] add_ln53_1839_fu_1550_p2;
wire   [31:0] conv_i_i_i_19_i_cast_cast_fu_1025_p1;
wire   [31:0] conv_i_i_i_20_i_fu_1029_p4;
wire   [31:0] add_ln53_1840_fu_1560_p2;
wire   [31:0] zext_ln53_6_fu_1556_p1;
wire   [30:0] conv_i_i_i_25_i_cast_cast_fu_1105_p1;
wire   [30:0] conv_i_i_i_27_i_cast_cast_fu_1133_p1;
wire   [30:0] add_ln53_1842_fu_1572_p2;
wire   [30:0] conv_i_i_i_29_i_cast_cast_fu_1161_p1;
wire   [30:0] conv_i_i_i_31_i_cast_cast_fu_1189_p1;
wire   [30:0] add_ln53_1843_fu_1582_p2;
wire   [31:0] zext_ln53_8_fu_1588_p1;
wire   [31:0] zext_ln53_7_fu_1578_p1;
wire   [31:0] add_ln53_1844_fu_1592_p2;
wire   [31:0] add_ln53_1841_fu_1566_p2;
wire  signed [31:0] p_cast65_cast_fu_987_p1;
wire  signed [31:0] p_cast68_cast_fu_1077_p1;
wire  signed [31:0] p_cast72_cast_fu_1175_p1;
wire  signed [31:0] p_cast69_cast_fu_1091_p1;
wire   [31:0] add_ln53_1847_fu_1610_p2;
wire   [31:0] add_ln53_1846_fu_1604_p2;
wire  signed [30:0] p_cast71_cast_fu_1147_p1;
wire  signed [30:0] p_cast67_cast_fu_1063_p1;
wire  signed [27:0] p_cast66_cast_fu_1049_p1;
wire   [27:0] add_ln53_1850_fu_1628_p2;
wire  signed [28:0] sext_ln53_1276_fu_1634_p1;
wire  signed [28:0] p_cast70_cast_fu_1119_p1;
wire   [28:0] add_ln53_1851_fu_1638_p2;
wire  signed [30:0] sext_ln53_1277_fu_1644_p1;
wire   [30:0] add_ln53_1849_fu_1622_p2;
wire   [30:0] add_ln53_1852_fu_1648_p2;
wire  signed [31:0] sext_ln53_1278_fu_1654_p1;
wire   [31:0] add_ln53_1848_fu_1616_p2;
wire   [31:0] add_ln53_1853_fu_1658_p2;
wire   [31:0] add_ln53_1845_fu_1598_p2;
wire   [30:0] conv_i_i_i_35_i_cast_cast_fu_1245_p1;
wire   [30:0] conv_i_i_i_39_i_cast_cast_fu_1301_p1;
wire   [30:0] add_ln53_1855_fu_1671_p2;
wire   [30:0] conv_i_i_i_42_i_cast_cast_fu_1343_p1;
wire   [30:0] conv_i_i_i_43_i_cast_cast_fu_1357_p1;
wire   [30:0] add_ln53_1856_fu_1681_p2;
wire   [31:0] zext_ln53_10_fu_1687_p1;
wire   [31:0] zext_ln53_9_fu_1677_p1;
wire   [29:0] conv_i_i_i_45_i_cast_cast_fu_1385_p1;
wire   [29:0] conv_i_i_i_46_i_cast_cast_fu_1399_p1;
wire   [29:0] add_ln53_1858_fu_1697_p2;
wire   [31:0] conv_i_i_i_47_i_cast_cast_fu_1413_p1;
wire  signed [31:0] p_cast74_cast_fu_1217_p1;
wire   [31:0] add_ln53_1859_fu_1707_p2;
wire   [31:0] zext_ln53_11_fu_1703_p1;
wire   [31:0] add_ln53_1860_fu_1713_p2;
wire   [31:0] add_ln53_1857_fu_1691_p2;
wire  signed [31:0] p_cast76_cast_fu_1259_p1;
wire  signed [31:0] p_cast80_cast_fu_1329_p1;
wire  signed [30:0] p_cast73_cast_fu_1203_p1;
wire  signed [30:0] p_cast78_cast_fu_1287_p1;
wire   [30:0] add_ln53_1863_fu_1731_p2;
wire  signed [31:0] sext_ln53_1279_fu_1737_p1;
wire   [31:0] add_ln53_1862_fu_1725_p2;
wire  signed [30:0] p_cast79_cast_fu_1315_p1;
wire  signed [30:0] p_cast75_cast_fu_1231_p1;
wire  signed [27:0] p_cast81_cast_fu_1371_p1;
wire   [27:0] add_ln53_1866_fu_1753_p2;
wire  signed [28:0] sext_ln53_1280_fu_1759_p1;
wire  signed [28:0] p_cast77_cast_fu_1273_p1;
wire   [28:0] add_ln53_1867_fu_1763_p2;
wire  signed [30:0] sext_ln53_1281_fu_1769_p1;
wire   [30:0] add_ln53_1865_fu_1747_p2;
wire   [30:0] add_ln53_1868_fu_1773_p2;
wire  signed [31:0] sext_ln53_1282_fu_1779_p1;
wire   [31:0] add_ln53_1864_fu_1741_p2;
wire   [31:0] add_ln53_1869_fu_1783_p2;
wire   [31:0] add_ln53_1861_fu_1719_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire   [43:0] mul_i_i_13_i_fu_332_p00;
wire   [41:0] mul_i_i_14_i_fu_302_p00;
wire   [44:0] mul_i_i_15_i_fu_347_p00;
wire   [46:0] mul_i_i_16_i_fu_497_p00;
wire   [44:0] mul_i_i_17_i_fu_352_p00;
wire   [45:0] mul_i_i_18_i_fu_377_p00;
wire   [42:0] mul_i_i_1_i_fu_417_p00;
wire   [47:0] mul_i_i_20_i_fu_527_p00;
wire   [44:0] mul_i_i_22_i_fu_447_p00;
wire   [46:0] mul_i_i_23_i_fu_502_p00;
wire   [45:0] mul_i_i_25_i_fu_387_p00;
wire   [43:0] mul_i_i_27_i_fu_337_p00;
wire   [45:0] mul_i_i_29_i_fu_392_p00;
wire   [42:0] mul_i_i_2_i_fu_307_p00;
wire   [46:0] mul_i_i_30_i_fu_507_p00;
wire   [43:0] mul_i_i_31_i_fu_342_p00;
wire   [46:0] mul_i_i_33_i_fu_512_p00;
wire   [43:0] mul_i_i_34_i_fu_442_p00;
wire   [46:0] mul_i_i_36_i_fu_517_p00;
wire   [45:0] mul_i_i_38_i_fu_477_p00;
wire   [45:0] mul_i_i_39_i_fu_402_p00;
wire   [46:0] mul_i_i_3_i_fu_487_p00;
wire   [46:0] mul_i_i_41_i_fu_522_p00;
wire   [45:0] mul_i_i_42_i_fu_407_p00;
wire   [42:0] mul_i_i_44_i_fu_432_p00;
wire   [44:0] mul_i_i_45_i_fu_357_p00;
wire   [44:0] mul_i_i_46_i_fu_362_p00;
wire   [42:0] mul_i_i_47_i_fu_312_p00;
wire   [45:0] mul_i_i_4_i_fu_367_p00;
wire   [46:0] mul_i_i_5_i_fu_492_p00;
wire   [43:0] mul_i_i_6_i_fu_317_p00;
wire   [41:0] mul_i_i_7_i_fu_297_p00;
wire   [43:0] mul_i_i_8_i_fu_322_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 layer8_out_0_preg = 32'd0;
#0 layer8_out_1_preg = 32'd0;
#0 layer8_out_2_preg = 32'd0;
end

myproject_mul_31ns_12ns_42_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 42 ))
mul_31ns_12ns_42_1_1_U2431(
    .din0(mul_i_i_7_i_fu_297_p0),
    .din1(mul_i_i_7_i_fu_297_p1),
    .dout(mul_i_i_7_i_fu_297_p2)
);

myproject_mul_31ns_12ns_42_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 42 ))
mul_31ns_12ns_42_1_1_U2432(
    .din0(mul_i_i_14_i_fu_302_p0),
    .din1(mul_i_i_14_i_fu_302_p1),
    .dout(mul_i_i_14_i_fu_302_p2)
);

myproject_mul_31ns_13ns_43_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 43 ))
mul_31ns_13ns_43_1_1_U2433(
    .din0(mul_i_i_2_i_fu_307_p0),
    .din1(mul_i_i_2_i_fu_307_p1),
    .dout(mul_i_i_2_i_fu_307_p2)
);

myproject_mul_31ns_13ns_43_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 43 ))
mul_31ns_13ns_43_1_1_U2434(
    .din0(mul_i_i_47_i_fu_312_p0),
    .din1(mul_i_i_47_i_fu_312_p1),
    .dout(mul_i_i_47_i_fu_312_p2)
);

myproject_mul_31ns_14ns_44_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 44 ))
mul_31ns_14ns_44_1_1_U2435(
    .din0(mul_i_i_6_i_fu_317_p0),
    .din1(mul_i_i_6_i_fu_317_p1),
    .dout(mul_i_i_6_i_fu_317_p2)
);

myproject_mul_31ns_14ns_44_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 44 ))
mul_31ns_14ns_44_1_1_U2436(
    .din0(mul_i_i_8_i_fu_322_p0),
    .din1(mul_i_i_8_i_fu_322_p1),
    .dout(mul_i_i_8_i_fu_322_p2)
);

myproject_mul_31ns_14ns_44_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 44 ))
mul_31ns_14ns_44_1_1_U2437(
    .din0(mul_i_i_10_i_fu_327_p0),
    .din1(mul_i_i_10_i_fu_327_p1),
    .dout(mul_i_i_10_i_fu_327_p2)
);

myproject_mul_31ns_14ns_44_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 44 ))
mul_31ns_14ns_44_1_1_U2438(
    .din0(mul_i_i_13_i_fu_332_p0),
    .din1(mul_i_i_13_i_fu_332_p1),
    .dout(mul_i_i_13_i_fu_332_p2)
);

myproject_mul_31ns_14ns_44_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 44 ))
mul_31ns_14ns_44_1_1_U2439(
    .din0(mul_i_i_27_i_fu_337_p0),
    .din1(mul_i_i_27_i_fu_337_p1),
    .dout(mul_i_i_27_i_fu_337_p2)
);

myproject_mul_31ns_14ns_44_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 44 ))
mul_31ns_14ns_44_1_1_U2440(
    .din0(mul_i_i_31_i_fu_342_p0),
    .din1(mul_i_i_31_i_fu_342_p1),
    .dout(mul_i_i_31_i_fu_342_p2)
);

myproject_mul_31ns_15ns_45_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 45 ))
mul_31ns_15ns_45_1_1_U2441(
    .din0(mul_i_i_15_i_fu_347_p0),
    .din1(mul_i_i_15_i_fu_347_p1),
    .dout(mul_i_i_15_i_fu_347_p2)
);

myproject_mul_31ns_15ns_45_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 45 ))
mul_31ns_15ns_45_1_1_U2442(
    .din0(mul_i_i_17_i_fu_352_p0),
    .din1(mul_i_i_17_i_fu_352_p1),
    .dout(mul_i_i_17_i_fu_352_p2)
);

myproject_mul_31ns_15ns_45_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 45 ))
mul_31ns_15ns_45_1_1_U2443(
    .din0(mul_i_i_45_i_fu_357_p0),
    .din1(mul_i_i_45_i_fu_357_p1),
    .dout(mul_i_i_45_i_fu_357_p2)
);

myproject_mul_31ns_15ns_45_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 45 ))
mul_31ns_15ns_45_1_1_U2444(
    .din0(mul_i_i_46_i_fu_362_p0),
    .din1(mul_i_i_46_i_fu_362_p1),
    .dout(mul_i_i_46_i_fu_362_p2)
);

myproject_mul_31ns_16ns_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 46 ))
mul_31ns_16ns_46_1_1_U2445(
    .din0(mul_i_i_4_i_fu_367_p0),
    .din1(mul_i_i_4_i_fu_367_p1),
    .dout(mul_i_i_4_i_fu_367_p2)
);

myproject_mul_31ns_16ns_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 46 ))
mul_31ns_16ns_46_1_1_U2446(
    .din0(mul_i_i_11_i_fu_372_p0),
    .din1(mul_i_i_11_i_fu_372_p1),
    .dout(mul_i_i_11_i_fu_372_p2)
);

myproject_mul_31ns_16ns_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 46 ))
mul_31ns_16ns_46_1_1_U2447(
    .din0(mul_i_i_18_i_fu_377_p0),
    .din1(mul_i_i_18_i_fu_377_p1),
    .dout(mul_i_i_18_i_fu_377_p2)
);

myproject_mul_31ns_16ns_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 46 ))
mul_31ns_16ns_46_1_1_U2448(
    .din0(mul_i_i_19_i_fu_382_p0),
    .din1(mul_i_i_19_i_fu_382_p1),
    .dout(mul_i_i_19_i_fu_382_p2)
);

myproject_mul_31ns_16ns_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 46 ))
mul_31ns_16ns_46_1_1_U2449(
    .din0(mul_i_i_25_i_fu_387_p0),
    .din1(mul_i_i_25_i_fu_387_p1),
    .dout(mul_i_i_25_i_fu_387_p2)
);

myproject_mul_31ns_16ns_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 46 ))
mul_31ns_16ns_46_1_1_U2450(
    .din0(mul_i_i_29_i_fu_392_p0),
    .din1(mul_i_i_29_i_fu_392_p1),
    .dout(mul_i_i_29_i_fu_392_p2)
);

myproject_mul_31ns_16ns_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 46 ))
mul_31ns_16ns_46_1_1_U2451(
    .din0(mul_i_i_35_i_fu_397_p0),
    .din1(mul_i_i_35_i_fu_397_p1),
    .dout(mul_i_i_35_i_fu_397_p2)
);

myproject_mul_31ns_16ns_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 46 ))
mul_31ns_16ns_46_1_1_U2452(
    .din0(mul_i_i_39_i_fu_402_p0),
    .din1(mul_i_i_39_i_fu_402_p1),
    .dout(mul_i_i_39_i_fu_402_p2)
);

myproject_mul_31ns_16ns_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 46 ))
mul_31ns_16ns_46_1_1_U2453(
    .din0(mul_i_i_42_i_fu_407_p0),
    .din1(mul_i_i_42_i_fu_407_p1),
    .dout(mul_i_i_42_i_fu_407_p2)
);

myproject_mul_31ns_16ns_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 46 ))
mul_31ns_16ns_46_1_1_U2454(
    .din0(mul_i_i_43_i_fu_412_p0),
    .din1(mul_i_i_43_i_fu_412_p1),
    .dout(mul_i_i_43_i_fu_412_p2)
);

myproject_mul_31ns_12s_43_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 43 ))
mul_31ns_12s_43_1_1_U2455(
    .din0(mul_i_i_1_i_fu_417_p0),
    .din1(mul_i_i_1_i_fu_417_p1),
    .dout(mul_i_i_1_i_fu_417_p2)
);

myproject_mul_31ns_12s_43_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 43 ))
mul_31ns_12s_43_1_1_U2456(
    .din0(mul_i_i_21_i_fu_422_p0),
    .din1(mul_i_i_21_i_fu_422_p1),
    .dout(mul_i_i_21_i_fu_422_p2)
);

myproject_mul_31ns_12s_43_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 43 ))
mul_31ns_12s_43_1_1_U2457(
    .din0(mul_i_i_37_i_fu_427_p0),
    .din1(mul_i_i_37_i_fu_427_p1),
    .dout(mul_i_i_37_i_fu_427_p2)
);

myproject_mul_31ns_12s_43_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 43 ))
mul_31ns_12s_43_1_1_U2458(
    .din0(mul_i_i_44_i_fu_432_p0),
    .din1(mul_i_i_44_i_fu_432_p1),
    .dout(mul_i_i_44_i_fu_432_p2)
);

myproject_mul_31ns_13s_44_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 44 ))
mul_31ns_13s_44_1_1_U2459(
    .din0(mul_i_i_26_i_fu_437_p0),
    .din1(mul_i_i_26_i_fu_437_p1),
    .dout(mul_i_i_26_i_fu_437_p2)
);

myproject_mul_31ns_13s_44_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 44 ))
mul_31ns_13s_44_1_1_U2460(
    .din0(mul_i_i_34_i_fu_442_p0),
    .din1(mul_i_i_34_i_fu_442_p1),
    .dout(mul_i_i_34_i_fu_442_p2)
);

myproject_mul_31ns_14s_45_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 45 ))
mul_31ns_14s_45_1_1_U2461(
    .din0(mul_i_i_22_i_fu_447_p0),
    .din1(mul_i_i_22_i_fu_447_p1),
    .dout(mul_i_i_22_i_fu_447_p2)
);

myproject_mul_31ns_15s_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 46 ))
mul_31ns_15s_46_1_1_U2462(
    .din0(mul_i_i_i_fu_452_p0),
    .din1(mul_i_i_i_fu_452_p1),
    .dout(mul_i_i_i_fu_452_p2)
);

myproject_mul_31ns_15s_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 46 ))
mul_31ns_15s_46_1_1_U2463(
    .din0(mul_i_i_12_i_fu_457_p0),
    .din1(mul_i_i_12_i_fu_457_p1),
    .dout(mul_i_i_12_i_fu_457_p2)
);

myproject_mul_31ns_15s_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 46 ))
mul_31ns_15s_46_1_1_U2464(
    .din0(mul_i_i_24_i_fu_462_p0),
    .din1(mul_i_i_24_i_fu_462_p1),
    .dout(mul_i_i_24_i_fu_462_p2)
);

myproject_mul_31ns_15s_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 46 ))
mul_31ns_15s_46_1_1_U2465(
    .din0(mul_i_i_28_i_fu_467_p0),
    .din1(mul_i_i_28_i_fu_467_p1),
    .dout(mul_i_i_28_i_fu_467_p2)
);

myproject_mul_31ns_15s_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 46 ))
mul_31ns_15s_46_1_1_U2466(
    .din0(mul_i_i_32_i_fu_472_p0),
    .din1(mul_i_i_32_i_fu_472_p1),
    .dout(mul_i_i_32_i_fu_472_p2)
);

myproject_mul_31ns_15s_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 46 ))
mul_31ns_15s_46_1_1_U2467(
    .din0(mul_i_i_38_i_fu_477_p0),
    .din1(mul_i_i_38_i_fu_477_p1),
    .dout(mul_i_i_38_i_fu_477_p2)
);

myproject_mul_31ns_15s_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 46 ))
mul_31ns_15s_46_1_1_U2468(
    .din0(mul_i_i_40_i_fu_482_p0),
    .din1(mul_i_i_40_i_fu_482_p1),
    .dout(mul_i_i_40_i_fu_482_p2)
);

myproject_mul_31ns_16s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_31ns_16s_47_1_1_U2469(
    .din0(mul_i_i_3_i_fu_487_p0),
    .din1(mul_i_i_3_i_fu_487_p1),
    .dout(mul_i_i_3_i_fu_487_p2)
);

myproject_mul_31ns_16s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_31ns_16s_47_1_1_U2470(
    .din0(mul_i_i_5_i_fu_492_p0),
    .din1(mul_i_i_5_i_fu_492_p1),
    .dout(mul_i_i_5_i_fu_492_p2)
);

myproject_mul_31ns_16s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_31ns_16s_47_1_1_U2471(
    .din0(mul_i_i_16_i_fu_497_p0),
    .din1(mul_i_i_16_i_fu_497_p1),
    .dout(mul_i_i_16_i_fu_497_p2)
);

myproject_mul_31ns_16s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_31ns_16s_47_1_1_U2472(
    .din0(mul_i_i_23_i_fu_502_p0),
    .din1(mul_i_i_23_i_fu_502_p1),
    .dout(mul_i_i_23_i_fu_502_p2)
);

myproject_mul_31ns_16s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_31ns_16s_47_1_1_U2473(
    .din0(mul_i_i_30_i_fu_507_p0),
    .din1(mul_i_i_30_i_fu_507_p1),
    .dout(mul_i_i_30_i_fu_507_p2)
);

myproject_mul_31ns_16s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_31ns_16s_47_1_1_U2474(
    .din0(mul_i_i_33_i_fu_512_p0),
    .din1(mul_i_i_33_i_fu_512_p1),
    .dout(mul_i_i_33_i_fu_512_p2)
);

myproject_mul_31ns_16s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_31ns_16s_47_1_1_U2475(
    .din0(mul_i_i_36_i_fu_517_p0),
    .din1(mul_i_i_36_i_fu_517_p1),
    .dout(mul_i_i_36_i_fu_517_p2)
);

myproject_mul_31ns_16s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 47 ))
mul_31ns_16s_47_1_1_U2476(
    .din0(mul_i_i_41_i_fu_522_p0),
    .din1(mul_i_i_41_i_fu_522_p1),
    .dout(mul_i_i_41_i_fu_522_p2)
);

myproject_mul_31ns_17s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 48 ))
mul_31ns_17s_48_1_1_U2477(
    .din0(mul_i_i_20_i_fu_527_p0),
    .din1(mul_i_i_20_i_fu_527_p1),
    .dout(mul_i_i_20_i_fu_527_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        layer8_out_0_preg <= 32'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            layer8_out_0_preg <= add_ln53_1838_fu_1543_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        layer8_out_1_preg <= 32'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            layer8_out_1_preg <= add_ln53_1854_fu_1664_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        layer8_out_2_preg <= 32'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            layer8_out_2_preg <= add_ln53_1870_fu_1789_p2;
        end
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer8_out_0 = add_ln53_1838_fu_1543_p2;
    end else begin
        layer8_out_0 = layer8_out_0_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer8_out_0_ap_vld = 1'b1;
    end else begin
        layer8_out_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer8_out_1 = add_ln53_1854_fu_1664_p2;
    end else begin
        layer8_out_1 = layer8_out_1_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer8_out_1_ap_vld = 1'b1;
    end else begin
        layer8_out_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer8_out_2 = add_ln53_1870_fu_1789_p2;
    end else begin
        layer8_out_2 = layer8_out_2_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer8_out_2_ap_vld = 1'b1;
    end else begin
        layer8_out_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln53_1824_fu_1423_p2 = (conv_i_i_i_6_i_cast_fu_705_p4 + conv_i_i_i_7_i_cast_cast_fu_740_p1);

assign add_ln53_1825_fu_1433_p2 = (zext_ln53_fu_1429_p1 + add_ln53_fu_1417_p2);

assign add_ln53_1826_fu_1443_p2 = (conv_i_i_i_8_i_cast_cast_fu_765_p1 + conv_i_i_i_10_i_cast_cast_fu_844_p1);

assign add_ln53_1827_fu_1453_p2 = (conv_i_i_i_11_i_cast_fu_859_p4 + conv_i_i_i_13_i_cast_cast_fu_919_p1);

assign add_ln53_1828_fu_1463_p2 = (zext_ln53_3_fu_1459_p1 + zext_ln53_2_fu_1449_p1);

assign add_ln53_1829_fu_1469_p2 = (add_ln53_1828_fu_1463_p2 + zext_ln53_1_fu_1439_p1);

assign add_ln53_1830_fu_1479_p2 = (conv_i_i_i_14_i_cast_cast_fu_948_p1 + conv_i_i_i_15_i_cast_fu_967_p4);

assign add_ln53_1831_fu_1489_p2 = ($signed(p_cast61_cast_fu_636_p1) + $signed(p_cast62_cast_fu_686_p1));

assign add_ln53_1832_fu_1495_p2 = (add_ln53_1831_fu_1489_p2 + zext_ln53_5_fu_1485_p1);

assign add_ln53_1833_fu_1501_p2 = ($signed(p_cast_cast_fu_553_p1) + $signed(p_cast64_cast_fu_890_p1));

assign add_ln53_1834_fu_1511_p2 = ($signed(p_cast63_cast_fu_819_p1) + $signed(28'd27418));

assign add_ln53_1835_fu_1521_p2 = ($signed(sext_ln53_1274_fu_1517_p1) + $signed(p_cast60_cast_fu_582_p1));

assign add_ln53_1836_fu_1531_p2 = ($signed(sext_ln53_1275_fu_1527_p1) + $signed(sext_ln53_fu_1507_p1));

assign add_ln53_1837_fu_1537_p2 = (add_ln53_1836_fu_1531_p2 + add_ln53_1832_fu_1495_p2);

assign add_ln53_1838_fu_1543_p2 = (add_ln53_1837_fu_1537_p2 + zext_ln53_4_fu_1475_p1);

assign add_ln53_1839_fu_1550_p2 = (conv_i_i_i_17_i_cast_cast_fu_1001_p1 + conv_i_i_i_18_i_cast_fu_1005_p4);

assign add_ln53_1840_fu_1560_p2 = (conv_i_i_i_19_i_cast_cast_fu_1025_p1 + conv_i_i_i_20_i_fu_1029_p4);

assign add_ln53_1841_fu_1566_p2 = (add_ln53_1840_fu_1560_p2 + zext_ln53_6_fu_1556_p1);

assign add_ln53_1842_fu_1572_p2 = (conv_i_i_i_25_i_cast_cast_fu_1105_p1 + conv_i_i_i_27_i_cast_cast_fu_1133_p1);

assign add_ln53_1843_fu_1582_p2 = (conv_i_i_i_29_i_cast_cast_fu_1161_p1 + conv_i_i_i_31_i_cast_cast_fu_1189_p1);

assign add_ln53_1844_fu_1592_p2 = (zext_ln53_8_fu_1588_p1 + zext_ln53_7_fu_1578_p1);

assign add_ln53_1845_fu_1598_p2 = (add_ln53_1844_fu_1592_p2 + add_ln53_1841_fu_1566_p2);

assign add_ln53_1846_fu_1604_p2 = ($signed(p_cast65_cast_fu_987_p1) + $signed(p_cast68_cast_fu_1077_p1));

assign add_ln53_1847_fu_1610_p2 = ($signed(p_cast72_cast_fu_1175_p1) + $signed(p_cast69_cast_fu_1091_p1));

assign add_ln53_1848_fu_1616_p2 = (add_ln53_1847_fu_1610_p2 + add_ln53_1846_fu_1604_p2);

assign add_ln53_1849_fu_1622_p2 = ($signed(p_cast71_cast_fu_1147_p1) + $signed(p_cast67_cast_fu_1063_p1));

assign add_ln53_1850_fu_1628_p2 = ($signed(p_cast66_cast_fu_1049_p1) + $signed(28'd19845));

assign add_ln53_1851_fu_1638_p2 = ($signed(sext_ln53_1276_fu_1634_p1) + $signed(p_cast70_cast_fu_1119_p1));

assign add_ln53_1852_fu_1648_p2 = ($signed(sext_ln53_1277_fu_1644_p1) + $signed(add_ln53_1849_fu_1622_p2));

assign add_ln53_1853_fu_1658_p2 = ($signed(sext_ln53_1278_fu_1654_p1) + $signed(add_ln53_1848_fu_1616_p2));

assign add_ln53_1854_fu_1664_p2 = (add_ln53_1853_fu_1658_p2 + add_ln53_1845_fu_1598_p2);

assign add_ln53_1855_fu_1671_p2 = (conv_i_i_i_35_i_cast_cast_fu_1245_p1 + conv_i_i_i_39_i_cast_cast_fu_1301_p1);

assign add_ln53_1856_fu_1681_p2 = (conv_i_i_i_42_i_cast_cast_fu_1343_p1 + conv_i_i_i_43_i_cast_cast_fu_1357_p1);

assign add_ln53_1857_fu_1691_p2 = (zext_ln53_10_fu_1687_p1 + zext_ln53_9_fu_1677_p1);

assign add_ln53_1858_fu_1697_p2 = (conv_i_i_i_45_i_cast_cast_fu_1385_p1 + conv_i_i_i_46_i_cast_cast_fu_1399_p1);

assign add_ln53_1859_fu_1707_p2 = ($signed(conv_i_i_i_47_i_cast_cast_fu_1413_p1) + $signed(p_cast74_cast_fu_1217_p1));

assign add_ln53_1860_fu_1713_p2 = (add_ln53_1859_fu_1707_p2 + zext_ln53_11_fu_1703_p1);

assign add_ln53_1861_fu_1719_p2 = (add_ln53_1860_fu_1713_p2 + add_ln53_1857_fu_1691_p2);

assign add_ln53_1862_fu_1725_p2 = ($signed(p_cast76_cast_fu_1259_p1) + $signed(p_cast80_cast_fu_1329_p1));

assign add_ln53_1863_fu_1731_p2 = ($signed(p_cast73_cast_fu_1203_p1) + $signed(p_cast78_cast_fu_1287_p1));

assign add_ln53_1864_fu_1741_p2 = ($signed(sext_ln53_1279_fu_1737_p1) + $signed(add_ln53_1862_fu_1725_p2));

assign add_ln53_1865_fu_1747_p2 = ($signed(p_cast79_cast_fu_1315_p1) + $signed(p_cast75_cast_fu_1231_p1));

assign add_ln53_1866_fu_1753_p2 = ($signed(p_cast81_cast_fu_1371_p1) + $signed(28'd268421195));

assign add_ln53_1867_fu_1763_p2 = ($signed(sext_ln53_1280_fu_1759_p1) + $signed(p_cast77_cast_fu_1273_p1));

assign add_ln53_1868_fu_1773_p2 = ($signed(sext_ln53_1281_fu_1769_p1) + $signed(add_ln53_1865_fu_1747_p2));

assign add_ln53_1869_fu_1783_p2 = ($signed(sext_ln53_1282_fu_1779_p1) + $signed(add_ln53_1864_fu_1741_p2));

assign add_ln53_1870_fu_1789_p2 = (add_ln53_1869_fu_1783_p2 + add_ln53_1861_fu_1719_p2);

assign add_ln53_fu_1417_p2 = (conv_i_i_i_2_i_cast_cast_fu_611_p1 + conv_i_i_i_4_i_cast_fu_655_p4);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign conv_i_i_10_i_cast_fu_828_p1 = p_read10;

assign conv_i_i_11_i_cast_fu_853_p1 = p_read11;

assign conv_i_i_12_i_cast_fu_874_p1 = p_read12;

assign conv_i_i_3_i_cast5_fu_615_p1 = p_read3;

assign conv_i_i_5_i_cast7_fu_665_p1 = p_read5;

assign conv_i_i_8_i_cast10_fu_744_p1 = p_read8;

assign conv_i_i_i_10_i_cast_cast_fu_844_p1 = tmp_20_fu_834_p4;

assign conv_i_i_i_11_i_cast_fu_859_p4 = {{mul_i_i_11_i_fu_372_p2[45:16]}};

assign conv_i_i_i_13_i_cast_cast_fu_919_p1 = tmp_21_fu_909_p4;

assign conv_i_i_i_14_i_cast_cast_fu_948_p1 = tmp_22_fu_938_p4;

assign conv_i_i_i_15_i_cast_fu_967_p4 = {{mul_i_i_15_i_fu_347_p2[44:16]}};

assign conv_i_i_i_17_i_cast_cast_fu_1001_p1 = tmp_23_fu_991_p4;

assign conv_i_i_i_18_i_cast_fu_1005_p4 = {{mul_i_i_18_i_fu_377_p2[45:16]}};

assign conv_i_i_i_19_i_cast_cast_fu_1025_p1 = tmp_24_fu_1015_p4;

assign conv_i_i_i_20_i_fu_1029_p4 = {{mul_i_i_20_i_fu_527_p2[47:16]}};

assign conv_i_i_i_25_i_cast_cast_fu_1105_p1 = tmp_25_fu_1095_p4;

assign conv_i_i_i_27_i_cast_cast_fu_1133_p1 = tmp_26_fu_1123_p4;

assign conv_i_i_i_29_i_cast_cast_fu_1161_p1 = tmp_27_fu_1151_p4;

assign conv_i_i_i_2_i_cast_cast_fu_611_p1 = tmp_fu_601_p4;

assign conv_i_i_i_31_i_cast_cast_fu_1189_p1 = tmp_28_fu_1179_p4;

assign conv_i_i_i_35_i_cast_cast_fu_1245_p1 = tmp_29_fu_1235_p4;

assign conv_i_i_i_39_i_cast_cast_fu_1301_p1 = tmp_30_fu_1291_p4;

assign conv_i_i_i_42_i_cast_cast_fu_1343_p1 = tmp_31_fu_1333_p4;

assign conv_i_i_i_43_i_cast_cast_fu_1357_p1 = tmp_32_fu_1347_p4;

assign conv_i_i_i_45_i_cast_cast_fu_1385_p1 = tmp_33_fu_1375_p4;

assign conv_i_i_i_46_i_cast_cast_fu_1399_p1 = tmp_34_fu_1389_p4;

assign conv_i_i_i_47_i_cast_cast_fu_1413_p1 = tmp_35_fu_1403_p4;

assign conv_i_i_i_4_i_cast_fu_655_p4 = {{mul_i_i_4_i_fu_367_p2[45:16]}};

assign conv_i_i_i_6_i_cast_fu_705_p4 = {{mul_i_i_6_i_fu_317_p2[43:16]}};

assign conv_i_i_i_7_i_cast_cast_fu_740_p1 = tmp_s_fu_730_p4;

assign conv_i_i_i_8_i_cast_cast_fu_765_p1 = tmp_19_fu_755_p4;

assign conv_i_i_i_cast_fu_537_p1 = p_read;

assign mul_i_i_10_i_fu_327_p0 = conv_i_i_10_i_cast_fu_828_p1;

assign mul_i_i_10_i_fu_327_p1 = 44'd4363;

assign mul_i_i_11_i_fu_372_p0 = conv_i_i_11_i_cast_fu_853_p1;

assign mul_i_i_11_i_fu_372_p1 = 46'd17094;

assign mul_i_i_12_i_fu_457_p0 = conv_i_i_12_i_cast_fu_874_p1;

assign mul_i_i_12_i_fu_457_p1 = 46'd70368744165926;

assign mul_i_i_13_i_fu_332_p0 = mul_i_i_13_i_fu_332_p00;

assign mul_i_i_13_i_fu_332_p00 = p_read13;

assign mul_i_i_13_i_fu_332_p1 = 44'd4526;

assign mul_i_i_14_i_fu_302_p0 = mul_i_i_14_i_fu_302_p00;

assign mul_i_i_14_i_fu_302_p00 = p_read14;

assign mul_i_i_14_i_fu_302_p1 = 42'd1478;

assign mul_i_i_15_i_fu_347_p0 = mul_i_i_15_i_fu_347_p00;

assign mul_i_i_15_i_fu_347_p00 = p_read15;

assign mul_i_i_15_i_fu_347_p1 = 45'd8394;

assign mul_i_i_16_i_fu_497_p0 = mul_i_i_16_i_fu_497_p00;

assign mul_i_i_16_i_fu_497_p00 = p_read;

assign mul_i_i_16_i_fu_497_p1 = 47'd140737488336015;

assign mul_i_i_17_i_fu_352_p0 = mul_i_i_17_i_fu_352_p00;

assign mul_i_i_17_i_fu_352_p00 = p_read1;

assign mul_i_i_17_i_fu_352_p1 = 45'd9193;

assign mul_i_i_18_i_fu_377_p0 = mul_i_i_18_i_fu_377_p00;

assign mul_i_i_18_i_fu_377_p00 = p_read2;

assign mul_i_i_18_i_fu_377_p1 = 46'd21386;

assign mul_i_i_19_i_fu_382_p0 = conv_i_i_3_i_cast5_fu_615_p1;

assign mul_i_i_19_i_fu_382_p1 = 46'd27693;

assign mul_i_i_1_i_fu_417_p0 = mul_i_i_1_i_fu_417_p00;

assign mul_i_i_1_i_fu_417_p00 = p_read1;

assign mul_i_i_1_i_fu_417_p1 = 43'd8796093020798;

assign mul_i_i_20_i_fu_527_p0 = mul_i_i_20_i_fu_527_p00;

assign mul_i_i_20_i_fu_527_p00 = p_read4;

assign mul_i_i_20_i_fu_527_p1 = 48'd281474976673158;

assign mul_i_i_21_i_fu_422_p0 = conv_i_i_5_i_cast7_fu_665_p1;

assign mul_i_i_21_i_fu_422_p1 = 43'd8796093020418;

assign mul_i_i_22_i_fu_447_p0 = mul_i_i_22_i_fu_447_p00;

assign mul_i_i_22_i_fu_447_p00 = p_read6;

assign mul_i_i_22_i_fu_447_p1 = 45'd35184372084198;

assign mul_i_i_23_i_fu_502_p0 = mul_i_i_23_i_fu_502_p00;

assign mul_i_i_23_i_fu_502_p00 = p_read7;

assign mul_i_i_23_i_fu_502_p1 = 47'd140737488331894;

assign mul_i_i_24_i_fu_462_p0 = conv_i_i_8_i_cast10_fu_744_p1;

assign mul_i_i_24_i_fu_462_p1 = 46'd70368744166834;

assign mul_i_i_25_i_fu_387_p0 = mul_i_i_25_i_fu_387_p00;

assign mul_i_i_25_i_fu_387_p00 = p_read9;

assign mul_i_i_25_i_fu_387_p1 = 46'd26688;

assign mul_i_i_26_i_fu_437_p0 = conv_i_i_10_i_cast_fu_828_p1;

assign mul_i_i_26_i_fu_437_p1 = 44'd17592186041509;

assign mul_i_i_27_i_fu_337_p0 = mul_i_i_27_i_fu_337_p00;

assign mul_i_i_27_i_fu_337_p00 = p_read11;

assign mul_i_i_27_i_fu_337_p1 = 44'd7606;

assign mul_i_i_28_i_fu_467_p0 = conv_i_i_12_i_cast_fu_874_p1;

assign mul_i_i_28_i_fu_467_p1 = 46'd70368744168883;

assign mul_i_i_29_i_fu_392_p0 = mul_i_i_29_i_fu_392_p00;

assign mul_i_i_29_i_fu_392_p00 = p_read13;

assign mul_i_i_29_i_fu_392_p1 = 46'd30415;

assign mul_i_i_2_i_fu_307_p0 = mul_i_i_2_i_fu_307_p00;

assign mul_i_i_2_i_fu_307_p00 = p_read2;

assign mul_i_i_2_i_fu_307_p1 = 43'd2514;

assign mul_i_i_30_i_fu_507_p0 = mul_i_i_30_i_fu_507_p00;

assign mul_i_i_30_i_fu_507_p00 = p_read14;

assign mul_i_i_30_i_fu_507_p1 = 47'd140737488333008;

assign mul_i_i_31_i_fu_342_p0 = mul_i_i_31_i_fu_342_p00;

assign mul_i_i_31_i_fu_342_p00 = p_read15;

assign mul_i_i_31_i_fu_342_p1 = 44'd5888;

assign mul_i_i_32_i_fu_472_p0 = conv_i_i_i_cast_fu_537_p1;

assign mul_i_i_32_i_fu_472_p1 = 46'd70368744168148;

assign mul_i_i_33_i_fu_512_p0 = mul_i_i_33_i_fu_512_p00;

assign mul_i_i_33_i_fu_512_p00 = p_read1;

assign mul_i_i_33_i_fu_512_p1 = 47'd140737488328489;

assign mul_i_i_34_i_fu_442_p0 = mul_i_i_34_i_fu_442_p00;

assign mul_i_i_34_i_fu_442_p00 = p_read2;

assign mul_i_i_34_i_fu_442_p1 = 44'd17592186041711;

assign mul_i_i_35_i_fu_397_p0 = conv_i_i_3_i_cast5_fu_615_p1;

assign mul_i_i_35_i_fu_397_p1 = 46'd23189;

assign mul_i_i_36_i_fu_517_p0 = mul_i_i_36_i_fu_517_p00;

assign mul_i_i_36_i_fu_517_p00 = p_read4;

assign mul_i_i_36_i_fu_517_p1 = 47'd140737488323143;

assign mul_i_i_37_i_fu_427_p0 = conv_i_i_5_i_cast7_fu_665_p1;

assign mul_i_i_37_i_fu_427_p1 = 43'd8796093020394;

assign mul_i_i_38_i_fu_477_p0 = mul_i_i_38_i_fu_477_p00;

assign mul_i_i_38_i_fu_477_p00 = p_read6;

assign mul_i_i_38_i_fu_477_p1 = 46'd70368744161305;

assign mul_i_i_39_i_fu_402_p0 = mul_i_i_39_i_fu_402_p00;

assign mul_i_i_39_i_fu_402_p00 = p_read7;

assign mul_i_i_39_i_fu_402_p1 = 46'd24237;

assign mul_i_i_3_i_fu_487_p0 = mul_i_i_3_i_fu_487_p00;

assign mul_i_i_3_i_fu_487_p00 = p_read3;

assign mul_i_i_3_i_fu_487_p1 = 47'd140737488334168;

assign mul_i_i_40_i_fu_482_p0 = conv_i_i_8_i_cast10_fu_744_p1;

assign mul_i_i_40_i_fu_482_p1 = 46'd70368744168073;

assign mul_i_i_41_i_fu_522_p0 = mul_i_i_41_i_fu_522_p00;

assign mul_i_i_41_i_fu_522_p00 = p_read9;

assign mul_i_i_41_i_fu_522_p1 = 47'd140737488335977;

assign mul_i_i_42_i_fu_407_p0 = mul_i_i_42_i_fu_407_p00;

assign mul_i_i_42_i_fu_407_p00 = p_read10;

assign mul_i_i_42_i_fu_407_p1 = 46'd23510;

assign mul_i_i_43_i_fu_412_p0 = conv_i_i_11_i_cast_fu_853_p1;

assign mul_i_i_43_i_fu_412_p1 = 46'd22830;

assign mul_i_i_44_i_fu_432_p0 = mul_i_i_44_i_fu_432_p00;

assign mul_i_i_44_i_fu_432_p00 = p_read12;

assign mul_i_i_44_i_fu_432_p1 = 43'd8796093021123;

assign mul_i_i_45_i_fu_357_p0 = mul_i_i_45_i_fu_357_p00;

assign mul_i_i_45_i_fu_357_p00 = p_read13;

assign mul_i_i_45_i_fu_357_p1 = 45'd10074;

assign mul_i_i_46_i_fu_362_p0 = mul_i_i_46_i_fu_362_p00;

assign mul_i_i_46_i_fu_362_p00 = p_read14;

assign mul_i_i_46_i_fu_362_p1 = 45'd9772;

assign mul_i_i_47_i_fu_312_p0 = mul_i_i_47_i_fu_312_p00;

assign mul_i_i_47_i_fu_312_p00 = p_read15;

assign mul_i_i_47_i_fu_312_p1 = 43'd3981;

assign mul_i_i_4_i_fu_367_p0 = mul_i_i_4_i_fu_367_p00;

assign mul_i_i_4_i_fu_367_p00 = p_read4;

assign mul_i_i_4_i_fu_367_p1 = 46'd17626;

assign mul_i_i_5_i_fu_492_p0 = mul_i_i_5_i_fu_492_p00;

assign mul_i_i_5_i_fu_492_p00 = p_read5;

assign mul_i_i_5_i_fu_492_p1 = 47'd140737488336401;

assign mul_i_i_6_i_fu_317_p0 = mul_i_i_6_i_fu_317_p00;

assign mul_i_i_6_i_fu_317_p00 = p_read6;

assign mul_i_i_6_i_fu_317_p1 = 44'd4906;

assign mul_i_i_7_i_fu_297_p0 = mul_i_i_7_i_fu_297_p00;

assign mul_i_i_7_i_fu_297_p00 = p_read7;

assign mul_i_i_7_i_fu_297_p1 = 42'd1937;

assign mul_i_i_8_i_fu_322_p0 = mul_i_i_8_i_fu_322_p00;

assign mul_i_i_8_i_fu_322_p00 = p_read8;

assign mul_i_i_8_i_fu_322_p1 = 44'd7894;

assign mul_i_i_9_i_fu_803_p2 = (p_shl1_cast_fu_799_p1 - p_shl_cast_fu_787_p1);

assign mul_i_i_i_fu_452_p0 = conv_i_i_i_cast_fu_537_p1;

assign mul_i_i_i_fu_452_p1 = 46'd70368744167206;

assign p_cast10_fu_1081_p4 = {{mul_i_i_24_i_fu_462_p2[45:16]}};

assign p_cast11_fu_1109_p4 = {{mul_i_i_26_i_fu_437_p2[43:16]}};

assign p_cast12_fu_1137_p4 = {{mul_i_i_28_i_fu_467_p2[45:16]}};

assign p_cast13_fu_1165_p4 = {{mul_i_i_30_i_fu_507_p2[46:16]}};

assign p_cast14_fu_1193_p4 = {{mul_i_i_32_i_fu_472_p2[45:16]}};

assign p_cast15_fu_1207_p4 = {{mul_i_i_33_i_fu_512_p2[46:16]}};

assign p_cast16_fu_1221_p4 = {{mul_i_i_34_i_fu_442_p2[43:16]}};

assign p_cast17_fu_1249_p4 = {{mul_i_i_36_i_fu_517_p2[46:16]}};

assign p_cast18_fu_1263_p4 = {{mul_i_i_37_i_fu_427_p2[42:16]}};

assign p_cast19_fu_1277_p4 = {{mul_i_i_38_i_fu_477_p2[45:16]}};

assign p_cast1_fu_572_p4 = {{mul_i_i_1_i_fu_417_p2[42:16]}};

assign p_cast20_fu_1305_p4 = {{mul_i_i_40_i_fu_482_p2[45:16]}};

assign p_cast21_fu_1319_p4 = {{mul_i_i_41_i_fu_522_p2[46:16]}};

assign p_cast22_fu_1361_p4 = {{mul_i_i_44_i_fu_432_p2[42:16]}};

assign p_cast2_fu_626_p4 = {{mul_i_i_3_i_fu_487_p2[46:16]}};

assign p_cast3_fu_676_p4 = {{mul_i_i_5_i_fu_492_p2[46:16]}};

assign p_cast4_fu_809_p4 = {{mul_i_i_9_i_fu_803_p2[42:16]}};

assign p_cast5_fu_880_p4 = {{mul_i_i_12_i_fu_457_p2[45:16]}};

assign p_cast60_cast_fu_582_p1 = $signed(p_cast1_fu_572_p4);

assign p_cast61_cast_fu_636_p1 = $signed(p_cast2_fu_626_p4);

assign p_cast62_cast_fu_686_p1 = $signed(p_cast3_fu_676_p4);

assign p_cast63_cast_fu_819_p1 = $signed(p_cast4_fu_809_p4);

assign p_cast64_cast_fu_890_p1 = $signed(p_cast5_fu_880_p4);

assign p_cast65_cast_fu_987_p1 = $signed(p_cast6_fu_977_p4);

assign p_cast66_cast_fu_1049_p1 = $signed(p_cast7_fu_1039_p4);

assign p_cast67_cast_fu_1063_p1 = $signed(p_cast8_fu_1053_p4);

assign p_cast68_cast_fu_1077_p1 = $signed(p_cast9_fu_1067_p4);

assign p_cast69_cast_fu_1091_p1 = $signed(p_cast10_fu_1081_p4);

assign p_cast6_fu_977_p4 = {{mul_i_i_16_i_fu_497_p2[46:16]}};

assign p_cast70_cast_fu_1119_p1 = $signed(p_cast11_fu_1109_p4);

assign p_cast71_cast_fu_1147_p1 = $signed(p_cast12_fu_1137_p4);

assign p_cast72_cast_fu_1175_p1 = $signed(p_cast13_fu_1165_p4);

assign p_cast73_cast_fu_1203_p1 = $signed(p_cast14_fu_1193_p4);

assign p_cast74_cast_fu_1217_p1 = $signed(p_cast15_fu_1207_p4);

assign p_cast75_cast_fu_1231_p1 = $signed(p_cast16_fu_1221_p4);

assign p_cast76_cast_fu_1259_p1 = $signed(p_cast17_fu_1249_p4);

assign p_cast77_cast_fu_1273_p1 = $signed(p_cast18_fu_1263_p4);

assign p_cast78_cast_fu_1287_p1 = $signed(p_cast19_fu_1277_p4);

assign p_cast79_cast_fu_1315_p1 = $signed(p_cast20_fu_1305_p4);

assign p_cast7_fu_1039_p4 = {{mul_i_i_21_i_fu_422_p2[42:16]}};

assign p_cast80_cast_fu_1329_p1 = $signed(p_cast21_fu_1319_p4);

assign p_cast81_cast_fu_1371_p1 = $signed(p_cast22_fu_1361_p4);

assign p_cast8_fu_1053_p4 = {{mul_i_i_22_i_fu_447_p2[44:16]}};

assign p_cast9_fu_1067_p4 = {{mul_i_i_23_i_fu_502_p2[46:16]}};

assign p_cast_cast_fu_553_p1 = $signed(p_cast_fu_543_p4);

assign p_cast_fu_543_p4 = {{mul_i_i_i_fu_452_p2[45:16]}};

assign p_shl1_cast_fu_799_p1 = p_shl1_fu_791_p3;

assign p_shl1_fu_791_p3 = {{p_read9}, {3'd0}};

assign p_shl_cast_fu_787_p1 = p_shl_fu_779_p3;

assign p_shl_fu_779_p3 = {{p_read9}, {11'd0}};

assign sext_ln53_1274_fu_1517_p1 = $signed(add_ln53_1834_fu_1511_p2);

assign sext_ln53_1275_fu_1527_p1 = $signed(add_ln53_1835_fu_1521_p2);

assign sext_ln53_1276_fu_1634_p1 = $signed(add_ln53_1850_fu_1628_p2);

assign sext_ln53_1277_fu_1644_p1 = $signed(add_ln53_1851_fu_1638_p2);

assign sext_ln53_1278_fu_1654_p1 = $signed(add_ln53_1852_fu_1648_p2);

assign sext_ln53_1279_fu_1737_p1 = $signed(add_ln53_1863_fu_1731_p2);

assign sext_ln53_1280_fu_1759_p1 = $signed(add_ln53_1866_fu_1753_p2);

assign sext_ln53_1281_fu_1769_p1 = $signed(add_ln53_1867_fu_1763_p2);

assign sext_ln53_1282_fu_1779_p1 = $signed(add_ln53_1868_fu_1773_p2);

assign sext_ln53_fu_1507_p1 = $signed(add_ln53_1833_fu_1501_p2);

assign tmp_19_fu_755_p4 = {{mul_i_i_8_i_fu_322_p2[43:16]}};

assign tmp_20_fu_834_p4 = {{mul_i_i_10_i_fu_327_p2[43:16]}};

assign tmp_21_fu_909_p4 = {{mul_i_i_13_i_fu_332_p2[43:16]}};

assign tmp_22_fu_938_p4 = {{mul_i_i_14_i_fu_302_p2[41:16]}};

assign tmp_23_fu_991_p4 = {{mul_i_i_17_i_fu_352_p2[44:16]}};

assign tmp_24_fu_1015_p4 = {{mul_i_i_19_i_fu_382_p2[45:16]}};

assign tmp_25_fu_1095_p4 = {{mul_i_i_25_i_fu_387_p2[45:16]}};

assign tmp_26_fu_1123_p4 = {{mul_i_i_27_i_fu_337_p2[43:16]}};

assign tmp_27_fu_1151_p4 = {{mul_i_i_29_i_fu_392_p2[45:16]}};

assign tmp_28_fu_1179_p4 = {{mul_i_i_31_i_fu_342_p2[43:16]}};

assign tmp_29_fu_1235_p4 = {{mul_i_i_35_i_fu_397_p2[45:16]}};

assign tmp_30_fu_1291_p4 = {{mul_i_i_39_i_fu_402_p2[45:16]}};

assign tmp_31_fu_1333_p4 = {{mul_i_i_42_i_fu_407_p2[45:16]}};

assign tmp_32_fu_1347_p4 = {{mul_i_i_43_i_fu_412_p2[45:16]}};

assign tmp_33_fu_1375_p4 = {{mul_i_i_45_i_fu_357_p2[44:16]}};

assign tmp_34_fu_1389_p4 = {{mul_i_i_46_i_fu_362_p2[44:16]}};

assign tmp_35_fu_1403_p4 = {{mul_i_i_47_i_fu_312_p2[42:16]}};

assign tmp_fu_601_p4 = {{mul_i_i_2_i_fu_307_p2[42:16]}};

assign tmp_s_fu_730_p4 = {{mul_i_i_7_i_fu_297_p2[41:16]}};

assign zext_ln53_10_fu_1687_p1 = add_ln53_1856_fu_1681_p2;

assign zext_ln53_11_fu_1703_p1 = add_ln53_1858_fu_1697_p2;

assign zext_ln53_1_fu_1439_p1 = add_ln53_1825_fu_1433_p2;

assign zext_ln53_2_fu_1449_p1 = add_ln53_1826_fu_1443_p2;

assign zext_ln53_3_fu_1459_p1 = add_ln53_1827_fu_1453_p2;

assign zext_ln53_4_fu_1475_p1 = add_ln53_1829_fu_1469_p2;

assign zext_ln53_5_fu_1485_p1 = add_ln53_1830_fu_1479_p2;

assign zext_ln53_6_fu_1556_p1 = add_ln53_1839_fu_1550_p2;

assign zext_ln53_7_fu_1578_p1 = add_ln53_1842_fu_1572_p2;

assign zext_ln53_8_fu_1588_p1 = add_ln53_1843_fu_1582_p2;

assign zext_ln53_9_fu_1677_p1 = add_ln53_1855_fu_1671_p2;

assign zext_ln53_fu_1429_p1 = add_ln53_1824_fu_1423_p2;

endmodule //myproject_dense_resource_ap_fixed_32_16_4_0_0_ap_fixed_32_16_5_3_0_config8_s
