// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::ap_ST_fsm_state1 = "1";
const sc_lv<32> relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<31> relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::ap_const_lv31_0 = "0000000000000000000000000000000";
const bool relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::ap_const_boolean_1 = true;

relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln45_fu_154_p3 );
    sensitive << ( ap_return_0_preg );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln45_1_fu_172_p3 );
    sensitive << ( ap_return_1_preg );

    SC_METHOD(thread_ap_return_10);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln45_10_fu_334_p3 );
    sensitive << ( ap_return_10_preg );

    SC_METHOD(thread_ap_return_11);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln45_11_fu_352_p3 );
    sensitive << ( ap_return_11_preg );

    SC_METHOD(thread_ap_return_12);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln45_12_fu_370_p3 );
    sensitive << ( ap_return_12_preg );

    SC_METHOD(thread_ap_return_13);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln45_13_fu_388_p3 );
    sensitive << ( ap_return_13_preg );

    SC_METHOD(thread_ap_return_14);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln45_14_fu_406_p3 );
    sensitive << ( ap_return_14_preg );

    SC_METHOD(thread_ap_return_15);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln45_15_fu_424_p3 );
    sensitive << ( ap_return_15_preg );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln45_2_fu_190_p3 );
    sensitive << ( ap_return_2_preg );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln45_3_fu_208_p3 );
    sensitive << ( ap_return_3_preg );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln45_4_fu_226_p3 );
    sensitive << ( ap_return_4_preg );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln45_5_fu_244_p3 );
    sensitive << ( ap_return_5_preg );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln45_6_fu_262_p3 );
    sensitive << ( ap_return_6_preg );

    SC_METHOD(thread_ap_return_7);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln45_7_fu_280_p3 );
    sensitive << ( ap_return_7_preg );

    SC_METHOD(thread_ap_return_8);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln45_8_fu_298_p3 );
    sensitive << ( ap_return_8_preg );

    SC_METHOD(thread_ap_return_9);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln45_9_fu_316_p3 );
    sensitive << ( ap_return_9_preg );

    SC_METHOD(thread_icmp_ln1494_10_fu_328_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_10_V_read );

    SC_METHOD(thread_icmp_ln1494_11_fu_346_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_11_V_read );

    SC_METHOD(thread_icmp_ln1494_12_fu_364_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_12_V_read );

    SC_METHOD(thread_icmp_ln1494_13_fu_382_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_13_V_read );

    SC_METHOD(thread_icmp_ln1494_14_fu_400_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_14_V_read );

    SC_METHOD(thread_icmp_ln1494_15_fu_418_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_15_V_read );

    SC_METHOD(thread_icmp_ln1494_1_fu_166_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_icmp_ln1494_2_fu_184_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_icmp_ln1494_3_fu_202_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_icmp_ln1494_4_fu_220_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_icmp_ln1494_5_fu_238_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_icmp_ln1494_6_fu_256_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_6_V_read );

    SC_METHOD(thread_icmp_ln1494_7_fu_274_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_icmp_ln1494_8_fu_292_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_icmp_ln1494_9_fu_310_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_icmp_ln1494_fu_148_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_select_ln45_10_fu_334_p3);
    sensitive << ( icmp_ln1494_10_fu_328_p2 );
    sensitive << ( trunc_ln1494_10_fu_324_p1 );

    SC_METHOD(thread_select_ln45_11_fu_352_p3);
    sensitive << ( icmp_ln1494_11_fu_346_p2 );
    sensitive << ( trunc_ln1494_11_fu_342_p1 );

    SC_METHOD(thread_select_ln45_12_fu_370_p3);
    sensitive << ( icmp_ln1494_12_fu_364_p2 );
    sensitive << ( trunc_ln1494_12_fu_360_p1 );

    SC_METHOD(thread_select_ln45_13_fu_388_p3);
    sensitive << ( icmp_ln1494_13_fu_382_p2 );
    sensitive << ( trunc_ln1494_13_fu_378_p1 );

    SC_METHOD(thread_select_ln45_14_fu_406_p3);
    sensitive << ( icmp_ln1494_14_fu_400_p2 );
    sensitive << ( trunc_ln1494_14_fu_396_p1 );

    SC_METHOD(thread_select_ln45_15_fu_424_p3);
    sensitive << ( icmp_ln1494_15_fu_418_p2 );
    sensitive << ( trunc_ln1494_15_fu_414_p1 );

    SC_METHOD(thread_select_ln45_1_fu_172_p3);
    sensitive << ( icmp_ln1494_1_fu_166_p2 );
    sensitive << ( trunc_ln1494_1_fu_162_p1 );

    SC_METHOD(thread_select_ln45_2_fu_190_p3);
    sensitive << ( icmp_ln1494_2_fu_184_p2 );
    sensitive << ( trunc_ln1494_2_fu_180_p1 );

    SC_METHOD(thread_select_ln45_3_fu_208_p3);
    sensitive << ( icmp_ln1494_3_fu_202_p2 );
    sensitive << ( trunc_ln1494_3_fu_198_p1 );

    SC_METHOD(thread_select_ln45_4_fu_226_p3);
    sensitive << ( icmp_ln1494_4_fu_220_p2 );
    sensitive << ( trunc_ln1494_4_fu_216_p1 );

    SC_METHOD(thread_select_ln45_5_fu_244_p3);
    sensitive << ( icmp_ln1494_5_fu_238_p2 );
    sensitive << ( trunc_ln1494_5_fu_234_p1 );

    SC_METHOD(thread_select_ln45_6_fu_262_p3);
    sensitive << ( icmp_ln1494_6_fu_256_p2 );
    sensitive << ( trunc_ln1494_6_fu_252_p1 );

    SC_METHOD(thread_select_ln45_7_fu_280_p3);
    sensitive << ( icmp_ln1494_7_fu_274_p2 );
    sensitive << ( trunc_ln1494_7_fu_270_p1 );

    SC_METHOD(thread_select_ln45_8_fu_298_p3);
    sensitive << ( icmp_ln1494_8_fu_292_p2 );
    sensitive << ( trunc_ln1494_8_fu_288_p1 );

    SC_METHOD(thread_select_ln45_9_fu_316_p3);
    sensitive << ( icmp_ln1494_9_fu_310_p2 );
    sensitive << ( trunc_ln1494_9_fu_306_p1 );

    SC_METHOD(thread_select_ln45_fu_154_p3);
    sensitive << ( icmp_ln1494_fu_148_p2 );
    sensitive << ( trunc_ln1494_fu_144_p1 );

    SC_METHOD(thread_trunc_ln1494_10_fu_324_p1);
    sensitive << ( data_10_V_read );

    SC_METHOD(thread_trunc_ln1494_11_fu_342_p1);
    sensitive << ( data_11_V_read );

    SC_METHOD(thread_trunc_ln1494_12_fu_360_p1);
    sensitive << ( data_12_V_read );

    SC_METHOD(thread_trunc_ln1494_13_fu_378_p1);
    sensitive << ( data_13_V_read );

    SC_METHOD(thread_trunc_ln1494_14_fu_396_p1);
    sensitive << ( data_14_V_read );

    SC_METHOD(thread_trunc_ln1494_15_fu_414_p1);
    sensitive << ( data_15_V_read );

    SC_METHOD(thread_trunc_ln1494_1_fu_162_p1);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_trunc_ln1494_2_fu_180_p1);
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_trunc_ln1494_3_fu_198_p1);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_trunc_ln1494_4_fu_216_p1);
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_trunc_ln1494_5_fu_234_p1);
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_trunc_ln1494_6_fu_252_p1);
    sensitive << ( data_6_V_read );

    SC_METHOD(thread_trunc_ln1494_7_fu_270_p1);
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_trunc_ln1494_8_fu_288_p1);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_trunc_ln1494_9_fu_306_p1);
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_trunc_ln1494_fu_144_p1);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "1";
    ap_return_0_preg = "0000000000000000000000000000000";
    ap_return_1_preg = "0000000000000000000000000000000";
    ap_return_2_preg = "0000000000000000000000000000000";
    ap_return_3_preg = "0000000000000000000000000000000";
    ap_return_4_preg = "0000000000000000000000000000000";
    ap_return_5_preg = "0000000000000000000000000000000";
    ap_return_6_preg = "0000000000000000000000000000000";
    ap_return_7_preg = "0000000000000000000000000000000";
    ap_return_8_preg = "0000000000000000000000000000000";
    ap_return_9_preg = "0000000000000000000000000000000";
    ap_return_10_preg = "0000000000000000000000000000000";
    ap_return_11_preg = "0000000000000000000000000000000";
    ap_return_12_preg = "0000000000000000000000000000000";
    ap_return_13_preg = "0000000000000000000000000000000";
    ap_return_14_preg = "0000000000000000000000000000000";
    ap_return_15_preg = "0000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_5_V_read, "(port)data_5_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, data_7_V_read, "(port)data_7_V_read");
    sc_trace(mVcdFile, data_8_V_read, "(port)data_8_V_read");
    sc_trace(mVcdFile, data_9_V_read, "(port)data_9_V_read");
    sc_trace(mVcdFile, data_10_V_read, "(port)data_10_V_read");
    sc_trace(mVcdFile, data_11_V_read, "(port)data_11_V_read");
    sc_trace(mVcdFile, data_12_V_read, "(port)data_12_V_read");
    sc_trace(mVcdFile, data_13_V_read, "(port)data_13_V_read");
    sc_trace(mVcdFile, data_14_V_read, "(port)data_14_V_read");
    sc_trace(mVcdFile, data_15_V_read, "(port)data_15_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, ap_return_7, "(port)ap_return_7");
    sc_trace(mVcdFile, ap_return_8, "(port)ap_return_8");
    sc_trace(mVcdFile, ap_return_9, "(port)ap_return_9");
    sc_trace(mVcdFile, ap_return_10, "(port)ap_return_10");
    sc_trace(mVcdFile, ap_return_11, "(port)ap_return_11");
    sc_trace(mVcdFile, ap_return_12, "(port)ap_return_12");
    sc_trace(mVcdFile, ap_return_13, "(port)ap_return_13");
    sc_trace(mVcdFile, ap_return_14, "(port)ap_return_14");
    sc_trace(mVcdFile, ap_return_15, "(port)ap_return_15");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, icmp_ln1494_fu_148_p2, "icmp_ln1494_fu_148_p2");
    sc_trace(mVcdFile, trunc_ln1494_fu_144_p1, "trunc_ln1494_fu_144_p1");
    sc_trace(mVcdFile, icmp_ln1494_1_fu_166_p2, "icmp_ln1494_1_fu_166_p2");
    sc_trace(mVcdFile, trunc_ln1494_1_fu_162_p1, "trunc_ln1494_1_fu_162_p1");
    sc_trace(mVcdFile, icmp_ln1494_2_fu_184_p2, "icmp_ln1494_2_fu_184_p2");
    sc_trace(mVcdFile, trunc_ln1494_2_fu_180_p1, "trunc_ln1494_2_fu_180_p1");
    sc_trace(mVcdFile, icmp_ln1494_3_fu_202_p2, "icmp_ln1494_3_fu_202_p2");
    sc_trace(mVcdFile, trunc_ln1494_3_fu_198_p1, "trunc_ln1494_3_fu_198_p1");
    sc_trace(mVcdFile, icmp_ln1494_4_fu_220_p2, "icmp_ln1494_4_fu_220_p2");
    sc_trace(mVcdFile, trunc_ln1494_4_fu_216_p1, "trunc_ln1494_4_fu_216_p1");
    sc_trace(mVcdFile, icmp_ln1494_5_fu_238_p2, "icmp_ln1494_5_fu_238_p2");
    sc_trace(mVcdFile, trunc_ln1494_5_fu_234_p1, "trunc_ln1494_5_fu_234_p1");
    sc_trace(mVcdFile, icmp_ln1494_6_fu_256_p2, "icmp_ln1494_6_fu_256_p2");
    sc_trace(mVcdFile, trunc_ln1494_6_fu_252_p1, "trunc_ln1494_6_fu_252_p1");
    sc_trace(mVcdFile, icmp_ln1494_7_fu_274_p2, "icmp_ln1494_7_fu_274_p2");
    sc_trace(mVcdFile, trunc_ln1494_7_fu_270_p1, "trunc_ln1494_7_fu_270_p1");
    sc_trace(mVcdFile, icmp_ln1494_8_fu_292_p2, "icmp_ln1494_8_fu_292_p2");
    sc_trace(mVcdFile, trunc_ln1494_8_fu_288_p1, "trunc_ln1494_8_fu_288_p1");
    sc_trace(mVcdFile, icmp_ln1494_9_fu_310_p2, "icmp_ln1494_9_fu_310_p2");
    sc_trace(mVcdFile, trunc_ln1494_9_fu_306_p1, "trunc_ln1494_9_fu_306_p1");
    sc_trace(mVcdFile, icmp_ln1494_10_fu_328_p2, "icmp_ln1494_10_fu_328_p2");
    sc_trace(mVcdFile, trunc_ln1494_10_fu_324_p1, "trunc_ln1494_10_fu_324_p1");
    sc_trace(mVcdFile, icmp_ln1494_11_fu_346_p2, "icmp_ln1494_11_fu_346_p2");
    sc_trace(mVcdFile, trunc_ln1494_11_fu_342_p1, "trunc_ln1494_11_fu_342_p1");
    sc_trace(mVcdFile, icmp_ln1494_12_fu_364_p2, "icmp_ln1494_12_fu_364_p2");
    sc_trace(mVcdFile, trunc_ln1494_12_fu_360_p1, "trunc_ln1494_12_fu_360_p1");
    sc_trace(mVcdFile, icmp_ln1494_13_fu_382_p2, "icmp_ln1494_13_fu_382_p2");
    sc_trace(mVcdFile, trunc_ln1494_13_fu_378_p1, "trunc_ln1494_13_fu_378_p1");
    sc_trace(mVcdFile, icmp_ln1494_14_fu_400_p2, "icmp_ln1494_14_fu_400_p2");
    sc_trace(mVcdFile, trunc_ln1494_14_fu_396_p1, "trunc_ln1494_14_fu_396_p1");
    sc_trace(mVcdFile, icmp_ln1494_15_fu_418_p2, "icmp_ln1494_15_fu_418_p2");
    sc_trace(mVcdFile, trunc_ln1494_15_fu_414_p1, "trunc_ln1494_15_fu_414_p1");
    sc_trace(mVcdFile, select_ln45_fu_154_p3, "select_ln45_fu_154_p3");
    sc_trace(mVcdFile, select_ln45_1_fu_172_p3, "select_ln45_1_fu_172_p3");
    sc_trace(mVcdFile, select_ln45_2_fu_190_p3, "select_ln45_2_fu_190_p3");
    sc_trace(mVcdFile, select_ln45_3_fu_208_p3, "select_ln45_3_fu_208_p3");
    sc_trace(mVcdFile, select_ln45_4_fu_226_p3, "select_ln45_4_fu_226_p3");
    sc_trace(mVcdFile, select_ln45_5_fu_244_p3, "select_ln45_5_fu_244_p3");
    sc_trace(mVcdFile, select_ln45_6_fu_262_p3, "select_ln45_6_fu_262_p3");
    sc_trace(mVcdFile, select_ln45_7_fu_280_p3, "select_ln45_7_fu_280_p3");
    sc_trace(mVcdFile, select_ln45_8_fu_298_p3, "select_ln45_8_fu_298_p3");
    sc_trace(mVcdFile, select_ln45_9_fu_316_p3, "select_ln45_9_fu_316_p3");
    sc_trace(mVcdFile, select_ln45_10_fu_334_p3, "select_ln45_10_fu_334_p3");
    sc_trace(mVcdFile, select_ln45_11_fu_352_p3, "select_ln45_11_fu_352_p3");
    sc_trace(mVcdFile, select_ln45_12_fu_370_p3, "select_ln45_12_fu_370_p3");
    sc_trace(mVcdFile, select_ln45_13_fu_388_p3, "select_ln45_13_fu_388_p3");
    sc_trace(mVcdFile, select_ln45_14_fu_406_p3, "select_ln45_14_fu_406_p3");
    sc_trace(mVcdFile, select_ln45_15_fu_424_p3, "select_ln45_15_fu_424_p3");
    sc_trace(mVcdFile, ap_return_0_preg, "ap_return_0_preg");
    sc_trace(mVcdFile, ap_return_1_preg, "ap_return_1_preg");
    sc_trace(mVcdFile, ap_return_2_preg, "ap_return_2_preg");
    sc_trace(mVcdFile, ap_return_3_preg, "ap_return_3_preg");
    sc_trace(mVcdFile, ap_return_4_preg, "ap_return_4_preg");
    sc_trace(mVcdFile, ap_return_5_preg, "ap_return_5_preg");
    sc_trace(mVcdFile, ap_return_6_preg, "ap_return_6_preg");
    sc_trace(mVcdFile, ap_return_7_preg, "ap_return_7_preg");
    sc_trace(mVcdFile, ap_return_8_preg, "ap_return_8_preg");
    sc_trace(mVcdFile, ap_return_9_preg, "ap_return_9_preg");
    sc_trace(mVcdFile, ap_return_10_preg, "ap_return_10_preg");
    sc_trace(mVcdFile, ap_return_11_preg, "ap_return_11_preg");
    sc_trace(mVcdFile, ap_return_12_preg, "ap_return_12_preg");
    sc_trace(mVcdFile, ap_return_13_preg, "ap_return_13_preg");
    sc_trace(mVcdFile, ap_return_14_preg, "ap_return_14_preg");
    sc_trace(mVcdFile, ap_return_15_preg, "ap_return_15_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::~relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_0_preg = ap_const_lv31_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_0_preg = select_ln45_fu_154_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_10_preg = ap_const_lv31_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_10_preg = select_ln45_10_fu_334_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_11_preg = ap_const_lv31_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_11_preg = select_ln45_11_fu_352_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_12_preg = ap_const_lv31_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_12_preg = select_ln45_12_fu_370_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_13_preg = ap_const_lv31_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_13_preg = select_ln45_13_fu_388_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_14_preg = ap_const_lv31_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_14_preg = select_ln45_14_fu_406_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_15_preg = ap_const_lv31_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_15_preg = select_ln45_15_fu_424_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_1_preg = ap_const_lv31_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_1_preg = select_ln45_1_fu_172_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_2_preg = ap_const_lv31_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_2_preg = select_ln45_2_fu_190_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_3_preg = ap_const_lv31_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_3_preg = select_ln45_3_fu_208_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_4_preg = ap_const_lv31_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_4_preg = select_ln45_4_fu_226_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_5_preg = ap_const_lv31_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_5_preg = select_ln45_5_fu_244_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_6_preg = ap_const_lv31_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_6_preg = select_ln45_6_fu_262_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_7_preg = ap_const_lv31_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_7_preg = select_ln45_7_fu_280_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_8_preg = ap_const_lv31_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_8_preg = select_ln45_8_fu_298_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_9_preg = ap_const_lv31_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_9_preg = select_ln45_9_fu_316_p3.read();
        }
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_return_0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_0 = select_ln45_fu_154_p3.read();
    } else {
        ap_return_0 = ap_return_0_preg.read();
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_return_1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_1 = select_ln45_1_fu_172_p3.read();
    } else {
        ap_return_1 = ap_return_1_preg.read();
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_return_10() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_10 = select_ln45_10_fu_334_p3.read();
    } else {
        ap_return_10 = ap_return_10_preg.read();
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_return_11() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_11 = select_ln45_11_fu_352_p3.read();
    } else {
        ap_return_11 = ap_return_11_preg.read();
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_return_12() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_12 = select_ln45_12_fu_370_p3.read();
    } else {
        ap_return_12 = ap_return_12_preg.read();
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_return_13() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_13 = select_ln45_13_fu_388_p3.read();
    } else {
        ap_return_13 = ap_return_13_preg.read();
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_return_14() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_14 = select_ln45_14_fu_406_p3.read();
    } else {
        ap_return_14 = ap_return_14_preg.read();
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_return_15() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_15 = select_ln45_15_fu_424_p3.read();
    } else {
        ap_return_15 = ap_return_15_preg.read();
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_return_2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_2 = select_ln45_2_fu_190_p3.read();
    } else {
        ap_return_2 = ap_return_2_preg.read();
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_return_3() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_3 = select_ln45_3_fu_208_p3.read();
    } else {
        ap_return_3 = ap_return_3_preg.read();
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_return_4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_4 = select_ln45_4_fu_226_p3.read();
    } else {
        ap_return_4 = ap_return_4_preg.read();
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_return_5() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_5 = select_ln45_5_fu_244_p3.read();
    } else {
        ap_return_5 = ap_return_5_preg.read();
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_return_6() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_6 = select_ln45_6_fu_262_p3.read();
    } else {
        ap_return_6 = ap_return_6_preg.read();
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_return_7() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_7 = select_ln45_7_fu_280_p3.read();
    } else {
        ap_return_7 = ap_return_7_preg.read();
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_return_8() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_8 = select_ln45_8_fu_298_p3.read();
    } else {
        ap_return_8 = ap_return_8_preg.read();
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_return_9() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_9 = select_ln45_9_fu_316_p3.read();
    } else {
        ap_return_9 = ap_return_9_preg.read();
    }
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_icmp_ln1494_10_fu_328_p2() {
    icmp_ln1494_10_fu_328_p2 = (!data_10_V_read.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(data_10_V_read.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_icmp_ln1494_11_fu_346_p2() {
    icmp_ln1494_11_fu_346_p2 = (!data_11_V_read.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(data_11_V_read.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_icmp_ln1494_12_fu_364_p2() {
    icmp_ln1494_12_fu_364_p2 = (!data_12_V_read.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(data_12_V_read.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_icmp_ln1494_13_fu_382_p2() {
    icmp_ln1494_13_fu_382_p2 = (!data_13_V_read.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(data_13_V_read.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_icmp_ln1494_14_fu_400_p2() {
    icmp_ln1494_14_fu_400_p2 = (!data_14_V_read.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(data_14_V_read.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_icmp_ln1494_15_fu_418_p2() {
    icmp_ln1494_15_fu_418_p2 = (!data_15_V_read.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(data_15_V_read.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_icmp_ln1494_1_fu_166_p2() {
    icmp_ln1494_1_fu_166_p2 = (!data_1_V_read.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(data_1_V_read.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_icmp_ln1494_2_fu_184_p2() {
    icmp_ln1494_2_fu_184_p2 = (!data_2_V_read.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(data_2_V_read.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_icmp_ln1494_3_fu_202_p2() {
    icmp_ln1494_3_fu_202_p2 = (!data_3_V_read.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(data_3_V_read.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_icmp_ln1494_4_fu_220_p2() {
    icmp_ln1494_4_fu_220_p2 = (!data_4_V_read.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(data_4_V_read.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_icmp_ln1494_5_fu_238_p2() {
    icmp_ln1494_5_fu_238_p2 = (!data_5_V_read.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(data_5_V_read.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_icmp_ln1494_6_fu_256_p2() {
    icmp_ln1494_6_fu_256_p2 = (!data_6_V_read.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(data_6_V_read.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_icmp_ln1494_7_fu_274_p2() {
    icmp_ln1494_7_fu_274_p2 = (!data_7_V_read.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(data_7_V_read.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_icmp_ln1494_8_fu_292_p2() {
    icmp_ln1494_8_fu_292_p2 = (!data_8_V_read.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(data_8_V_read.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_icmp_ln1494_9_fu_310_p2() {
    icmp_ln1494_9_fu_310_p2 = (!data_9_V_read.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(data_9_V_read.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_icmp_ln1494_fu_148_p2() {
    icmp_ln1494_fu_148_p2 = (!data_0_V_read.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(data_0_V_read.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_select_ln45_10_fu_334_p3() {
    select_ln45_10_fu_334_p3 = (!icmp_ln1494_10_fu_328_p2.read()[0].is_01())? sc_lv<31>(): ((icmp_ln1494_10_fu_328_p2.read()[0].to_bool())? trunc_ln1494_10_fu_324_p1.read(): ap_const_lv31_0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_select_ln45_11_fu_352_p3() {
    select_ln45_11_fu_352_p3 = (!icmp_ln1494_11_fu_346_p2.read()[0].is_01())? sc_lv<31>(): ((icmp_ln1494_11_fu_346_p2.read()[0].to_bool())? trunc_ln1494_11_fu_342_p1.read(): ap_const_lv31_0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_select_ln45_12_fu_370_p3() {
    select_ln45_12_fu_370_p3 = (!icmp_ln1494_12_fu_364_p2.read()[0].is_01())? sc_lv<31>(): ((icmp_ln1494_12_fu_364_p2.read()[0].to_bool())? trunc_ln1494_12_fu_360_p1.read(): ap_const_lv31_0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_select_ln45_13_fu_388_p3() {
    select_ln45_13_fu_388_p3 = (!icmp_ln1494_13_fu_382_p2.read()[0].is_01())? sc_lv<31>(): ((icmp_ln1494_13_fu_382_p2.read()[0].to_bool())? trunc_ln1494_13_fu_378_p1.read(): ap_const_lv31_0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_select_ln45_14_fu_406_p3() {
    select_ln45_14_fu_406_p3 = (!icmp_ln1494_14_fu_400_p2.read()[0].is_01())? sc_lv<31>(): ((icmp_ln1494_14_fu_400_p2.read()[0].to_bool())? trunc_ln1494_14_fu_396_p1.read(): ap_const_lv31_0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_select_ln45_15_fu_424_p3() {
    select_ln45_15_fu_424_p3 = (!icmp_ln1494_15_fu_418_p2.read()[0].is_01())? sc_lv<31>(): ((icmp_ln1494_15_fu_418_p2.read()[0].to_bool())? trunc_ln1494_15_fu_414_p1.read(): ap_const_lv31_0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_select_ln45_1_fu_172_p3() {
    select_ln45_1_fu_172_p3 = (!icmp_ln1494_1_fu_166_p2.read()[0].is_01())? sc_lv<31>(): ((icmp_ln1494_1_fu_166_p2.read()[0].to_bool())? trunc_ln1494_1_fu_162_p1.read(): ap_const_lv31_0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_select_ln45_2_fu_190_p3() {
    select_ln45_2_fu_190_p3 = (!icmp_ln1494_2_fu_184_p2.read()[0].is_01())? sc_lv<31>(): ((icmp_ln1494_2_fu_184_p2.read()[0].to_bool())? trunc_ln1494_2_fu_180_p1.read(): ap_const_lv31_0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_select_ln45_3_fu_208_p3() {
    select_ln45_3_fu_208_p3 = (!icmp_ln1494_3_fu_202_p2.read()[0].is_01())? sc_lv<31>(): ((icmp_ln1494_3_fu_202_p2.read()[0].to_bool())? trunc_ln1494_3_fu_198_p1.read(): ap_const_lv31_0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_select_ln45_4_fu_226_p3() {
    select_ln45_4_fu_226_p3 = (!icmp_ln1494_4_fu_220_p2.read()[0].is_01())? sc_lv<31>(): ((icmp_ln1494_4_fu_220_p2.read()[0].to_bool())? trunc_ln1494_4_fu_216_p1.read(): ap_const_lv31_0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_select_ln45_5_fu_244_p3() {
    select_ln45_5_fu_244_p3 = (!icmp_ln1494_5_fu_238_p2.read()[0].is_01())? sc_lv<31>(): ((icmp_ln1494_5_fu_238_p2.read()[0].to_bool())? trunc_ln1494_5_fu_234_p1.read(): ap_const_lv31_0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_select_ln45_6_fu_262_p3() {
    select_ln45_6_fu_262_p3 = (!icmp_ln1494_6_fu_256_p2.read()[0].is_01())? sc_lv<31>(): ((icmp_ln1494_6_fu_256_p2.read()[0].to_bool())? trunc_ln1494_6_fu_252_p1.read(): ap_const_lv31_0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_select_ln45_7_fu_280_p3() {
    select_ln45_7_fu_280_p3 = (!icmp_ln1494_7_fu_274_p2.read()[0].is_01())? sc_lv<31>(): ((icmp_ln1494_7_fu_274_p2.read()[0].to_bool())? trunc_ln1494_7_fu_270_p1.read(): ap_const_lv31_0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_select_ln45_8_fu_298_p3() {
    select_ln45_8_fu_298_p3 = (!icmp_ln1494_8_fu_292_p2.read()[0].is_01())? sc_lv<31>(): ((icmp_ln1494_8_fu_292_p2.read()[0].to_bool())? trunc_ln1494_8_fu_288_p1.read(): ap_const_lv31_0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_select_ln45_9_fu_316_p3() {
    select_ln45_9_fu_316_p3 = (!icmp_ln1494_9_fu_310_p2.read()[0].is_01())? sc_lv<31>(): ((icmp_ln1494_9_fu_310_p2.read()[0].to_bool())? trunc_ln1494_9_fu_306_p1.read(): ap_const_lv31_0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_select_ln45_fu_154_p3() {
    select_ln45_fu_154_p3 = (!icmp_ln1494_fu_148_p2.read()[0].is_01())? sc_lv<31>(): ((icmp_ln1494_fu_148_p2.read()[0].to_bool())? trunc_ln1494_fu_144_p1.read(): ap_const_lv31_0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_trunc_ln1494_10_fu_324_p1() {
    trunc_ln1494_10_fu_324_p1 = data_10_V_read.read().range(31-1, 0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_trunc_ln1494_11_fu_342_p1() {
    trunc_ln1494_11_fu_342_p1 = data_11_V_read.read().range(31-1, 0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_trunc_ln1494_12_fu_360_p1() {
    trunc_ln1494_12_fu_360_p1 = data_12_V_read.read().range(31-1, 0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_trunc_ln1494_13_fu_378_p1() {
    trunc_ln1494_13_fu_378_p1 = data_13_V_read.read().range(31-1, 0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_trunc_ln1494_14_fu_396_p1() {
    trunc_ln1494_14_fu_396_p1 = data_14_V_read.read().range(31-1, 0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_trunc_ln1494_15_fu_414_p1() {
    trunc_ln1494_15_fu_414_p1 = data_15_V_read.read().range(31-1, 0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_trunc_ln1494_1_fu_162_p1() {
    trunc_ln1494_1_fu_162_p1 = data_1_V_read.read().range(31-1, 0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_trunc_ln1494_2_fu_180_p1() {
    trunc_ln1494_2_fu_180_p1 = data_2_V_read.read().range(31-1, 0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_trunc_ln1494_3_fu_198_p1() {
    trunc_ln1494_3_fu_198_p1 = data_3_V_read.read().range(31-1, 0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_trunc_ln1494_4_fu_216_p1() {
    trunc_ln1494_4_fu_216_p1 = data_4_V_read.read().range(31-1, 0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_trunc_ln1494_5_fu_234_p1() {
    trunc_ln1494_5_fu_234_p1 = data_5_V_read.read().range(31-1, 0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_trunc_ln1494_6_fu_252_p1() {
    trunc_ln1494_6_fu_252_p1 = data_6_V_read.read().range(31-1, 0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_trunc_ln1494_7_fu_270_p1() {
    trunc_ln1494_7_fu_270_p1 = data_7_V_read.read().range(31-1, 0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_trunc_ln1494_8_fu_288_p1() {
    trunc_ln1494_8_fu_288_p1 = data_8_V_read.read().range(31-1, 0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_trunc_ln1494_9_fu_306_p1() {
    trunc_ln1494_9_fu_306_p1 = data_9_V_read.read().range(31-1, 0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_trunc_ln1494_fu_144_p1() {
    trunc_ln1494_fu_144_p1 = data_0_V_read.read().range(31-1, 0);
}

void relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config7_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

