// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_32_16_4_0_0_ap_fixed_32_16_5_3_0_config8_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        ap_return_0,
        ap_return_1,
        ap_return_2
);


output   ap_ready;
input  [31:0] data_0_val;
input  [31:0] data_1_val;
input  [31:0] data_2_val;
input  [31:0] data_3_val;
input  [31:0] data_4_val;
input  [31:0] data_5_val;
input  [31:0] data_6_val;
input  [31:0] data_7_val;
input  [31:0] data_8_val;
input  [31:0] data_9_val;
input  [31:0] data_10_val;
input  [31:0] data_11_val;
input  [31:0] data_12_val;
input  [31:0] data_13_val;
input  [31:0] data_14_val;
input  [31:0] data_15_val;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;

wire  signed [31:0] mul_ln73_1739_fu_276_p0;
wire  signed [47:0] sext_ln70_395_fu_10231_p1;
wire   [15:0] mul_ln73_1739_fu_276_p1;
wire  signed [31:0] mul_ln73_1740_fu_277_p0;
wire  signed [46:0] sext_ln70_397_fu_10276_p1;
wire  signed [14:0] mul_ln73_1740_fu_277_p1;
wire   [15:0] mul_ln73_1744_fu_278_p1;
wire  signed [31:0] mul_ln73_1727_fu_279_p0;
wire  signed [47:0] sext_ln70_386_fu_10005_p1;
wire  signed [15:0] mul_ln73_1727_fu_279_p1;
wire   [14:0] mul_ln73_1749_fu_280_p1;
wire  signed [31:0] mul_ln73_1717_fu_281_p0;
wire  signed [47:0] sext_ln70_381_fu_9829_p1;
wire   [15:0] mul_ln73_1717_fu_281_p1;
wire  signed [15:0] mul_ln73_1747_fu_282_p1;
wire  signed [31:0] mul_ln73_1737_fu_283_p0;
wire   [15:0] mul_ln73_1737_fu_283_p1;
wire  signed [31:0] mul_ln73_1731_fu_284_p0;
wire  signed [46:0] sext_ln70_388_fu_10050_p1;
wire  signed [14:0] mul_ln73_1731_fu_284_p1;
wire  signed [31:0] mul_ln73_1708_fu_285_p0;
wire  signed [46:0] sext_ln70_375_fu_9683_p1;
wire  signed [14:0] mul_ln73_1708_fu_285_p1;
wire  signed [31:0] mul_ln73_1732_fu_286_p0;
wire  signed [47:0] sext_ln70_390_fu_10103_p1;
wire   [15:0] mul_ln73_1732_fu_286_p1;
wire   [13:0] mul_ln73_1738_fu_287_p1;
wire  signed [31:0] mul_ln73_1715_fu_288_p0;
wire  signed [15:0] mul_ln73_1715_fu_288_p1;
wire  signed [31:0] mul_ln73_1724_fu_289_p0;
wire  signed [45:0] sext_ln70_385_fu_9957_p1;
wire  signed [13:0] mul_ln73_1724_fu_289_p1;
wire   [12:0] mul_ln73_1751_fu_290_p1;
wire  signed [15:0] mul_ln73_1720_fu_291_p1;
wire  signed [31:0] mul_ln73_1723_fu_292_p0;
wire   [13:0] mul_ln73_1723_fu_292_p1;
wire  signed [14:0] mul_ln73_1725_fu_293_p1;
wire   [13:0] mul_ln73_1743_fu_294_p1;
wire  signed [31:0] mul_ln73_1728_fu_295_p0;
wire   [15:0] mul_ln73_1728_fu_295_p1;
wire   [14:0] mul_ln73_1745_fu_296_p1;
wire   [13:0] mul_ln73_1734_fu_297_p1;
wire  signed [15:0] mul_ln73_1711_fu_298_p1;
wire  signed [12:0] mul_ln73_1735_fu_299_p1;
wire  signed [31:0] mul_ln73_1712_fu_300_p0;
wire  signed [44:0] sext_ln70_380_fu_9785_p1;
wire   [12:0] mul_ln73_1712_fu_300_p1;
wire  signed [31:0] mul_ln73_1722_fu_301_p0;
wire  signed [43:0] sext_ln70_382_fu_9903_p1;
wire  signed [11:0] mul_ln73_1722_fu_301_p1;
wire  signed [31:0] mul_ln73_fu_302_p0;
wire  signed [14:0] mul_ln73_fu_302_p1;
wire   [11:0] mul_ln73_1746_fu_303_p1;
wire  signed [31:0] mul_ln73_1714_fu_304_p0;
wire  signed [12:0] mul_ln73_1714_fu_304_p1;
wire   [13:0] mul_ln73_1750_fu_305_p1;
wire   [11:0] mul_ln73_1726_fu_306_p1;
wire   [15:0] mul_ln73_1713_fu_307_p1;
wire  signed [15:0] mul_ln73_1707_fu_309_p1;
wire   [14:0] mul_ln73_1748_fu_310_p1;
wire  signed [31:0] mul_ln73_1719_fu_311_p0;
wire  signed [47:0] sext_ln42_839_fu_9866_p1;
wire  signed [15:0] mul_ln73_1719_fu_311_p1;
wire  signed [31:0] mul_ln73_1730_fu_312_p0;
wire  signed [14:0] mul_ln73_1730_fu_312_p1;
wire  signed [31:0] mul_ln73_1716_fu_313_p0;
wire   [15:0] mul_ln73_1716_fu_313_p1;
wire  signed [31:0] mul_ln42_fu_314_p0;
wire  signed [16:0] mul_ln42_fu_314_p1;
wire  signed [31:0] mul_ln73_1733_fu_315_p0;
wire  signed [15:0] mul_ln73_1733_fu_315_p1;
wire  signed [11:0] mul_ln73_1709_fu_316_p1;
wire  signed [31:0] mul_ln73_1741_fu_317_p0;
wire  signed [14:0] mul_ln73_1741_fu_317_p1;
wire   [14:0] mul_ln73_1710_fu_318_p1;
wire   [13:0] mul_ln73_1729_fu_319_p1;
wire  signed [31:0] mul_ln73_1721_fu_320_p0;
wire  signed [11:0] mul_ln73_1721_fu_320_p1;
wire  signed [11:0] mul_ln73_1742_fu_321_p1;
wire  signed [31:0] mul_ln73_1718_fu_322_p0;
wire   [15:0] mul_ln73_1718_fu_322_p1;
wire   [15:0] mul_ln73_1736_fu_323_p1;
wire  signed [31:0] sext_ln70_375_fu_9683_p0;
wire   [46:0] mul_ln73_fu_302_p2;
wire   [30:0] trunc_ln_fu_9689_p4;
wire   [47:0] mul_ln73_1707_fu_309_p2;
wire   [46:0] mul_ln73_1708_fu_285_p2;
wire   [30:0] trunc_ln42_s_fu_9713_p4;
wire   [43:0] mul_ln73_1709_fu_316_p2;
wire   [27:0] trunc_ln42_2_fu_9742_p4;
wire   [46:0] mul_ln73_1710_fu_318_p2;
wire   [30:0] trunc_ln42_3_fu_9756_p4;
wire   [47:0] mul_ln73_1711_fu_298_p2;
wire  signed [31:0] sext_ln70_380_fu_9785_p0;
wire   [44:0] mul_ln73_1712_fu_300_p2;
wire   [28:0] trunc_ln42_4_fu_9791_p4;
wire   [47:0] mul_ln73_1713_fu_307_p2;
wire   [44:0] mul_ln73_1714_fu_304_p2;
wire   [28:0] trunc_ln42_6_fu_9815_p4;
wire   [47:0] mul_ln73_1715_fu_288_p2;
wire   [47:0] mul_ln73_1716_fu_313_p2;
wire   [47:0] mul_ln73_1717_fu_281_p2;
wire   [47:0] mul_ln73_1718_fu_322_p2;
wire   [47:0] mul_ln42_fu_314_p2;
wire   [47:0] mul_ln73_1719_fu_311_p2;
wire  signed [31:0] sext_ln70_382_fu_9903_p0;
wire   [47:0] mul_ln73_1720_fu_291_p2;
wire   [43:0] mul_ln73_1721_fu_320_p2;
wire   [27:0] trunc_ln42_15_fu_9924_p4;
wire   [43:0] mul_ln73_1722_fu_301_p2;
wire   [27:0] trunc_ln42_16_fu_9938_p4;
wire  signed [31:0] sext_ln70_385_fu_9957_p0;
wire   [45:0] mul_ln73_1723_fu_292_p2;
wire   [29:0] trunc_ln42_17_fu_9963_p4;
wire   [45:0] mul_ln73_1724_fu_289_p2;
wire   [29:0] trunc_ln42_18_fu_9977_p4;
wire   [46:0] mul_ln73_1725_fu_293_p2;
wire   [30:0] trunc_ln42_19_fu_9991_p4;
wire  signed [31:0] sext_ln70_386_fu_10005_p0;
wire   [43:0] mul_ln73_1726_fu_306_p2;
wire   [27:0] trunc_ln42_20_fu_10016_p4;
wire   [47:0] mul_ln73_1727_fu_279_p2;
wire   [47:0] mul_ln73_1728_fu_295_p2;
wire  signed [31:0] sext_ln70_388_fu_10050_p0;
wire   [45:0] mul_ln73_1729_fu_319_p2;
wire   [29:0] trunc_ln42_23_fu_10061_p4;
wire   [46:0] mul_ln73_1730_fu_312_p2;
wire   [30:0] trunc_ln42_24_fu_10075_p4;
wire   [46:0] mul_ln73_1731_fu_284_p2;
wire   [30:0] trunc_ln42_25_fu_10089_p4;
wire  signed [31:0] sext_ln70_390_fu_10103_p0;
wire  signed [31:0] shl_ln_fu_10109_p1;
wire   [42:0] shl_ln_fu_10109_p3;
wire  signed [31:0] shl_ln73_s_fu_10121_p1;
wire   [34:0] shl_ln73_s_fu_10121_p3;
wire  signed [43:0] sext_ln73_53_fu_10129_p1;
wire  signed [43:0] sext_ln73_fu_10117_p1;
wire   [43:0] sub_ln73_fu_10133_p2;
wire   [27:0] trunc_ln42_26_fu_10139_p4;
wire   [47:0] mul_ln73_1732_fu_286_p2;
wire   [47:0] mul_ln73_1733_fu_315_p2;
wire   [45:0] mul_ln73_1734_fu_297_p2;
wire   [29:0] trunc_ln42_29_fu_10188_p4;
wire   [44:0] mul_ln73_1735_fu_299_p2;
wire   [28:0] trunc_ln42_30_fu_10202_p4;
wire   [47:0] mul_ln73_1736_fu_323_p2;
wire  signed [31:0] sext_ln70_395_fu_10231_p0;
wire   [47:0] mul_ln73_1737_fu_283_p2;
wire   [45:0] mul_ln73_1738_fu_287_p2;
wire   [29:0] trunc_ln42_33_fu_10247_p4;
wire   [47:0] mul_ln73_1739_fu_276_p2;
wire  signed [31:0] sext_ln70_397_fu_10276_p0;
wire   [46:0] mul_ln73_1740_fu_277_p2;
wire   [30:0] trunc_ln42_35_fu_10282_p4;
wire   [46:0] mul_ln73_1741_fu_317_p2;
wire   [30:0] trunc_ln42_36_fu_10296_p4;
wire   [43:0] mul_ln73_1742_fu_321_p2;
wire   [27:0] trunc_ln42_37_fu_10310_p4;
wire   [45:0] mul_ln73_1743_fu_294_p2;
wire   [29:0] trunc_ln42_38_fu_10339_p4;
wire   [47:0] mul_ln73_1744_fu_278_p2;
wire   [46:0] mul_ln73_1745_fu_296_p2;
wire   [30:0] trunc_ln42_40_fu_10363_p4;
wire   [43:0] mul_ln73_1746_fu_303_p2;
wire   [27:0] trunc_ln42_41_fu_10392_p4;
wire   [47:0] mul_ln73_1747_fu_282_p2;
wire   [46:0] mul_ln73_1748_fu_310_p2;
wire   [30:0] trunc_ln42_43_fu_10416_p4;
wire   [46:0] mul_ln73_1749_fu_280_p2;
wire   [30:0] trunc_ln42_44_fu_10445_p4;
wire   [45:0] mul_ln73_1750_fu_305_p2;
wire   [29:0] trunc_ln42_45_fu_10459_p4;
wire   [44:0] mul_ln73_1751_fu_290_p2;
wire   [28:0] trunc_ln42_46_fu_10473_p4;
wire  signed [31:0] sext_ln42_fu_9699_p1;
wire  signed [31:0] sext_ln42_835_fu_9752_p1;
wire  signed [31:0] sext_ln42_837_fu_9801_p1;
wire   [31:0] trunc_ln42_9_fu_9836_p4;
wire   [31:0] add_ln58_1824_fu_10493_p2;
wire   [31:0] add_ln58_fu_10487_p2;
wire   [31:0] trunc_ln42_11_fu_9873_p4;
wire   [31:0] trunc_ln42_14_fu_9914_p4;
wire  signed [30:0] sext_ln73_52_fu_9973_p1;
wire  signed [30:0] sext_ln73_54_fu_10026_p1;
wire   [30:0] add_ln58_1827_fu_10511_p2;
wire  signed [31:0] sext_ln58_360_fu_10517_p1;
wire   [31:0] add_ln58_1826_fu_10505_p2;
wire   [31:0] add_ln58_1828_fu_10521_p2;
wire   [31:0] add_ln58_1825_fu_10499_p2;
wire  signed [30:0] sext_ln73_55_fu_10071_p1;
wire  signed [30:0] sext_ln73_56_fu_10149_p1;
wire   [30:0] add_ln58_1830_fu_10533_p2;
wire  signed [31:0] sext_ln42_846_fu_10198_p1;
wire   [31:0] trunc_ln42_32_fu_10237_p4;
wire   [31:0] add_ln58_1831_fu_10543_p2;
wire  signed [31:0] sext_ln58_361_fu_10539_p1;
wire  signed [31:0] sext_ln42_847_fu_10292_p1;
wire  signed [31:0] sext_ln42_850_fu_10349_p1;
wire  signed [31:0] sext_ln42_854_fu_10455_p1;
wire   [31:0] add_ln58_1834_fu_10561_p2;
wire  signed [31:0] sext_ln42_852_fu_10402_p1;
wire   [31:0] add_ln58_1835_fu_10567_p2;
wire   [31:0] add_ln58_1833_fu_10555_p2;
wire   [31:0] add_ln58_1836_fu_10573_p2;
wire   [31:0] add_ln58_1832_fu_10549_p2;
wire   [31:0] add_ln58_1837_fu_10579_p2;
wire   [31:0] add_ln58_1829_fu_10527_p2;
wire   [31:0] trunc_ln42_1_fu_9703_p4;
wire  signed [31:0] sext_ln42_836_fu_9766_p1;
wire   [31:0] trunc_ln42_7_fu_9805_p4;
wire   [31:0] trunc_ln42_8_fu_9846_p4;
wire   [31:0] add_ln58_1840_fu_10597_p2;
wire   [31:0] add_ln58_1839_fu_10591_p2;
wire   [31:0] trunc_ln42_12_fu_9883_p4;
wire  signed [31:0] sext_ln42_840_fu_9934_p1;
wire  signed [31:0] sext_ln42_842_fu_9987_p1;
wire   [31:0] trunc_ln42_21_fu_10030_p4;
wire   [31:0] add_ln58_1843_fu_10615_p2;
wire   [31:0] add_ln58_1842_fu_10609_p2;
wire   [31:0] add_ln58_1844_fu_10621_p2;
wire   [31:0] add_ln58_1841_fu_10603_p2;
wire  signed [31:0] sext_ln42_844_fu_10085_p1;
wire   [31:0] trunc_ln42_27_fu_10153_p4;
wire  signed [30:0] sext_ln73_57_fu_10212_p1;
wire  signed [30:0] sext_ln73_58_fu_10257_p1;
wire   [30:0] add_ln58_1847_fu_10639_p2;
wire  signed [31:0] sext_ln58_362_fu_10645_p1;
wire   [31:0] add_ln58_1846_fu_10633_p2;
wire  signed [31:0] sext_ln42_848_fu_10306_p1;
wire   [31:0] trunc_ln42_39_fu_10353_p4;
wire  signed [30:0] sext_ln73_59_fu_10469_p1;
wire   [30:0] add_ln58_1850_fu_10661_p2;
wire  signed [31:0] sext_ln58_363_fu_10667_p1;
wire   [31:0] trunc_ln42_42_fu_10406_p4;
wire   [31:0] add_ln58_1851_fu_10671_p2;
wire   [31:0] add_ln58_1849_fu_10655_p2;
wire   [31:0] add_ln58_1852_fu_10677_p2;
wire   [31:0] add_ln58_1848_fu_10649_p2;
wire   [31:0] add_ln58_1853_fu_10683_p2;
wire   [31:0] add_ln58_1845_fu_10627_p2;
wire  signed [31:0] sext_ln42_834_fu_9723_p1;
wire   [31:0] trunc_ln42_5_fu_9770_p4;
wire  signed [31:0] sext_ln42_838_fu_9825_p1;
wire   [31:0] trunc_ln42_10_fu_9856_p4;
wire   [31:0] add_ln58_1856_fu_10701_p2;
wire   [31:0] add_ln58_1855_fu_10695_p2;
wire   [31:0] trunc_ln42_13_fu_9893_p4;
wire  signed [31:0] sext_ln42_841_fu_9948_p1;
wire  signed [31:0] sext_ln42_843_fu_10001_p1;
wire   [31:0] trunc_ln42_22_fu_10040_p4;
wire   [31:0] add_ln58_1859_fu_10719_p2;
wire   [31:0] add_ln58_1858_fu_10713_p2;
wire   [31:0] add_ln58_1860_fu_10725_p2;
wire   [31:0] add_ln58_1857_fu_10707_p2;
wire  signed [31:0] sext_ln42_845_fu_10099_p1;
wire   [31:0] trunc_ln42_28_fu_10163_p4;
wire   [31:0] trunc_ln42_31_fu_10216_p4;
wire   [31:0] trunc_ln42_34_fu_10261_p4;
wire   [31:0] add_ln58_1863_fu_10743_p2;
wire   [31:0] add_ln58_1862_fu_10737_p2;
wire  signed [31:0] sext_ln42_849_fu_10320_p1;
wire  signed [31:0] sext_ln42_851_fu_10373_p1;
wire  signed [29:0] sext_ln58_fu_10483_p1;
wire   [29:0] add_ln58_1866_fu_10761_p2;
wire  signed [31:0] sext_ln58_364_fu_10767_p1;
wire  signed [31:0] sext_ln42_853_fu_10426_p1;
wire   [31:0] add_ln58_1867_fu_10771_p2;
wire   [31:0] add_ln58_1865_fu_10755_p2;
wire   [31:0] add_ln58_1868_fu_10777_p2;
wire   [31:0] add_ln58_1864_fu_10749_p2;
wire   [31:0] add_ln58_1869_fu_10783_p2;
wire   [31:0] add_ln58_1861_fu_10731_p2;
wire   [31:0] add_ln58_1838_fu_10585_p2;
wire   [31:0] add_ln58_1854_fu_10689_p2;
wire   [31:0] add_ln58_1870_fu_10789_p2;

myproject_mul_32s_16ns_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16ns_48_1_1_U2409(
    .din0(mul_ln73_1739_fu_276_p0),
    .din1(mul_ln73_1739_fu_276_p1),
    .dout(mul_ln73_1739_fu_276_p2)
);

myproject_mul_32s_15s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 47 ))
mul_32s_15s_47_1_1_U2410(
    .din0(mul_ln73_1740_fu_277_p0),
    .din1(mul_ln73_1740_fu_277_p1),
    .dout(mul_ln73_1740_fu_277_p2)
);

myproject_mul_32s_16ns_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16ns_48_1_1_U2411(
    .din0(data_13_val),
    .din1(mul_ln73_1744_fu_278_p1),
    .dout(mul_ln73_1744_fu_278_p2)
);

myproject_mul_32s_16s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16s_48_1_1_U2412(
    .din0(mul_ln73_1727_fu_279_p0),
    .din1(mul_ln73_1727_fu_279_p1),
    .dout(mul_ln73_1727_fu_279_p2)
);

myproject_mul_32s_15ns_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 47 ))
mul_32s_15ns_47_1_1_U2413(
    .din0(data_15_val),
    .din1(mul_ln73_1749_fu_280_p1),
    .dout(mul_ln73_1749_fu_280_p2)
);

myproject_mul_32s_16ns_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16ns_48_1_1_U2414(
    .din0(mul_ln73_1717_fu_281_p0),
    .din1(mul_ln73_1717_fu_281_p1),
    .dout(mul_ln73_1717_fu_281_p2)
);

myproject_mul_32s_16s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16s_48_1_1_U2415(
    .din0(data_14_val),
    .din1(mul_ln73_1747_fu_282_p1),
    .dout(mul_ln73_1747_fu_282_p2)
);

myproject_mul_32s_16ns_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16ns_48_1_1_U2416(
    .din0(mul_ln73_1737_fu_283_p0),
    .din1(mul_ln73_1737_fu_283_p1),
    .dout(mul_ln73_1737_fu_283_p2)
);

myproject_mul_32s_15s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 47 ))
mul_32s_15s_47_1_1_U2417(
    .din0(mul_ln73_1731_fu_284_p0),
    .din1(mul_ln73_1731_fu_284_p1),
    .dout(mul_ln73_1731_fu_284_p2)
);

myproject_mul_32s_15s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 47 ))
mul_32s_15s_47_1_1_U2418(
    .din0(mul_ln73_1708_fu_285_p0),
    .din1(mul_ln73_1708_fu_285_p1),
    .dout(mul_ln73_1708_fu_285_p2)
);

myproject_mul_32s_16ns_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16ns_48_1_1_U2419(
    .din0(mul_ln73_1732_fu_286_p0),
    .din1(mul_ln73_1732_fu_286_p1),
    .dout(mul_ln73_1732_fu_286_p2)
);

myproject_mul_32s_14ns_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 46 ))
mul_32s_14ns_46_1_1_U2420(
    .din0(data_11_val),
    .din1(mul_ln73_1738_fu_287_p1),
    .dout(mul_ln73_1738_fu_287_p2)
);

myproject_mul_32s_16s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16s_48_1_1_U2421(
    .din0(mul_ln73_1715_fu_288_p0),
    .din1(mul_ln73_1715_fu_288_p1),
    .dout(mul_ln73_1715_fu_288_p2)
);

myproject_mul_32s_14s_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 46 ))
mul_32s_14s_46_1_1_U2422(
    .din0(mul_ln73_1724_fu_289_p0),
    .din1(mul_ln73_1724_fu_289_p1),
    .dout(mul_ln73_1724_fu_289_p2)
);

myproject_mul_32s_13ns_45_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 45 ))
mul_32s_13ns_45_1_1_U2423(
    .din0(data_15_val),
    .din1(mul_ln73_1751_fu_290_p1),
    .dout(mul_ln73_1751_fu_290_p2)
);

myproject_mul_32s_16s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16s_48_1_1_U2424(
    .din0(data_5_val),
    .din1(mul_ln73_1720_fu_291_p1),
    .dout(mul_ln73_1720_fu_291_p2)
);

myproject_mul_32s_14ns_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 46 ))
mul_32s_14ns_46_1_1_U2425(
    .din0(mul_ln73_1723_fu_292_p0),
    .din1(mul_ln73_1723_fu_292_p1),
    .dout(mul_ln73_1723_fu_292_p2)
);

myproject_mul_32s_15s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 47 ))
mul_32s_15s_47_1_1_U2426(
    .din0(data_6_val),
    .din1(mul_ln73_1725_fu_293_p1),
    .dout(mul_ln73_1725_fu_293_p2)
);

myproject_mul_32s_14ns_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 46 ))
mul_32s_14ns_46_1_1_U2427(
    .din0(data_13_val),
    .din1(mul_ln73_1743_fu_294_p1),
    .dout(mul_ln73_1743_fu_294_p2)
);

myproject_mul_32s_16ns_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16ns_48_1_1_U2428(
    .din0(mul_ln73_1728_fu_295_p0),
    .din1(mul_ln73_1728_fu_295_p1),
    .dout(mul_ln73_1728_fu_295_p2)
);

myproject_mul_32s_15ns_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 47 ))
mul_32s_15ns_47_1_1_U2429(
    .din0(data_13_val),
    .din1(mul_ln73_1745_fu_296_p1),
    .dout(mul_ln73_1745_fu_296_p2)
);

myproject_mul_32s_14ns_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 46 ))
mul_32s_14ns_46_1_1_U2430(
    .din0(data_10_val),
    .din1(mul_ln73_1734_fu_297_p1),
    .dout(mul_ln73_1734_fu_297_p2)
);

myproject_mul_32s_16s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16s_48_1_1_U2431(
    .din0(data_1_val),
    .din1(mul_ln73_1711_fu_298_p1),
    .dout(mul_ln73_1711_fu_298_p2)
);

myproject_mul_32s_13s_45_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 45 ))
mul_32s_13s_45_1_1_U2432(
    .din0(data_10_val),
    .din1(mul_ln73_1735_fu_299_p1),
    .dout(mul_ln73_1735_fu_299_p2)
);

myproject_mul_32s_13ns_45_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 45 ))
mul_32s_13ns_45_1_1_U2433(
    .din0(mul_ln73_1712_fu_300_p0),
    .din1(mul_ln73_1712_fu_300_p1),
    .dout(mul_ln73_1712_fu_300_p2)
);

myproject_mul_32s_12s_44_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 44 ))
mul_32s_12s_44_1_1_U2434(
    .din0(mul_ln73_1722_fu_301_p0),
    .din1(mul_ln73_1722_fu_301_p1),
    .dout(mul_ln73_1722_fu_301_p2)
);

myproject_mul_32s_15s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 47 ))
mul_32s_15s_47_1_1_U2435(
    .din0(mul_ln73_fu_302_p0),
    .din1(mul_ln73_fu_302_p1),
    .dout(mul_ln73_fu_302_p2)
);

myproject_mul_32s_12ns_44_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 44 ))
mul_32s_12ns_44_1_1_U2436(
    .din0(data_14_val),
    .din1(mul_ln73_1746_fu_303_p1),
    .dout(mul_ln73_1746_fu_303_p2)
);

myproject_mul_32s_13s_45_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 45 ))
mul_32s_13s_45_1_1_U2437(
    .din0(mul_ln73_1714_fu_304_p0),
    .din1(mul_ln73_1714_fu_304_p1),
    .dout(mul_ln73_1714_fu_304_p2)
);

myproject_mul_32s_14ns_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 46 ))
mul_32s_14ns_46_1_1_U2438(
    .din0(data_15_val),
    .din1(mul_ln73_1750_fu_305_p1),
    .dout(mul_ln73_1750_fu_305_p2)
);

myproject_mul_32s_12ns_44_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 44 ))
mul_32s_12ns_44_1_1_U2439(
    .din0(data_7_val),
    .din1(mul_ln73_1726_fu_306_p1),
    .dout(mul_ln73_1726_fu_306_p2)
);

myproject_mul_32s_16ns_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16ns_48_1_1_U2440(
    .din0(data_2_val),
    .din1(mul_ln73_1713_fu_307_p1),
    .dout(mul_ln73_1713_fu_307_p2)
);

myproject_mul_32s_16s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16s_48_1_1_U2441(
    .din0(data_0_val),
    .din1(mul_ln73_1707_fu_309_p1),
    .dout(mul_ln73_1707_fu_309_p2)
);

myproject_mul_32s_15ns_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 47 ))
mul_32s_15ns_47_1_1_U2442(
    .din0(data_14_val),
    .din1(mul_ln73_1748_fu_310_p1),
    .dout(mul_ln73_1748_fu_310_p2)
);

myproject_mul_32s_16s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16s_48_1_1_U2443(
    .din0(mul_ln73_1719_fu_311_p0),
    .din1(mul_ln73_1719_fu_311_p1),
    .dout(mul_ln73_1719_fu_311_p2)
);

myproject_mul_32s_15s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 47 ))
mul_32s_15s_47_1_1_U2444(
    .din0(mul_ln73_1730_fu_312_p0),
    .din1(mul_ln73_1730_fu_312_p1),
    .dout(mul_ln73_1730_fu_312_p2)
);

myproject_mul_32s_16ns_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16ns_48_1_1_U2445(
    .din0(mul_ln73_1716_fu_313_p0),
    .din1(mul_ln73_1716_fu_313_p1),
    .dout(mul_ln73_1716_fu_313_p2)
);

myproject_mul_32s_17s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 48 ))
mul_32s_17s_48_1_1_U2446(
    .din0(mul_ln42_fu_314_p0),
    .din1(mul_ln42_fu_314_p1),
    .dout(mul_ln42_fu_314_p2)
);

myproject_mul_32s_16s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16s_48_1_1_U2447(
    .din0(mul_ln73_1733_fu_315_p0),
    .din1(mul_ln73_1733_fu_315_p1),
    .dout(mul_ln73_1733_fu_315_p2)
);

myproject_mul_32s_12s_44_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 44 ))
mul_32s_12s_44_1_1_U2448(
    .din0(data_1_val),
    .din1(mul_ln73_1709_fu_316_p1),
    .dout(mul_ln73_1709_fu_316_p2)
);

myproject_mul_32s_15s_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 47 ))
mul_32s_15s_47_1_1_U2449(
    .din0(mul_ln73_1741_fu_317_p0),
    .din1(mul_ln73_1741_fu_317_p1),
    .dout(mul_ln73_1741_fu_317_p2)
);

myproject_mul_32s_15ns_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 47 ))
mul_32s_15ns_47_1_1_U2450(
    .din0(data_1_val),
    .din1(mul_ln73_1710_fu_318_p1),
    .dout(mul_ln73_1710_fu_318_p2)
);

myproject_mul_32s_14ns_46_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 46 ))
mul_32s_14ns_46_1_1_U2451(
    .din0(data_8_val),
    .din1(mul_ln73_1729_fu_319_p1),
    .dout(mul_ln73_1729_fu_319_p2)
);

myproject_mul_32s_12s_44_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 44 ))
mul_32s_12s_44_1_1_U2452(
    .din0(mul_ln73_1721_fu_320_p0),
    .din1(mul_ln73_1721_fu_320_p1),
    .dout(mul_ln73_1721_fu_320_p2)
);

myproject_mul_32s_12s_44_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 44 ))
mul_32s_12s_44_1_1_U2453(
    .din0(data_12_val),
    .din1(mul_ln73_1742_fu_321_p1),
    .dout(mul_ln73_1742_fu_321_p2)
);

myproject_mul_32s_16ns_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16ns_48_1_1_U2454(
    .din0(mul_ln73_1718_fu_322_p0),
    .din1(mul_ln73_1718_fu_322_p1),
    .dout(mul_ln73_1718_fu_322_p2)
);

myproject_mul_32s_16ns_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16ns_48_1_1_U2455(
    .din0(data_10_val),
    .din1(mul_ln73_1736_fu_323_p1),
    .dout(mul_ln73_1736_fu_323_p2)
);

assign add_ln58_1824_fu_10493_p2 = ($signed(sext_ln42_837_fu_9801_p1) + $signed(trunc_ln42_9_fu_9836_p4));

assign add_ln58_1825_fu_10499_p2 = (add_ln58_1824_fu_10493_p2 + add_ln58_fu_10487_p2);

assign add_ln58_1826_fu_10505_p2 = (trunc_ln42_11_fu_9873_p4 + trunc_ln42_14_fu_9914_p4);

assign add_ln58_1827_fu_10511_p2 = ($signed(sext_ln73_52_fu_9973_p1) + $signed(sext_ln73_54_fu_10026_p1));

assign add_ln58_1828_fu_10521_p2 = ($signed(sext_ln58_360_fu_10517_p1) + $signed(add_ln58_1826_fu_10505_p2));

assign add_ln58_1829_fu_10527_p2 = (add_ln58_1828_fu_10521_p2 + add_ln58_1825_fu_10499_p2);

assign add_ln58_1830_fu_10533_p2 = ($signed(sext_ln73_55_fu_10071_p1) + $signed(sext_ln73_56_fu_10149_p1));

assign add_ln58_1831_fu_10543_p2 = ($signed(sext_ln42_846_fu_10198_p1) + $signed(trunc_ln42_32_fu_10237_p4));

assign add_ln58_1832_fu_10549_p2 = ($signed(add_ln58_1831_fu_10543_p2) + $signed(sext_ln58_361_fu_10539_p1));

assign add_ln58_1833_fu_10555_p2 = ($signed(sext_ln42_847_fu_10292_p1) + $signed(sext_ln42_850_fu_10349_p1));

assign add_ln58_1834_fu_10561_p2 = ($signed(sext_ln42_854_fu_10455_p1) + $signed(32'd27418));

assign add_ln58_1835_fu_10567_p2 = ($signed(add_ln58_1834_fu_10561_p2) + $signed(sext_ln42_852_fu_10402_p1));

assign add_ln58_1836_fu_10573_p2 = (add_ln58_1835_fu_10567_p2 + add_ln58_1833_fu_10555_p2);

assign add_ln58_1837_fu_10579_p2 = (add_ln58_1836_fu_10573_p2 + add_ln58_1832_fu_10549_p2);

assign add_ln58_1838_fu_10585_p2 = (add_ln58_1837_fu_10579_p2 + add_ln58_1829_fu_10527_p2);

assign add_ln58_1839_fu_10591_p2 = ($signed(trunc_ln42_1_fu_9703_p4) + $signed(sext_ln42_836_fu_9766_p1));

assign add_ln58_1840_fu_10597_p2 = (trunc_ln42_7_fu_9805_p4 + trunc_ln42_8_fu_9846_p4);

assign add_ln58_1841_fu_10603_p2 = (add_ln58_1840_fu_10597_p2 + add_ln58_1839_fu_10591_p2);

assign add_ln58_1842_fu_10609_p2 = ($signed(trunc_ln42_12_fu_9883_p4) + $signed(sext_ln42_840_fu_9934_p1));

assign add_ln58_1843_fu_10615_p2 = ($signed(sext_ln42_842_fu_9987_p1) + $signed(trunc_ln42_21_fu_10030_p4));

assign add_ln58_1844_fu_10621_p2 = (add_ln58_1843_fu_10615_p2 + add_ln58_1842_fu_10609_p2);

assign add_ln58_1845_fu_10627_p2 = (add_ln58_1844_fu_10621_p2 + add_ln58_1841_fu_10603_p2);

assign add_ln58_1846_fu_10633_p2 = ($signed(sext_ln42_844_fu_10085_p1) + $signed(trunc_ln42_27_fu_10153_p4));

assign add_ln58_1847_fu_10639_p2 = ($signed(sext_ln73_57_fu_10212_p1) + $signed(sext_ln73_58_fu_10257_p1));

assign add_ln58_1848_fu_10649_p2 = ($signed(sext_ln58_362_fu_10645_p1) + $signed(add_ln58_1846_fu_10633_p2));

assign add_ln58_1849_fu_10655_p2 = ($signed(sext_ln42_848_fu_10306_p1) + $signed(trunc_ln42_39_fu_10353_p4));

assign add_ln58_1850_fu_10661_p2 = ($signed(sext_ln73_59_fu_10469_p1) + $signed(31'd19845));

assign add_ln58_1851_fu_10671_p2 = ($signed(sext_ln58_363_fu_10667_p1) + $signed(trunc_ln42_42_fu_10406_p4));

assign add_ln58_1852_fu_10677_p2 = (add_ln58_1851_fu_10671_p2 + add_ln58_1849_fu_10655_p2);

assign add_ln58_1853_fu_10683_p2 = (add_ln58_1852_fu_10677_p2 + add_ln58_1848_fu_10649_p2);

assign add_ln58_1854_fu_10689_p2 = (add_ln58_1853_fu_10683_p2 + add_ln58_1845_fu_10627_p2);

assign add_ln58_1855_fu_10695_p2 = ($signed(sext_ln42_834_fu_9723_p1) + $signed(trunc_ln42_5_fu_9770_p4));

assign add_ln58_1856_fu_10701_p2 = ($signed(sext_ln42_838_fu_9825_p1) + $signed(trunc_ln42_10_fu_9856_p4));

assign add_ln58_1857_fu_10707_p2 = (add_ln58_1856_fu_10701_p2 + add_ln58_1855_fu_10695_p2);

assign add_ln58_1858_fu_10713_p2 = ($signed(trunc_ln42_13_fu_9893_p4) + $signed(sext_ln42_841_fu_9948_p1));

assign add_ln58_1859_fu_10719_p2 = ($signed(sext_ln42_843_fu_10001_p1) + $signed(trunc_ln42_22_fu_10040_p4));

assign add_ln58_1860_fu_10725_p2 = (add_ln58_1859_fu_10719_p2 + add_ln58_1858_fu_10713_p2);

assign add_ln58_1861_fu_10731_p2 = (add_ln58_1860_fu_10725_p2 + add_ln58_1857_fu_10707_p2);

assign add_ln58_1862_fu_10737_p2 = ($signed(sext_ln42_845_fu_10099_p1) + $signed(trunc_ln42_28_fu_10163_p4));

assign add_ln58_1863_fu_10743_p2 = (trunc_ln42_31_fu_10216_p4 + trunc_ln42_34_fu_10261_p4);

assign add_ln58_1864_fu_10749_p2 = (add_ln58_1863_fu_10743_p2 + add_ln58_1862_fu_10737_p2);

assign add_ln58_1865_fu_10755_p2 = ($signed(sext_ln42_849_fu_10320_p1) + $signed(sext_ln42_851_fu_10373_p1));

assign add_ln58_1866_fu_10761_p2 = ($signed(sext_ln58_fu_10483_p1) + $signed(30'd1073727563));

assign add_ln58_1867_fu_10771_p2 = ($signed(sext_ln58_364_fu_10767_p1) + $signed(sext_ln42_853_fu_10426_p1));

assign add_ln58_1868_fu_10777_p2 = (add_ln58_1867_fu_10771_p2 + add_ln58_1865_fu_10755_p2);

assign add_ln58_1869_fu_10783_p2 = (add_ln58_1868_fu_10777_p2 + add_ln58_1864_fu_10749_p2);

assign add_ln58_1870_fu_10789_p2 = (add_ln58_1869_fu_10783_p2 + add_ln58_1861_fu_10731_p2);

assign add_ln58_fu_10487_p2 = ($signed(sext_ln42_fu_9699_p1) + $signed(sext_ln42_835_fu_9752_p1));

assign ap_ready = 1'b1;

assign sext_ln42_834_fu_9723_p1 = $signed(trunc_ln42_s_fu_9713_p4);

assign sext_ln42_835_fu_9752_p1 = $signed(trunc_ln42_2_fu_9742_p4);

assign sext_ln42_836_fu_9766_p1 = $signed(trunc_ln42_3_fu_9756_p4);

assign sext_ln42_837_fu_9801_p1 = $signed(trunc_ln42_4_fu_9791_p4);

assign sext_ln42_838_fu_9825_p1 = $signed(trunc_ln42_6_fu_9815_p4);

assign sext_ln42_839_fu_9866_p1 = $signed(data_4_val);

assign sext_ln42_840_fu_9934_p1 = $signed(trunc_ln42_15_fu_9924_p4);

assign sext_ln42_841_fu_9948_p1 = $signed(trunc_ln42_16_fu_9938_p4);

assign sext_ln42_842_fu_9987_p1 = $signed(trunc_ln42_18_fu_9977_p4);

assign sext_ln42_843_fu_10001_p1 = $signed(trunc_ln42_19_fu_9991_p4);

assign sext_ln42_844_fu_10085_p1 = $signed(trunc_ln42_24_fu_10075_p4);

assign sext_ln42_845_fu_10099_p1 = $signed(trunc_ln42_25_fu_10089_p4);

assign sext_ln42_846_fu_10198_p1 = $signed(trunc_ln42_29_fu_10188_p4);

assign sext_ln42_847_fu_10292_p1 = $signed(trunc_ln42_35_fu_10282_p4);

assign sext_ln42_848_fu_10306_p1 = $signed(trunc_ln42_36_fu_10296_p4);

assign sext_ln42_849_fu_10320_p1 = $signed(trunc_ln42_37_fu_10310_p4);

assign sext_ln42_850_fu_10349_p1 = $signed(trunc_ln42_38_fu_10339_p4);

assign sext_ln42_851_fu_10373_p1 = $signed(trunc_ln42_40_fu_10363_p4);

assign sext_ln42_852_fu_10402_p1 = $signed(trunc_ln42_41_fu_10392_p4);

assign sext_ln42_853_fu_10426_p1 = $signed(trunc_ln42_43_fu_10416_p4);

assign sext_ln42_854_fu_10455_p1 = $signed(trunc_ln42_44_fu_10445_p4);

assign sext_ln42_fu_9699_p1 = $signed(trunc_ln_fu_9689_p4);

assign sext_ln58_360_fu_10517_p1 = $signed(add_ln58_1827_fu_10511_p2);

assign sext_ln58_361_fu_10539_p1 = $signed(add_ln58_1830_fu_10533_p2);

assign sext_ln58_362_fu_10645_p1 = $signed(add_ln58_1847_fu_10639_p2);

assign sext_ln58_363_fu_10667_p1 = $signed(add_ln58_1850_fu_10661_p2);

assign sext_ln58_364_fu_10767_p1 = $signed(add_ln58_1866_fu_10761_p2);

assign sext_ln58_fu_10483_p1 = $signed(trunc_ln42_46_fu_10473_p4);

assign sext_ln70_375_fu_9683_p1 = sext_ln70_375_fu_9683_p0;

assign sext_ln70_380_fu_9785_p1 = sext_ln70_380_fu_9785_p0;

assign sext_ln70_381_fu_9829_p1 = $signed(data_3_val);

assign sext_ln70_382_fu_9903_p1 = sext_ln70_382_fu_9903_p0;

assign sext_ln70_385_fu_9957_p1 = sext_ln70_385_fu_9957_p0;

assign sext_ln70_386_fu_10005_p1 = sext_ln70_386_fu_10005_p0;

assign sext_ln70_388_fu_10050_p1 = sext_ln70_388_fu_10050_p0;

assign sext_ln70_390_fu_10103_p1 = sext_ln70_390_fu_10103_p0;

assign sext_ln70_395_fu_10231_p1 = sext_ln70_395_fu_10231_p0;

assign sext_ln70_397_fu_10276_p1 = sext_ln70_397_fu_10276_p0;

assign sext_ln73_52_fu_9973_p1 = $signed(trunc_ln42_17_fu_9963_p4);

assign sext_ln73_53_fu_10129_p1 = $signed(shl_ln73_s_fu_10121_p3);

assign sext_ln73_54_fu_10026_p1 = $signed(trunc_ln42_20_fu_10016_p4);

assign sext_ln73_55_fu_10071_p1 = $signed(trunc_ln42_23_fu_10061_p4);

assign sext_ln73_56_fu_10149_p1 = $signed(trunc_ln42_26_fu_10139_p4);

assign sext_ln73_57_fu_10212_p1 = $signed(trunc_ln42_30_fu_10202_p4);

assign sext_ln73_58_fu_10257_p1 = $signed(trunc_ln42_33_fu_10247_p4);

assign sext_ln73_59_fu_10469_p1 = $signed(trunc_ln42_45_fu_10459_p4);

assign sext_ln73_fu_10117_p1 = $signed(shl_ln_fu_10109_p3);

assign shl_ln73_s_fu_10121_p3 = {{shl_ln73_s_fu_10121_p1}, {3'd0}};

assign shl_ln_fu_10109_p3 = {{shl_ln_fu_10109_p1}, {11'd0}};

assign sub_ln73_fu_10133_p2 = ($signed(sext_ln73_53_fu_10129_p1) - $signed(sext_ln73_fu_10117_p1));

assign trunc_ln42_10_fu_9856_p4 = {{mul_ln73_1717_fu_281_p2[47:16]}};

assign trunc_ln42_11_fu_9873_p4 = {{mul_ln73_1718_fu_322_p2[47:16]}};

assign trunc_ln42_12_fu_9883_p4 = {{mul_ln42_fu_314_p2[47:16]}};

assign trunc_ln42_13_fu_9893_p4 = {{mul_ln73_1719_fu_311_p2[47:16]}};

assign trunc_ln42_14_fu_9914_p4 = {{mul_ln73_1720_fu_291_p2[47:16]}};

assign trunc_ln42_15_fu_9924_p4 = {{mul_ln73_1721_fu_320_p2[43:16]}};

assign trunc_ln42_16_fu_9938_p4 = {{mul_ln73_1722_fu_301_p2[43:16]}};

assign trunc_ln42_17_fu_9963_p4 = {{mul_ln73_1723_fu_292_p2[45:16]}};

assign trunc_ln42_18_fu_9977_p4 = {{mul_ln73_1724_fu_289_p2[45:16]}};

assign trunc_ln42_19_fu_9991_p4 = {{mul_ln73_1725_fu_293_p2[46:16]}};

assign trunc_ln42_1_fu_9703_p4 = {{mul_ln73_1707_fu_309_p2[47:16]}};

assign trunc_ln42_20_fu_10016_p4 = {{mul_ln73_1726_fu_306_p2[43:16]}};

assign trunc_ln42_21_fu_10030_p4 = {{mul_ln73_1727_fu_279_p2[47:16]}};

assign trunc_ln42_22_fu_10040_p4 = {{mul_ln73_1728_fu_295_p2[47:16]}};

assign trunc_ln42_23_fu_10061_p4 = {{mul_ln73_1729_fu_319_p2[45:16]}};

assign trunc_ln42_24_fu_10075_p4 = {{mul_ln73_1730_fu_312_p2[46:16]}};

assign trunc_ln42_25_fu_10089_p4 = {{mul_ln73_1731_fu_284_p2[46:16]}};

assign trunc_ln42_26_fu_10139_p4 = {{sub_ln73_fu_10133_p2[43:16]}};

assign trunc_ln42_27_fu_10153_p4 = {{mul_ln73_1732_fu_286_p2[47:16]}};

assign trunc_ln42_28_fu_10163_p4 = {{mul_ln73_1733_fu_315_p2[47:16]}};

assign trunc_ln42_29_fu_10188_p4 = {{mul_ln73_1734_fu_297_p2[45:16]}};

assign trunc_ln42_2_fu_9742_p4 = {{mul_ln73_1709_fu_316_p2[43:16]}};

assign trunc_ln42_30_fu_10202_p4 = {{mul_ln73_1735_fu_299_p2[44:16]}};

assign trunc_ln42_31_fu_10216_p4 = {{mul_ln73_1736_fu_323_p2[47:16]}};

assign trunc_ln42_32_fu_10237_p4 = {{mul_ln73_1737_fu_283_p2[47:16]}};

assign trunc_ln42_33_fu_10247_p4 = {{mul_ln73_1738_fu_287_p2[45:16]}};

assign trunc_ln42_34_fu_10261_p4 = {{mul_ln73_1739_fu_276_p2[47:16]}};

assign trunc_ln42_35_fu_10282_p4 = {{mul_ln73_1740_fu_277_p2[46:16]}};

assign trunc_ln42_36_fu_10296_p4 = {{mul_ln73_1741_fu_317_p2[46:16]}};

assign trunc_ln42_37_fu_10310_p4 = {{mul_ln73_1742_fu_321_p2[43:16]}};

assign trunc_ln42_38_fu_10339_p4 = {{mul_ln73_1743_fu_294_p2[45:16]}};

assign trunc_ln42_39_fu_10353_p4 = {{mul_ln73_1744_fu_278_p2[47:16]}};

assign trunc_ln42_3_fu_9756_p4 = {{mul_ln73_1710_fu_318_p2[46:16]}};

assign trunc_ln42_40_fu_10363_p4 = {{mul_ln73_1745_fu_296_p2[46:16]}};

assign trunc_ln42_41_fu_10392_p4 = {{mul_ln73_1746_fu_303_p2[43:16]}};

assign trunc_ln42_42_fu_10406_p4 = {{mul_ln73_1747_fu_282_p2[47:16]}};

assign trunc_ln42_43_fu_10416_p4 = {{mul_ln73_1748_fu_310_p2[46:16]}};

assign trunc_ln42_44_fu_10445_p4 = {{mul_ln73_1749_fu_280_p2[46:16]}};

assign trunc_ln42_45_fu_10459_p4 = {{mul_ln73_1750_fu_305_p2[45:16]}};

assign trunc_ln42_46_fu_10473_p4 = {{mul_ln73_1751_fu_290_p2[44:16]}};

assign trunc_ln42_4_fu_9791_p4 = {{mul_ln73_1712_fu_300_p2[44:16]}};

assign trunc_ln42_5_fu_9770_p4 = {{mul_ln73_1711_fu_298_p2[47:16]}};

assign trunc_ln42_6_fu_9815_p4 = {{mul_ln73_1714_fu_304_p2[44:16]}};

assign trunc_ln42_7_fu_9805_p4 = {{mul_ln73_1713_fu_307_p2[47:16]}};

assign trunc_ln42_8_fu_9846_p4 = {{mul_ln73_1716_fu_313_p2[47:16]}};

assign trunc_ln42_9_fu_9836_p4 = {{mul_ln73_1715_fu_288_p2[47:16]}};

assign trunc_ln42_s_fu_9713_p4 = {{mul_ln73_1708_fu_285_p2[46:16]}};

assign trunc_ln_fu_9689_p4 = {{mul_ln73_fu_302_p2[46:16]}};

assign ap_return_0 = add_ln58_1838_fu_10585_p2;

assign ap_return_1 = add_ln58_1854_fu_10689_p2;

assign ap_return_2 = add_ln58_1870_fu_10789_p2;

assign mul_ln42_fu_314_p0 = sext_ln42_839_fu_9866_p1;

assign mul_ln42_fu_314_p1 = 48'd281474976673158;

assign mul_ln73_1707_fu_309_p1 = 48'd281474976691343;

assign mul_ln73_1708_fu_285_p0 = sext_ln70_375_fu_9683_p1;

assign mul_ln73_1708_fu_285_p1 = 47'd140737488345812;

assign mul_ln73_1709_fu_316_p1 = 44'd17592186043006;

assign mul_ln73_1710_fu_318_p1 = 47'd9193;

assign mul_ln73_1711_fu_298_p1 = 48'd281474976683817;

assign mul_ln73_1712_fu_300_p0 = sext_ln70_380_fu_9785_p1;

assign mul_ln73_1712_fu_300_p1 = 45'd2514;

assign mul_ln73_1713_fu_307_p1 = 48'd21386;

assign mul_ln73_1714_fu_304_p0 = sext_ln70_380_fu_9785_p1;

assign mul_ln73_1714_fu_304_p1 = 45'd35184372086127;

assign mul_ln73_1715_fu_288_p0 = sext_ln70_381_fu_9829_p1;

assign mul_ln73_1715_fu_288_p1 = 48'd281474976689496;

assign mul_ln73_1716_fu_313_p0 = sext_ln70_381_fu_9829_p1;

assign mul_ln73_1716_fu_313_p1 = 48'd27693;

assign mul_ln73_1717_fu_281_p0 = sext_ln70_381_fu_9829_p1;

assign mul_ln73_1717_fu_281_p1 = 48'd23189;

assign mul_ln73_1718_fu_322_p0 = sext_ln42_839_fu_9866_p1;

assign mul_ln73_1718_fu_322_p1 = 48'd17626;

assign mul_ln73_1719_fu_311_p0 = sext_ln42_839_fu_9866_p1;

assign mul_ln73_1719_fu_311_p1 = 48'd281474976678471;

assign mul_ln73_1720_fu_291_p1 = 48'd281474976691729;

assign mul_ln73_1721_fu_320_p0 = sext_ln70_382_fu_9903_p1;

assign mul_ln73_1721_fu_320_p1 = 44'd17592186042626;

assign mul_ln73_1722_fu_301_p0 = sext_ln70_382_fu_9903_p1;

assign mul_ln73_1722_fu_301_p1 = 44'd17592186042602;

assign mul_ln73_1723_fu_292_p0 = sext_ln70_385_fu_9957_p1;

assign mul_ln73_1723_fu_292_p1 = 46'd4906;

assign mul_ln73_1724_fu_289_p0 = sext_ln70_385_fu_9957_p1;

assign mul_ln73_1724_fu_289_p1 = 46'd70368744173030;

assign mul_ln73_1725_fu_293_p1 = 47'd140737488338969;

assign mul_ln73_1726_fu_306_p1 = 44'd1937;

assign mul_ln73_1727_fu_279_p0 = sext_ln70_386_fu_10005_p1;

assign mul_ln73_1727_fu_279_p1 = 48'd281474976687222;

assign mul_ln73_1728_fu_295_p0 = sext_ln70_386_fu_10005_p1;

assign mul_ln73_1728_fu_295_p1 = 48'd24237;

assign mul_ln73_1729_fu_319_p1 = 46'd7894;

assign mul_ln73_1730_fu_312_p0 = sext_ln70_388_fu_10050_p1;

assign mul_ln73_1730_fu_312_p1 = 47'd140737488344498;

assign mul_ln73_1731_fu_284_p0 = sext_ln70_388_fu_10050_p1;

assign mul_ln73_1731_fu_284_p1 = 47'd140737488345737;

assign mul_ln73_1732_fu_286_p0 = sext_ln70_390_fu_10103_p1;

assign mul_ln73_1732_fu_286_p1 = 48'd26688;

assign mul_ln73_1733_fu_315_p0 = sext_ln70_390_fu_10103_p1;

assign mul_ln73_1733_fu_315_p1 = 48'd281474976691305;

assign mul_ln73_1734_fu_297_p1 = 46'd4363;

assign mul_ln73_1735_fu_299_p1 = 45'd35184372085925;

assign mul_ln73_1736_fu_323_p1 = 48'd23510;

assign mul_ln73_1737_fu_283_p0 = sext_ln70_395_fu_10231_p1;

assign mul_ln73_1737_fu_283_p1 = 48'd17094;

assign mul_ln73_1738_fu_287_p1 = 46'd7606;

assign mul_ln73_1739_fu_276_p0 = sext_ln70_395_fu_10231_p1;

assign mul_ln73_1739_fu_276_p1 = 48'd22830;

assign mul_ln73_1740_fu_277_p0 = sext_ln70_397_fu_10276_p1;

assign mul_ln73_1740_fu_277_p1 = 47'd140737488343590;

assign mul_ln73_1741_fu_317_p0 = sext_ln70_397_fu_10276_p1;

assign mul_ln73_1741_fu_317_p1 = 47'd140737488346547;

assign mul_ln73_1742_fu_321_p1 = 44'd17592186043331;

assign mul_ln73_1743_fu_294_p1 = 46'd4526;

assign mul_ln73_1744_fu_278_p1 = 48'd30415;

assign mul_ln73_1745_fu_296_p1 = 47'd10074;

assign mul_ln73_1746_fu_303_p1 = 44'd1478;

assign mul_ln73_1747_fu_282_p1 = 48'd281474976688336;

assign mul_ln73_1748_fu_310_p1 = 47'd9772;

assign mul_ln73_1749_fu_280_p1 = 47'd8394;

assign mul_ln73_1750_fu_305_p1 = 46'd5888;

assign mul_ln73_1751_fu_290_p1 = 45'd3981;

assign mul_ln73_fu_302_p0 = sext_ln70_375_fu_9683_p1;

assign mul_ln73_fu_302_p1 = 47'd140737488344870;

assign sext_ln70_375_fu_9683_p0 = data_0_val;

assign sext_ln70_380_fu_9785_p0 = data_2_val;

assign sext_ln70_382_fu_9903_p0 = data_5_val;

assign sext_ln70_385_fu_9957_p0 = data_6_val;

assign sext_ln70_386_fu_10005_p0 = data_7_val;

assign sext_ln70_388_fu_10050_p0 = data_8_val;

assign sext_ln70_390_fu_10103_p0 = data_9_val;

assign sext_ln70_395_fu_10231_p0 = data_11_val;

assign sext_ln70_397_fu_10276_p0 = data_12_val;

assign shl_ln73_s_fu_10121_p1 = data_9_val;

assign shl_ln_fu_10109_p1 = data_9_val;

endmodule //myproject_dense_latency_ap_fixed_32_16_4_0_0_ap_fixed_32_16_5_3_0_config8_s
