// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_ReLU_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_read;
input  [31:0] p_read1;
input  [31:0] p_read2;
input  [31:0] p_read3;
input  [31:0] p_read4;
input  [31:0] p_read5;
input  [31:0] p_read6;
input  [31:0] p_read7;
input  [31:0] p_read8;
input  [31:0] p_read9;
input  [31:0] p_read10;
input  [31:0] p_read11;
input  [31:0] p_read12;
input  [31:0] p_read13;
input  [31:0] p_read14;
input  [31:0] p_read15;
input  [31:0] p_read16;
input  [31:0] p_read17;
input  [31:0] p_read18;
input  [31:0] p_read19;
input  [31:0] p_read20;
input  [31:0] p_read21;
input  [31:0] p_read22;
input  [31:0] p_read23;
input  [31:0] p_read24;
input  [31:0] p_read25;
input  [31:0] p_read26;
input  [31:0] p_read27;
input  [31:0] p_read28;
input  [31:0] p_read29;
input  [31:0] p_read30;
input  [31:0] p_read31;
output  [30:0] ap_return_0;
output  [30:0] ap_return_1;
output  [30:0] ap_return_2;
output  [30:0] ap_return_3;
output  [30:0] ap_return_4;
output  [30:0] ap_return_5;
output  [30:0] ap_return_6;
output  [30:0] ap_return_7;
output  [30:0] ap_return_8;
output  [30:0] ap_return_9;
output  [30:0] ap_return_10;
output  [30:0] ap_return_11;
output  [30:0] ap_return_12;
output  [30:0] ap_return_13;
output  [30:0] ap_return_14;
output  [30:0] ap_return_15;
output  [30:0] ap_return_16;
output  [30:0] ap_return_17;
output  [30:0] ap_return_18;
output  [30:0] ap_return_19;
output  [30:0] ap_return_20;
output  [30:0] ap_return_21;
output  [30:0] ap_return_22;
output  [30:0] ap_return_23;
output  [30:0] ap_return_24;
output  [30:0] ap_return_25;
output  [30:0] ap_return_26;
output  [30:0] ap_return_27;
output  [30:0] ap_return_28;
output  [30:0] ap_return_29;
output  [30:0] ap_return_30;
output  [30:0] ap_return_31;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[30:0] ap_return_0;
reg[30:0] ap_return_1;
reg[30:0] ap_return_2;
reg[30:0] ap_return_3;
reg[30:0] ap_return_4;
reg[30:0] ap_return_5;
reg[30:0] ap_return_6;
reg[30:0] ap_return_7;
reg[30:0] ap_return_8;
reg[30:0] ap_return_9;
reg[30:0] ap_return_10;
reg[30:0] ap_return_11;
reg[30:0] ap_return_12;
reg[30:0] ap_return_13;
reg[30:0] ap_return_14;
reg[30:0] ap_return_15;
reg[30:0] ap_return_16;
reg[30:0] ap_return_17;
reg[30:0] ap_return_18;
reg[30:0] ap_return_19;
reg[30:0] ap_return_20;
reg[30:0] ap_return_21;
reg[30:0] ap_return_22;
reg[30:0] ap_return_23;
reg[30:0] ap_return_24;
reg[30:0] ap_return_25;
reg[30:0] ap_return_26;
reg[30:0] ap_return_27;
reg[30:0] ap_return_28;
reg[30:0] ap_return_29;
reg[30:0] ap_return_30;
reg[30:0] ap_return_31;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1;
wire   [0:0] icmp_ln45_fu_274_p2;
wire   [30:0] trunc_ln42_fu_270_p1;
wire   [0:0] icmp_ln45_16_fu_292_p2;
wire   [30:0] trunc_ln42_16_fu_288_p1;
wire   [0:0] icmp_ln45_17_fu_310_p2;
wire   [30:0] trunc_ln42_17_fu_306_p1;
wire   [0:0] icmp_ln45_18_fu_328_p2;
wire   [30:0] trunc_ln42_18_fu_324_p1;
wire   [0:0] icmp_ln45_19_fu_346_p2;
wire   [30:0] trunc_ln42_19_fu_342_p1;
wire   [0:0] icmp_ln45_20_fu_364_p2;
wire   [30:0] trunc_ln42_20_fu_360_p1;
wire   [0:0] icmp_ln45_21_fu_382_p2;
wire   [30:0] trunc_ln42_21_fu_378_p1;
wire   [0:0] icmp_ln45_22_fu_400_p2;
wire   [30:0] trunc_ln42_22_fu_396_p1;
wire   [0:0] icmp_ln45_23_fu_418_p2;
wire   [30:0] trunc_ln42_23_fu_414_p1;
wire   [0:0] icmp_ln45_24_fu_436_p2;
wire   [30:0] trunc_ln42_24_fu_432_p1;
wire   [0:0] icmp_ln45_25_fu_454_p2;
wire   [30:0] trunc_ln42_25_fu_450_p1;
wire   [0:0] icmp_ln45_26_fu_472_p2;
wire   [30:0] trunc_ln42_26_fu_468_p1;
wire   [0:0] icmp_ln45_27_fu_490_p2;
wire   [30:0] trunc_ln42_27_fu_486_p1;
wire   [0:0] icmp_ln45_28_fu_508_p2;
wire   [30:0] trunc_ln42_28_fu_504_p1;
wire   [0:0] icmp_ln45_29_fu_526_p2;
wire   [30:0] trunc_ln42_29_fu_522_p1;
wire   [0:0] icmp_ln45_30_fu_544_p2;
wire   [30:0] trunc_ln42_30_fu_540_p1;
wire   [0:0] icmp_ln45_31_fu_562_p2;
wire   [30:0] trunc_ln42_31_fu_558_p1;
wire   [0:0] icmp_ln45_32_fu_580_p2;
wire   [30:0] trunc_ln42_32_fu_576_p1;
wire   [0:0] icmp_ln45_33_fu_598_p2;
wire   [30:0] trunc_ln42_33_fu_594_p1;
wire   [0:0] icmp_ln45_34_fu_616_p2;
wire   [30:0] trunc_ln42_34_fu_612_p1;
wire   [0:0] icmp_ln45_35_fu_634_p2;
wire   [30:0] trunc_ln42_35_fu_630_p1;
wire   [0:0] icmp_ln45_36_fu_652_p2;
wire   [30:0] trunc_ln42_36_fu_648_p1;
wire   [0:0] icmp_ln45_37_fu_670_p2;
wire   [30:0] trunc_ln42_37_fu_666_p1;
wire   [0:0] icmp_ln45_38_fu_688_p2;
wire   [30:0] trunc_ln42_38_fu_684_p1;
wire   [0:0] icmp_ln45_39_fu_706_p2;
wire   [30:0] trunc_ln42_39_fu_702_p1;
wire   [0:0] icmp_ln45_40_fu_724_p2;
wire   [30:0] trunc_ln42_40_fu_720_p1;
wire   [0:0] icmp_ln45_41_fu_742_p2;
wire   [30:0] trunc_ln42_41_fu_738_p1;
wire   [0:0] icmp_ln45_42_fu_760_p2;
wire   [30:0] trunc_ln42_42_fu_756_p1;
wire   [0:0] icmp_ln45_43_fu_778_p2;
wire   [30:0] trunc_ln42_43_fu_774_p1;
wire   [0:0] icmp_ln45_44_fu_796_p2;
wire   [30:0] trunc_ln42_44_fu_792_p1;
wire   [0:0] icmp_ln45_45_fu_814_p2;
wire   [30:0] trunc_ln42_45_fu_810_p1;
wire   [0:0] icmp_ln45_46_fu_832_p2;
wire   [30:0] trunc_ln42_46_fu_828_p1;
wire   [30:0] datareg_fu_280_p3;
wire   [30:0] datareg_16_fu_298_p3;
wire   [30:0] datareg_17_fu_316_p3;
wire   [30:0] datareg_18_fu_334_p3;
wire   [30:0] datareg_19_fu_352_p3;
wire   [30:0] datareg_20_fu_370_p3;
wire   [30:0] datareg_21_fu_388_p3;
wire   [30:0] datareg_22_fu_406_p3;
wire   [30:0] datareg_23_fu_424_p3;
wire   [30:0] datareg_24_fu_442_p3;
wire   [30:0] datareg_25_fu_460_p3;
wire   [30:0] datareg_26_fu_478_p3;
wire   [30:0] datareg_27_fu_496_p3;
wire   [30:0] datareg_28_fu_514_p3;
wire   [30:0] datareg_29_fu_532_p3;
wire   [30:0] datareg_30_fu_550_p3;
wire   [30:0] datareg_31_fu_568_p3;
wire   [30:0] datareg_32_fu_586_p3;
wire   [30:0] datareg_33_fu_604_p3;
wire   [30:0] datareg_34_fu_622_p3;
wire   [30:0] datareg_35_fu_640_p3;
wire   [30:0] datareg_36_fu_658_p3;
wire   [30:0] datareg_37_fu_676_p3;
wire   [30:0] datareg_38_fu_694_p3;
wire   [30:0] datareg_39_fu_712_p3;
wire   [30:0] datareg_40_fu_730_p3;
wire   [30:0] datareg_41_fu_748_p3;
wire   [30:0] datareg_42_fu_766_p3;
wire   [30:0] datareg_43_fu_784_p3;
wire   [30:0] datareg_44_fu_802_p3;
wire   [30:0] datareg_45_fu_820_p3;
wire   [30:0] datareg_46_fu_838_p3;
reg   [30:0] ap_return_0_preg;
reg   [30:0] ap_return_1_preg;
reg   [30:0] ap_return_2_preg;
reg   [30:0] ap_return_3_preg;
reg   [30:0] ap_return_4_preg;
reg   [30:0] ap_return_5_preg;
reg   [30:0] ap_return_6_preg;
reg   [30:0] ap_return_7_preg;
reg   [30:0] ap_return_8_preg;
reg   [30:0] ap_return_9_preg;
reg   [30:0] ap_return_10_preg;
reg   [30:0] ap_return_11_preg;
reg   [30:0] ap_return_12_preg;
reg   [30:0] ap_return_13_preg;
reg   [30:0] ap_return_14_preg;
reg   [30:0] ap_return_15_preg;
reg   [30:0] ap_return_16_preg;
reg   [30:0] ap_return_17_preg;
reg   [30:0] ap_return_18_preg;
reg   [30:0] ap_return_19_preg;
reg   [30:0] ap_return_20_preg;
reg   [30:0] ap_return_21_preg;
reg   [30:0] ap_return_22_preg;
reg   [30:0] ap_return_23_preg;
reg   [30:0] ap_return_24_preg;
reg   [30:0] ap_return_25_preg;
reg   [30:0] ap_return_26_preg;
reg   [30:0] ap_return_27_preg;
reg   [30:0] ap_return_28_preg;
reg   [30:0] ap_return_29_preg;
reg   [30:0] ap_return_30_preg;
reg   [30:0] ap_return_31_preg;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_return_0_preg = 31'd0;
#0 ap_return_1_preg = 31'd0;
#0 ap_return_2_preg = 31'd0;
#0 ap_return_3_preg = 31'd0;
#0 ap_return_4_preg = 31'd0;
#0 ap_return_5_preg = 31'd0;
#0 ap_return_6_preg = 31'd0;
#0 ap_return_7_preg = 31'd0;
#0 ap_return_8_preg = 31'd0;
#0 ap_return_9_preg = 31'd0;
#0 ap_return_10_preg = 31'd0;
#0 ap_return_11_preg = 31'd0;
#0 ap_return_12_preg = 31'd0;
#0 ap_return_13_preg = 31'd0;
#0 ap_return_14_preg = 31'd0;
#0 ap_return_15_preg = 31'd0;
#0 ap_return_16_preg = 31'd0;
#0 ap_return_17_preg = 31'd0;
#0 ap_return_18_preg = 31'd0;
#0 ap_return_19_preg = 31'd0;
#0 ap_return_20_preg = 31'd0;
#0 ap_return_21_preg = 31'd0;
#0 ap_return_22_preg = 31'd0;
#0 ap_return_23_preg = 31'd0;
#0 ap_return_24_preg = 31'd0;
#0 ap_return_25_preg = 31'd0;
#0 ap_return_26_preg = 31'd0;
#0 ap_return_27_preg = 31'd0;
#0 ap_return_28_preg = 31'd0;
#0 ap_return_29_preg = 31'd0;
#0 ap_return_30_preg = 31'd0;
#0 ap_return_31_preg = 31'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_0_preg <= datareg_fu_280_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_10_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_10_preg <= datareg_25_fu_460_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_11_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_11_preg <= datareg_26_fu_478_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_12_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_12_preg <= datareg_27_fu_496_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_13_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_13_preg <= datareg_28_fu_514_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_14_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_14_preg <= datareg_29_fu_532_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_15_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_15_preg <= datareg_30_fu_550_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_16_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_16_preg <= datareg_31_fu_568_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_17_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_17_preg <= datareg_32_fu_586_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_18_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_18_preg <= datareg_33_fu_604_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_19_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_19_preg <= datareg_34_fu_622_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_1_preg <= datareg_16_fu_298_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_20_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_20_preg <= datareg_35_fu_640_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_21_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_21_preg <= datareg_36_fu_658_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_22_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_22_preg <= datareg_37_fu_676_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_23_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_23_preg <= datareg_38_fu_694_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_24_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_24_preg <= datareg_39_fu_712_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_25_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_25_preg <= datareg_40_fu_730_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_26_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_26_preg <= datareg_41_fu_748_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_27_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_27_preg <= datareg_42_fu_766_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_28_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_28_preg <= datareg_43_fu_784_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_29_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_29_preg <= datareg_44_fu_802_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_2_preg <= datareg_17_fu_316_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_30_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_30_preg <= datareg_45_fu_820_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_31_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_31_preg <= datareg_46_fu_838_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_3_preg <= datareg_18_fu_334_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_4_preg <= datareg_19_fu_352_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_5_preg <= datareg_20_fu_370_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_6_preg <= datareg_21_fu_388_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_7_preg <= datareg_22_fu_406_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_8_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_8_preg <= datareg_23_fu_424_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_9_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_9_preg <= datareg_24_fu_442_p3;
        end
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_0 = datareg_fu_280_p3;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_1 = datareg_16_fu_298_p3;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_10 = datareg_25_fu_460_p3;
    end else begin
        ap_return_10 = ap_return_10_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_11 = datareg_26_fu_478_p3;
    end else begin
        ap_return_11 = ap_return_11_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_12 = datareg_27_fu_496_p3;
    end else begin
        ap_return_12 = ap_return_12_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_13 = datareg_28_fu_514_p3;
    end else begin
        ap_return_13 = ap_return_13_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_14 = datareg_29_fu_532_p3;
    end else begin
        ap_return_14 = ap_return_14_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_15 = datareg_30_fu_550_p3;
    end else begin
        ap_return_15 = ap_return_15_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_16 = datareg_31_fu_568_p3;
    end else begin
        ap_return_16 = ap_return_16_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_17 = datareg_32_fu_586_p3;
    end else begin
        ap_return_17 = ap_return_17_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_18 = datareg_33_fu_604_p3;
    end else begin
        ap_return_18 = ap_return_18_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_19 = datareg_34_fu_622_p3;
    end else begin
        ap_return_19 = ap_return_19_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_2 = datareg_17_fu_316_p3;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_20 = datareg_35_fu_640_p3;
    end else begin
        ap_return_20 = ap_return_20_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_21 = datareg_36_fu_658_p3;
    end else begin
        ap_return_21 = ap_return_21_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_22 = datareg_37_fu_676_p3;
    end else begin
        ap_return_22 = ap_return_22_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_23 = datareg_38_fu_694_p3;
    end else begin
        ap_return_23 = ap_return_23_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_24 = datareg_39_fu_712_p3;
    end else begin
        ap_return_24 = ap_return_24_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_25 = datareg_40_fu_730_p3;
    end else begin
        ap_return_25 = ap_return_25_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_26 = datareg_41_fu_748_p3;
    end else begin
        ap_return_26 = ap_return_26_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_27 = datareg_42_fu_766_p3;
    end else begin
        ap_return_27 = ap_return_27_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_28 = datareg_43_fu_784_p3;
    end else begin
        ap_return_28 = ap_return_28_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_29 = datareg_44_fu_802_p3;
    end else begin
        ap_return_29 = ap_return_29_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_3 = datareg_18_fu_334_p3;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_30 = datareg_45_fu_820_p3;
    end else begin
        ap_return_30 = ap_return_30_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_31 = datareg_46_fu_838_p3;
    end else begin
        ap_return_31 = ap_return_31_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_4 = datareg_19_fu_352_p3;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_5 = datareg_20_fu_370_p3;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_6 = datareg_21_fu_388_p3;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_7 = datareg_22_fu_406_p3;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_8 = datareg_23_fu_424_p3;
    end else begin
        ap_return_8 = ap_return_8_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_9 = datareg_24_fu_442_p3;
    end else begin
        ap_return_9 = ap_return_9_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign datareg_16_fu_298_p3 = ((icmp_ln45_16_fu_292_p2[0:0] == 1'b1) ? trunc_ln42_16_fu_288_p1 : 31'd0);

assign datareg_17_fu_316_p3 = ((icmp_ln45_17_fu_310_p2[0:0] == 1'b1) ? trunc_ln42_17_fu_306_p1 : 31'd0);

assign datareg_18_fu_334_p3 = ((icmp_ln45_18_fu_328_p2[0:0] == 1'b1) ? trunc_ln42_18_fu_324_p1 : 31'd0);

assign datareg_19_fu_352_p3 = ((icmp_ln45_19_fu_346_p2[0:0] == 1'b1) ? trunc_ln42_19_fu_342_p1 : 31'd0);

assign datareg_20_fu_370_p3 = ((icmp_ln45_20_fu_364_p2[0:0] == 1'b1) ? trunc_ln42_20_fu_360_p1 : 31'd0);

assign datareg_21_fu_388_p3 = ((icmp_ln45_21_fu_382_p2[0:0] == 1'b1) ? trunc_ln42_21_fu_378_p1 : 31'd0);

assign datareg_22_fu_406_p3 = ((icmp_ln45_22_fu_400_p2[0:0] == 1'b1) ? trunc_ln42_22_fu_396_p1 : 31'd0);

assign datareg_23_fu_424_p3 = ((icmp_ln45_23_fu_418_p2[0:0] == 1'b1) ? trunc_ln42_23_fu_414_p1 : 31'd0);

assign datareg_24_fu_442_p3 = ((icmp_ln45_24_fu_436_p2[0:0] == 1'b1) ? trunc_ln42_24_fu_432_p1 : 31'd0);

assign datareg_25_fu_460_p3 = ((icmp_ln45_25_fu_454_p2[0:0] == 1'b1) ? trunc_ln42_25_fu_450_p1 : 31'd0);

assign datareg_26_fu_478_p3 = ((icmp_ln45_26_fu_472_p2[0:0] == 1'b1) ? trunc_ln42_26_fu_468_p1 : 31'd0);

assign datareg_27_fu_496_p3 = ((icmp_ln45_27_fu_490_p2[0:0] == 1'b1) ? trunc_ln42_27_fu_486_p1 : 31'd0);

assign datareg_28_fu_514_p3 = ((icmp_ln45_28_fu_508_p2[0:0] == 1'b1) ? trunc_ln42_28_fu_504_p1 : 31'd0);

assign datareg_29_fu_532_p3 = ((icmp_ln45_29_fu_526_p2[0:0] == 1'b1) ? trunc_ln42_29_fu_522_p1 : 31'd0);

assign datareg_30_fu_550_p3 = ((icmp_ln45_30_fu_544_p2[0:0] == 1'b1) ? trunc_ln42_30_fu_540_p1 : 31'd0);

assign datareg_31_fu_568_p3 = ((icmp_ln45_31_fu_562_p2[0:0] == 1'b1) ? trunc_ln42_31_fu_558_p1 : 31'd0);

assign datareg_32_fu_586_p3 = ((icmp_ln45_32_fu_580_p2[0:0] == 1'b1) ? trunc_ln42_32_fu_576_p1 : 31'd0);

assign datareg_33_fu_604_p3 = ((icmp_ln45_33_fu_598_p2[0:0] == 1'b1) ? trunc_ln42_33_fu_594_p1 : 31'd0);

assign datareg_34_fu_622_p3 = ((icmp_ln45_34_fu_616_p2[0:0] == 1'b1) ? trunc_ln42_34_fu_612_p1 : 31'd0);

assign datareg_35_fu_640_p3 = ((icmp_ln45_35_fu_634_p2[0:0] == 1'b1) ? trunc_ln42_35_fu_630_p1 : 31'd0);

assign datareg_36_fu_658_p3 = ((icmp_ln45_36_fu_652_p2[0:0] == 1'b1) ? trunc_ln42_36_fu_648_p1 : 31'd0);

assign datareg_37_fu_676_p3 = ((icmp_ln45_37_fu_670_p2[0:0] == 1'b1) ? trunc_ln42_37_fu_666_p1 : 31'd0);

assign datareg_38_fu_694_p3 = ((icmp_ln45_38_fu_688_p2[0:0] == 1'b1) ? trunc_ln42_38_fu_684_p1 : 31'd0);

assign datareg_39_fu_712_p3 = ((icmp_ln45_39_fu_706_p2[0:0] == 1'b1) ? trunc_ln42_39_fu_702_p1 : 31'd0);

assign datareg_40_fu_730_p3 = ((icmp_ln45_40_fu_724_p2[0:0] == 1'b1) ? trunc_ln42_40_fu_720_p1 : 31'd0);

assign datareg_41_fu_748_p3 = ((icmp_ln45_41_fu_742_p2[0:0] == 1'b1) ? trunc_ln42_41_fu_738_p1 : 31'd0);

assign datareg_42_fu_766_p3 = ((icmp_ln45_42_fu_760_p2[0:0] == 1'b1) ? trunc_ln42_42_fu_756_p1 : 31'd0);

assign datareg_43_fu_784_p3 = ((icmp_ln45_43_fu_778_p2[0:0] == 1'b1) ? trunc_ln42_43_fu_774_p1 : 31'd0);

assign datareg_44_fu_802_p3 = ((icmp_ln45_44_fu_796_p2[0:0] == 1'b1) ? trunc_ln42_44_fu_792_p1 : 31'd0);

assign datareg_45_fu_820_p3 = ((icmp_ln45_45_fu_814_p2[0:0] == 1'b1) ? trunc_ln42_45_fu_810_p1 : 31'd0);

assign datareg_46_fu_838_p3 = ((icmp_ln45_46_fu_832_p2[0:0] == 1'b1) ? trunc_ln42_46_fu_828_p1 : 31'd0);

assign datareg_fu_280_p3 = ((icmp_ln45_fu_274_p2[0:0] == 1'b1) ? trunc_ln42_fu_270_p1 : 31'd0);

assign icmp_ln45_16_fu_292_p2 = (($signed(p_read1) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_17_fu_310_p2 = (($signed(p_read2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_18_fu_328_p2 = (($signed(p_read3) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_19_fu_346_p2 = (($signed(p_read4) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_20_fu_364_p2 = (($signed(p_read5) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_21_fu_382_p2 = (($signed(p_read6) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_22_fu_400_p2 = (($signed(p_read7) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_23_fu_418_p2 = (($signed(p_read8) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_24_fu_436_p2 = (($signed(p_read9) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_25_fu_454_p2 = (($signed(p_read10) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_26_fu_472_p2 = (($signed(p_read11) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_27_fu_490_p2 = (($signed(p_read12) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_28_fu_508_p2 = (($signed(p_read13) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_29_fu_526_p2 = (($signed(p_read14) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_30_fu_544_p2 = (($signed(p_read15) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_31_fu_562_p2 = (($signed(p_read16) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_32_fu_580_p2 = (($signed(p_read17) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_33_fu_598_p2 = (($signed(p_read18) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_34_fu_616_p2 = (($signed(p_read19) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_35_fu_634_p2 = (($signed(p_read20) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_36_fu_652_p2 = (($signed(p_read21) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_37_fu_670_p2 = (($signed(p_read22) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_38_fu_688_p2 = (($signed(p_read23) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_39_fu_706_p2 = (($signed(p_read24) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_40_fu_724_p2 = (($signed(p_read25) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_41_fu_742_p2 = (($signed(p_read26) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_42_fu_760_p2 = (($signed(p_read27) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_43_fu_778_p2 = (($signed(p_read28) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_44_fu_796_p2 = (($signed(p_read29) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_45_fu_814_p2 = (($signed(p_read30) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_46_fu_832_p2 = (($signed(p_read31) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_274_p2 = (($signed(p_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign trunc_ln42_16_fu_288_p1 = p_read1[30:0];

assign trunc_ln42_17_fu_306_p1 = p_read2[30:0];

assign trunc_ln42_18_fu_324_p1 = p_read3[30:0];

assign trunc_ln42_19_fu_342_p1 = p_read4[30:0];

assign trunc_ln42_20_fu_360_p1 = p_read5[30:0];

assign trunc_ln42_21_fu_378_p1 = p_read6[30:0];

assign trunc_ln42_22_fu_396_p1 = p_read7[30:0];

assign trunc_ln42_23_fu_414_p1 = p_read8[30:0];

assign trunc_ln42_24_fu_432_p1 = p_read9[30:0];

assign trunc_ln42_25_fu_450_p1 = p_read10[30:0];

assign trunc_ln42_26_fu_468_p1 = p_read11[30:0];

assign trunc_ln42_27_fu_486_p1 = p_read12[30:0];

assign trunc_ln42_28_fu_504_p1 = p_read13[30:0];

assign trunc_ln42_29_fu_522_p1 = p_read14[30:0];

assign trunc_ln42_30_fu_540_p1 = p_read15[30:0];

assign trunc_ln42_31_fu_558_p1 = p_read16[30:0];

assign trunc_ln42_32_fu_576_p1 = p_read17[30:0];

assign trunc_ln42_33_fu_594_p1 = p_read18[30:0];

assign trunc_ln42_34_fu_612_p1 = p_read19[30:0];

assign trunc_ln42_35_fu_630_p1 = p_read20[30:0];

assign trunc_ln42_36_fu_648_p1 = p_read21[30:0];

assign trunc_ln42_37_fu_666_p1 = p_read22[30:0];

assign trunc_ln42_38_fu_684_p1 = p_read23[30:0];

assign trunc_ln42_39_fu_702_p1 = p_read24[30:0];

assign trunc_ln42_40_fu_720_p1 = p_read25[30:0];

assign trunc_ln42_41_fu_738_p1 = p_read26[30:0];

assign trunc_ln42_42_fu_756_p1 = p_read27[30:0];

assign trunc_ln42_43_fu_774_p1 = p_read28[30:0];

assign trunc_ln42_44_fu_792_p1 = p_read29[30:0];

assign trunc_ln42_45_fu_810_p1 = p_read30[30:0];

assign trunc_ln42_46_fu_828_p1 = p_read31[30:0];

assign trunc_ln42_fu_270_p1 = p_read[30:0];

endmodule //myproject_relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_ReLU_config4_s
