// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_14_V_read,
        data_15_V_read,
        data_16_V_read,
        data_17_V_read,
        data_18_V_read,
        data_19_V_read,
        data_20_V_read,
        data_21_V_read,
        data_22_V_read,
        data_23_V_read,
        data_24_V_read,
        data_25_V_read,
        data_26_V_read,
        data_27_V_read,
        data_28_V_read,
        data_29_V_read,
        data_30_V_read,
        data_31_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] data_0_V_read;
input  [31:0] data_1_V_read;
input  [31:0] data_2_V_read;
input  [31:0] data_3_V_read;
input  [31:0] data_4_V_read;
input  [31:0] data_5_V_read;
input  [31:0] data_6_V_read;
input  [31:0] data_7_V_read;
input  [31:0] data_8_V_read;
input  [31:0] data_9_V_read;
input  [31:0] data_10_V_read;
input  [31:0] data_11_V_read;
input  [31:0] data_12_V_read;
input  [31:0] data_13_V_read;
input  [31:0] data_14_V_read;
input  [31:0] data_15_V_read;
input  [31:0] data_16_V_read;
input  [31:0] data_17_V_read;
input  [31:0] data_18_V_read;
input  [31:0] data_19_V_read;
input  [31:0] data_20_V_read;
input  [31:0] data_21_V_read;
input  [31:0] data_22_V_read;
input  [31:0] data_23_V_read;
input  [31:0] data_24_V_read;
input  [31:0] data_25_V_read;
input  [31:0] data_26_V_read;
input  [31:0] data_27_V_read;
input  [31:0] data_28_V_read;
input  [31:0] data_29_V_read;
input  [31:0] data_30_V_read;
input  [31:0] data_31_V_read;
output  [30:0] ap_return_0;
output  [30:0] ap_return_1;
output  [30:0] ap_return_2;
output  [30:0] ap_return_3;
output  [30:0] ap_return_4;
output  [30:0] ap_return_5;
output  [30:0] ap_return_6;
output  [30:0] ap_return_7;
output  [30:0] ap_return_8;
output  [30:0] ap_return_9;
output  [30:0] ap_return_10;
output  [30:0] ap_return_11;
output  [30:0] ap_return_12;
output  [30:0] ap_return_13;
output  [30:0] ap_return_14;
output  [30:0] ap_return_15;
output  [30:0] ap_return_16;
output  [30:0] ap_return_17;
output  [30:0] ap_return_18;
output  [30:0] ap_return_19;
output  [30:0] ap_return_20;
output  [30:0] ap_return_21;
output  [30:0] ap_return_22;
output  [30:0] ap_return_23;
output  [30:0] ap_return_24;
output  [30:0] ap_return_25;
output  [30:0] ap_return_26;
output  [30:0] ap_return_27;
output  [30:0] ap_return_28;
output  [30:0] ap_return_29;
output  [30:0] ap_return_30;
output  [30:0] ap_return_31;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[30:0] ap_return_0;
reg[30:0] ap_return_1;
reg[30:0] ap_return_2;
reg[30:0] ap_return_3;
reg[30:0] ap_return_4;
reg[30:0] ap_return_5;
reg[30:0] ap_return_6;
reg[30:0] ap_return_7;
reg[30:0] ap_return_8;
reg[30:0] ap_return_9;
reg[30:0] ap_return_10;
reg[30:0] ap_return_11;
reg[30:0] ap_return_12;
reg[30:0] ap_return_13;
reg[30:0] ap_return_14;
reg[30:0] ap_return_15;
reg[30:0] ap_return_16;
reg[30:0] ap_return_17;
reg[30:0] ap_return_18;
reg[30:0] ap_return_19;
reg[30:0] ap_return_20;
reg[30:0] ap_return_21;
reg[30:0] ap_return_22;
reg[30:0] ap_return_23;
reg[30:0] ap_return_24;
reg[30:0] ap_return_25;
reg[30:0] ap_return_26;
reg[30:0] ap_return_27;
reg[30:0] ap_return_28;
reg[30:0] ap_return_29;
reg[30:0] ap_return_30;
reg[30:0] ap_return_31;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1;
wire   [0:0] icmp_ln1494_fu_276_p2;
wire   [30:0] trunc_ln1494_fu_272_p1;
wire   [0:0] icmp_ln1494_1_fu_294_p2;
wire   [30:0] trunc_ln1494_16_fu_290_p1;
wire   [0:0] icmp_ln1494_2_fu_312_p2;
wire   [30:0] trunc_ln1494_17_fu_308_p1;
wire   [0:0] icmp_ln1494_3_fu_330_p2;
wire   [30:0] trunc_ln1494_18_fu_326_p1;
wire   [0:0] icmp_ln1494_4_fu_348_p2;
wire   [30:0] trunc_ln1494_19_fu_344_p1;
wire   [0:0] icmp_ln1494_5_fu_366_p2;
wire   [30:0] trunc_ln1494_20_fu_362_p1;
wire   [0:0] icmp_ln1494_6_fu_384_p2;
wire   [30:0] trunc_ln1494_21_fu_380_p1;
wire   [0:0] icmp_ln1494_7_fu_402_p2;
wire   [30:0] trunc_ln1494_22_fu_398_p1;
wire   [0:0] icmp_ln1494_8_fu_420_p2;
wire   [30:0] trunc_ln1494_23_fu_416_p1;
wire   [0:0] icmp_ln1494_9_fu_438_p2;
wire   [30:0] trunc_ln1494_24_fu_434_p1;
wire   [0:0] icmp_ln1494_10_fu_456_p2;
wire   [30:0] trunc_ln1494_25_fu_452_p1;
wire   [0:0] icmp_ln1494_11_fu_474_p2;
wire   [30:0] trunc_ln1494_26_fu_470_p1;
wire   [0:0] icmp_ln1494_12_fu_492_p2;
wire   [30:0] trunc_ln1494_27_fu_488_p1;
wire   [0:0] icmp_ln1494_13_fu_510_p2;
wire   [30:0] trunc_ln1494_28_fu_506_p1;
wire   [0:0] icmp_ln1494_14_fu_528_p2;
wire   [30:0] trunc_ln1494_29_fu_524_p1;
wire   [0:0] icmp_ln1494_15_fu_546_p2;
wire   [30:0] trunc_ln1494_30_fu_542_p1;
wire   [0:0] icmp_ln1494_16_fu_564_p2;
wire   [30:0] trunc_ln1494_31_fu_560_p1;
wire   [0:0] icmp_ln1494_17_fu_582_p2;
wire   [30:0] trunc_ln1494_32_fu_578_p1;
wire   [0:0] icmp_ln1494_18_fu_600_p2;
wire   [30:0] trunc_ln1494_33_fu_596_p1;
wire   [0:0] icmp_ln1494_19_fu_618_p2;
wire   [30:0] trunc_ln1494_34_fu_614_p1;
wire   [0:0] icmp_ln1494_20_fu_636_p2;
wire   [30:0] trunc_ln1494_35_fu_632_p1;
wire   [0:0] icmp_ln1494_21_fu_654_p2;
wire   [30:0] trunc_ln1494_36_fu_650_p1;
wire   [0:0] icmp_ln1494_22_fu_672_p2;
wire   [30:0] trunc_ln1494_37_fu_668_p1;
wire   [0:0] icmp_ln1494_23_fu_690_p2;
wire   [30:0] trunc_ln1494_38_fu_686_p1;
wire   [0:0] icmp_ln1494_24_fu_708_p2;
wire   [30:0] trunc_ln1494_39_fu_704_p1;
wire   [0:0] icmp_ln1494_25_fu_726_p2;
wire   [30:0] trunc_ln1494_40_fu_722_p1;
wire   [0:0] icmp_ln1494_26_fu_744_p2;
wire   [30:0] trunc_ln1494_41_fu_740_p1;
wire   [0:0] icmp_ln1494_27_fu_762_p2;
wire   [30:0] trunc_ln1494_42_fu_758_p1;
wire   [0:0] icmp_ln1494_28_fu_780_p2;
wire   [30:0] trunc_ln1494_43_fu_776_p1;
wire   [0:0] icmp_ln1494_29_fu_798_p2;
wire   [30:0] trunc_ln1494_44_fu_794_p1;
wire   [0:0] icmp_ln1494_30_fu_816_p2;
wire   [30:0] trunc_ln1494_45_fu_812_p1;
wire   [0:0] icmp_ln1494_31_fu_834_p2;
wire   [30:0] trunc_ln1494_46_fu_830_p1;
wire   [30:0] select_ln45_fu_282_p3;
wire   [30:0] select_ln45_16_fu_300_p3;
wire   [30:0] select_ln45_17_fu_318_p3;
wire   [30:0] select_ln45_18_fu_336_p3;
wire   [30:0] select_ln45_19_fu_354_p3;
wire   [30:0] select_ln45_20_fu_372_p3;
wire   [30:0] select_ln45_21_fu_390_p3;
wire   [30:0] select_ln45_22_fu_408_p3;
wire   [30:0] select_ln45_23_fu_426_p3;
wire   [30:0] select_ln45_24_fu_444_p3;
wire   [30:0] select_ln45_25_fu_462_p3;
wire   [30:0] select_ln45_26_fu_480_p3;
wire   [30:0] select_ln45_27_fu_498_p3;
wire   [30:0] select_ln45_28_fu_516_p3;
wire   [30:0] select_ln45_29_fu_534_p3;
wire   [30:0] select_ln45_30_fu_552_p3;
wire   [30:0] select_ln45_31_fu_570_p3;
wire   [30:0] select_ln45_32_fu_588_p3;
wire   [30:0] select_ln45_33_fu_606_p3;
wire   [30:0] select_ln45_34_fu_624_p3;
wire   [30:0] select_ln45_35_fu_642_p3;
wire   [30:0] select_ln45_36_fu_660_p3;
wire   [30:0] select_ln45_37_fu_678_p3;
wire   [30:0] select_ln45_38_fu_696_p3;
wire   [30:0] select_ln45_39_fu_714_p3;
wire   [30:0] select_ln45_40_fu_732_p3;
wire   [30:0] select_ln45_41_fu_750_p3;
wire   [30:0] select_ln45_42_fu_768_p3;
wire   [30:0] select_ln45_43_fu_786_p3;
wire   [30:0] select_ln45_44_fu_804_p3;
wire   [30:0] select_ln45_45_fu_822_p3;
wire   [30:0] select_ln45_46_fu_840_p3;
reg   [30:0] ap_return_0_preg;
reg   [30:0] ap_return_1_preg;
reg   [30:0] ap_return_2_preg;
reg   [30:0] ap_return_3_preg;
reg   [30:0] ap_return_4_preg;
reg   [30:0] ap_return_5_preg;
reg   [30:0] ap_return_6_preg;
reg   [30:0] ap_return_7_preg;
reg   [30:0] ap_return_8_preg;
reg   [30:0] ap_return_9_preg;
reg   [30:0] ap_return_10_preg;
reg   [30:0] ap_return_11_preg;
reg   [30:0] ap_return_12_preg;
reg   [30:0] ap_return_13_preg;
reg   [30:0] ap_return_14_preg;
reg   [30:0] ap_return_15_preg;
reg   [30:0] ap_return_16_preg;
reg   [30:0] ap_return_17_preg;
reg   [30:0] ap_return_18_preg;
reg   [30:0] ap_return_19_preg;
reg   [30:0] ap_return_20_preg;
reg   [30:0] ap_return_21_preg;
reg   [30:0] ap_return_22_preg;
reg   [30:0] ap_return_23_preg;
reg   [30:0] ap_return_24_preg;
reg   [30:0] ap_return_25_preg;
reg   [30:0] ap_return_26_preg;
reg   [30:0] ap_return_27_preg;
reg   [30:0] ap_return_28_preg;
reg   [30:0] ap_return_29_preg;
reg   [30:0] ap_return_30_preg;
reg   [30:0] ap_return_31_preg;
reg   [0:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_return_0_preg = 31'd0;
#0 ap_return_1_preg = 31'd0;
#0 ap_return_2_preg = 31'd0;
#0 ap_return_3_preg = 31'd0;
#0 ap_return_4_preg = 31'd0;
#0 ap_return_5_preg = 31'd0;
#0 ap_return_6_preg = 31'd0;
#0 ap_return_7_preg = 31'd0;
#0 ap_return_8_preg = 31'd0;
#0 ap_return_9_preg = 31'd0;
#0 ap_return_10_preg = 31'd0;
#0 ap_return_11_preg = 31'd0;
#0 ap_return_12_preg = 31'd0;
#0 ap_return_13_preg = 31'd0;
#0 ap_return_14_preg = 31'd0;
#0 ap_return_15_preg = 31'd0;
#0 ap_return_16_preg = 31'd0;
#0 ap_return_17_preg = 31'd0;
#0 ap_return_18_preg = 31'd0;
#0 ap_return_19_preg = 31'd0;
#0 ap_return_20_preg = 31'd0;
#0 ap_return_21_preg = 31'd0;
#0 ap_return_22_preg = 31'd0;
#0 ap_return_23_preg = 31'd0;
#0 ap_return_24_preg = 31'd0;
#0 ap_return_25_preg = 31'd0;
#0 ap_return_26_preg = 31'd0;
#0 ap_return_27_preg = 31'd0;
#0 ap_return_28_preg = 31'd0;
#0 ap_return_29_preg = 31'd0;
#0 ap_return_30_preg = 31'd0;
#0 ap_return_31_preg = 31'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_0_preg <= select_ln45_fu_282_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_10_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_10_preg <= select_ln45_25_fu_462_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_11_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_11_preg <= select_ln45_26_fu_480_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_12_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_12_preg <= select_ln45_27_fu_498_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_13_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_13_preg <= select_ln45_28_fu_516_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_14_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_14_preg <= select_ln45_29_fu_534_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_15_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_15_preg <= select_ln45_30_fu_552_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_16_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_16_preg <= select_ln45_31_fu_570_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_17_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_17_preg <= select_ln45_32_fu_588_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_18_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_18_preg <= select_ln45_33_fu_606_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_19_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_19_preg <= select_ln45_34_fu_624_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_1_preg <= select_ln45_16_fu_300_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_20_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_20_preg <= select_ln45_35_fu_642_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_21_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_21_preg <= select_ln45_36_fu_660_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_22_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_22_preg <= select_ln45_37_fu_678_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_23_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_23_preg <= select_ln45_38_fu_696_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_24_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_24_preg <= select_ln45_39_fu_714_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_25_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_25_preg <= select_ln45_40_fu_732_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_26_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_26_preg <= select_ln45_41_fu_750_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_27_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_27_preg <= select_ln45_42_fu_768_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_28_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_28_preg <= select_ln45_43_fu_786_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_29_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_29_preg <= select_ln45_44_fu_804_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_2_preg <= select_ln45_17_fu_318_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_30_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_30_preg <= select_ln45_45_fu_822_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_31_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_31_preg <= select_ln45_46_fu_840_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_3_preg <= select_ln45_18_fu_336_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_4_preg <= select_ln45_19_fu_354_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_5_preg <= select_ln45_20_fu_372_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_6_preg <= select_ln45_21_fu_390_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_7_preg <= select_ln45_22_fu_408_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_8_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_8_preg <= select_ln45_23_fu_426_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_9_preg <= 31'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_9_preg <= select_ln45_24_fu_444_p3;
        end
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_0 = select_ln45_fu_282_p3;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_1 = select_ln45_16_fu_300_p3;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_10 = select_ln45_25_fu_462_p3;
    end else begin
        ap_return_10 = ap_return_10_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_11 = select_ln45_26_fu_480_p3;
    end else begin
        ap_return_11 = ap_return_11_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_12 = select_ln45_27_fu_498_p3;
    end else begin
        ap_return_12 = ap_return_12_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_13 = select_ln45_28_fu_516_p3;
    end else begin
        ap_return_13 = ap_return_13_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_14 = select_ln45_29_fu_534_p3;
    end else begin
        ap_return_14 = ap_return_14_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_15 = select_ln45_30_fu_552_p3;
    end else begin
        ap_return_15 = ap_return_15_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_16 = select_ln45_31_fu_570_p3;
    end else begin
        ap_return_16 = ap_return_16_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_17 = select_ln45_32_fu_588_p3;
    end else begin
        ap_return_17 = ap_return_17_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_18 = select_ln45_33_fu_606_p3;
    end else begin
        ap_return_18 = ap_return_18_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_19 = select_ln45_34_fu_624_p3;
    end else begin
        ap_return_19 = ap_return_19_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_2 = select_ln45_17_fu_318_p3;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_20 = select_ln45_35_fu_642_p3;
    end else begin
        ap_return_20 = ap_return_20_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_21 = select_ln45_36_fu_660_p3;
    end else begin
        ap_return_21 = ap_return_21_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_22 = select_ln45_37_fu_678_p3;
    end else begin
        ap_return_22 = ap_return_22_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_23 = select_ln45_38_fu_696_p3;
    end else begin
        ap_return_23 = ap_return_23_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_24 = select_ln45_39_fu_714_p3;
    end else begin
        ap_return_24 = ap_return_24_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_25 = select_ln45_40_fu_732_p3;
    end else begin
        ap_return_25 = ap_return_25_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_26 = select_ln45_41_fu_750_p3;
    end else begin
        ap_return_26 = ap_return_26_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_27 = select_ln45_42_fu_768_p3;
    end else begin
        ap_return_27 = ap_return_27_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_28 = select_ln45_43_fu_786_p3;
    end else begin
        ap_return_28 = ap_return_28_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_29 = select_ln45_44_fu_804_p3;
    end else begin
        ap_return_29 = ap_return_29_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_3 = select_ln45_18_fu_336_p3;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_30 = select_ln45_45_fu_822_p3;
    end else begin
        ap_return_30 = ap_return_30_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_31 = select_ln45_46_fu_840_p3;
    end else begin
        ap_return_31 = ap_return_31_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_4 = select_ln45_19_fu_354_p3;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_5 = select_ln45_20_fu_372_p3;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_6 = select_ln45_21_fu_390_p3;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_7 = select_ln45_22_fu_408_p3;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_8 = select_ln45_23_fu_426_p3;
    end else begin
        ap_return_8 = ap_return_8_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_9 = select_ln45_24_fu_444_p3;
    end else begin
        ap_return_9 = ap_return_9_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign icmp_ln1494_10_fu_456_p2 = (($signed(data_10_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_11_fu_474_p2 = (($signed(data_11_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_12_fu_492_p2 = (($signed(data_12_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_13_fu_510_p2 = (($signed(data_13_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_14_fu_528_p2 = (($signed(data_14_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_15_fu_546_p2 = (($signed(data_15_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_16_fu_564_p2 = (($signed(data_16_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_17_fu_582_p2 = (($signed(data_17_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_18_fu_600_p2 = (($signed(data_18_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_19_fu_618_p2 = (($signed(data_19_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_1_fu_294_p2 = (($signed(data_1_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_20_fu_636_p2 = (($signed(data_20_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_21_fu_654_p2 = (($signed(data_21_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_22_fu_672_p2 = (($signed(data_22_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_23_fu_690_p2 = (($signed(data_23_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_24_fu_708_p2 = (($signed(data_24_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_25_fu_726_p2 = (($signed(data_25_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_26_fu_744_p2 = (($signed(data_26_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_27_fu_762_p2 = (($signed(data_27_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_28_fu_780_p2 = (($signed(data_28_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_29_fu_798_p2 = (($signed(data_29_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_2_fu_312_p2 = (($signed(data_2_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_30_fu_816_p2 = (($signed(data_30_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_31_fu_834_p2 = (($signed(data_31_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_3_fu_330_p2 = (($signed(data_3_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_4_fu_348_p2 = (($signed(data_4_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_5_fu_366_p2 = (($signed(data_5_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_6_fu_384_p2 = (($signed(data_6_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_7_fu_402_p2 = (($signed(data_7_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_8_fu_420_p2 = (($signed(data_8_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_9_fu_438_p2 = (($signed(data_9_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_fu_276_p2 = (($signed(data_0_V_read) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign select_ln45_16_fu_300_p3 = ((icmp_ln1494_1_fu_294_p2[0:0] === 1'b1) ? trunc_ln1494_16_fu_290_p1 : 31'd0);

assign select_ln45_17_fu_318_p3 = ((icmp_ln1494_2_fu_312_p2[0:0] === 1'b1) ? trunc_ln1494_17_fu_308_p1 : 31'd0);

assign select_ln45_18_fu_336_p3 = ((icmp_ln1494_3_fu_330_p2[0:0] === 1'b1) ? trunc_ln1494_18_fu_326_p1 : 31'd0);

assign select_ln45_19_fu_354_p3 = ((icmp_ln1494_4_fu_348_p2[0:0] === 1'b1) ? trunc_ln1494_19_fu_344_p1 : 31'd0);

assign select_ln45_20_fu_372_p3 = ((icmp_ln1494_5_fu_366_p2[0:0] === 1'b1) ? trunc_ln1494_20_fu_362_p1 : 31'd0);

assign select_ln45_21_fu_390_p3 = ((icmp_ln1494_6_fu_384_p2[0:0] === 1'b1) ? trunc_ln1494_21_fu_380_p1 : 31'd0);

assign select_ln45_22_fu_408_p3 = ((icmp_ln1494_7_fu_402_p2[0:0] === 1'b1) ? trunc_ln1494_22_fu_398_p1 : 31'd0);

assign select_ln45_23_fu_426_p3 = ((icmp_ln1494_8_fu_420_p2[0:0] === 1'b1) ? trunc_ln1494_23_fu_416_p1 : 31'd0);

assign select_ln45_24_fu_444_p3 = ((icmp_ln1494_9_fu_438_p2[0:0] === 1'b1) ? trunc_ln1494_24_fu_434_p1 : 31'd0);

assign select_ln45_25_fu_462_p3 = ((icmp_ln1494_10_fu_456_p2[0:0] === 1'b1) ? trunc_ln1494_25_fu_452_p1 : 31'd0);

assign select_ln45_26_fu_480_p3 = ((icmp_ln1494_11_fu_474_p2[0:0] === 1'b1) ? trunc_ln1494_26_fu_470_p1 : 31'd0);

assign select_ln45_27_fu_498_p3 = ((icmp_ln1494_12_fu_492_p2[0:0] === 1'b1) ? trunc_ln1494_27_fu_488_p1 : 31'd0);

assign select_ln45_28_fu_516_p3 = ((icmp_ln1494_13_fu_510_p2[0:0] === 1'b1) ? trunc_ln1494_28_fu_506_p1 : 31'd0);

assign select_ln45_29_fu_534_p3 = ((icmp_ln1494_14_fu_528_p2[0:0] === 1'b1) ? trunc_ln1494_29_fu_524_p1 : 31'd0);

assign select_ln45_30_fu_552_p3 = ((icmp_ln1494_15_fu_546_p2[0:0] === 1'b1) ? trunc_ln1494_30_fu_542_p1 : 31'd0);

assign select_ln45_31_fu_570_p3 = ((icmp_ln1494_16_fu_564_p2[0:0] === 1'b1) ? trunc_ln1494_31_fu_560_p1 : 31'd0);

assign select_ln45_32_fu_588_p3 = ((icmp_ln1494_17_fu_582_p2[0:0] === 1'b1) ? trunc_ln1494_32_fu_578_p1 : 31'd0);

assign select_ln45_33_fu_606_p3 = ((icmp_ln1494_18_fu_600_p2[0:0] === 1'b1) ? trunc_ln1494_33_fu_596_p1 : 31'd0);

assign select_ln45_34_fu_624_p3 = ((icmp_ln1494_19_fu_618_p2[0:0] === 1'b1) ? trunc_ln1494_34_fu_614_p1 : 31'd0);

assign select_ln45_35_fu_642_p3 = ((icmp_ln1494_20_fu_636_p2[0:0] === 1'b1) ? trunc_ln1494_35_fu_632_p1 : 31'd0);

assign select_ln45_36_fu_660_p3 = ((icmp_ln1494_21_fu_654_p2[0:0] === 1'b1) ? trunc_ln1494_36_fu_650_p1 : 31'd0);

assign select_ln45_37_fu_678_p3 = ((icmp_ln1494_22_fu_672_p2[0:0] === 1'b1) ? trunc_ln1494_37_fu_668_p1 : 31'd0);

assign select_ln45_38_fu_696_p3 = ((icmp_ln1494_23_fu_690_p2[0:0] === 1'b1) ? trunc_ln1494_38_fu_686_p1 : 31'd0);

assign select_ln45_39_fu_714_p3 = ((icmp_ln1494_24_fu_708_p2[0:0] === 1'b1) ? trunc_ln1494_39_fu_704_p1 : 31'd0);

assign select_ln45_40_fu_732_p3 = ((icmp_ln1494_25_fu_726_p2[0:0] === 1'b1) ? trunc_ln1494_40_fu_722_p1 : 31'd0);

assign select_ln45_41_fu_750_p3 = ((icmp_ln1494_26_fu_744_p2[0:0] === 1'b1) ? trunc_ln1494_41_fu_740_p1 : 31'd0);

assign select_ln45_42_fu_768_p3 = ((icmp_ln1494_27_fu_762_p2[0:0] === 1'b1) ? trunc_ln1494_42_fu_758_p1 : 31'd0);

assign select_ln45_43_fu_786_p3 = ((icmp_ln1494_28_fu_780_p2[0:0] === 1'b1) ? trunc_ln1494_43_fu_776_p1 : 31'd0);

assign select_ln45_44_fu_804_p3 = ((icmp_ln1494_29_fu_798_p2[0:0] === 1'b1) ? trunc_ln1494_44_fu_794_p1 : 31'd0);

assign select_ln45_45_fu_822_p3 = ((icmp_ln1494_30_fu_816_p2[0:0] === 1'b1) ? trunc_ln1494_45_fu_812_p1 : 31'd0);

assign select_ln45_46_fu_840_p3 = ((icmp_ln1494_31_fu_834_p2[0:0] === 1'b1) ? trunc_ln1494_46_fu_830_p1 : 31'd0);

assign select_ln45_fu_282_p3 = ((icmp_ln1494_fu_276_p2[0:0] === 1'b1) ? trunc_ln1494_fu_272_p1 : 31'd0);

assign trunc_ln1494_16_fu_290_p1 = data_1_V_read[30:0];

assign trunc_ln1494_17_fu_308_p1 = data_2_V_read[30:0];

assign trunc_ln1494_18_fu_326_p1 = data_3_V_read[30:0];

assign trunc_ln1494_19_fu_344_p1 = data_4_V_read[30:0];

assign trunc_ln1494_20_fu_362_p1 = data_5_V_read[30:0];

assign trunc_ln1494_21_fu_380_p1 = data_6_V_read[30:0];

assign trunc_ln1494_22_fu_398_p1 = data_7_V_read[30:0];

assign trunc_ln1494_23_fu_416_p1 = data_8_V_read[30:0];

assign trunc_ln1494_24_fu_434_p1 = data_9_V_read[30:0];

assign trunc_ln1494_25_fu_452_p1 = data_10_V_read[30:0];

assign trunc_ln1494_26_fu_470_p1 = data_11_V_read[30:0];

assign trunc_ln1494_27_fu_488_p1 = data_12_V_read[30:0];

assign trunc_ln1494_28_fu_506_p1 = data_13_V_read[30:0];

assign trunc_ln1494_29_fu_524_p1 = data_14_V_read[30:0];

assign trunc_ln1494_30_fu_542_p1 = data_15_V_read[30:0];

assign trunc_ln1494_31_fu_560_p1 = data_16_V_read[30:0];

assign trunc_ln1494_32_fu_578_p1 = data_17_V_read[30:0];

assign trunc_ln1494_33_fu_596_p1 = data_18_V_read[30:0];

assign trunc_ln1494_34_fu_614_p1 = data_19_V_read[30:0];

assign trunc_ln1494_35_fu_632_p1 = data_20_V_read[30:0];

assign trunc_ln1494_36_fu_650_p1 = data_21_V_read[30:0];

assign trunc_ln1494_37_fu_668_p1 = data_22_V_read[30:0];

assign trunc_ln1494_38_fu_686_p1 = data_23_V_read[30:0];

assign trunc_ln1494_39_fu_704_p1 = data_24_V_read[30:0];

assign trunc_ln1494_40_fu_722_p1 = data_25_V_read[30:0];

assign trunc_ln1494_41_fu_740_p1 = data_26_V_read[30:0];

assign trunc_ln1494_42_fu_758_p1 = data_27_V_read[30:0];

assign trunc_ln1494_43_fu_776_p1 = data_28_V_read[30:0];

assign trunc_ln1494_44_fu_794_p1 = data_29_V_read[30:0];

assign trunc_ln1494_45_fu_812_p1 = data_30_V_read[30:0];

assign trunc_ln1494_46_fu_830_p1 = data_31_V_read[30:0];

assign trunc_ln1494_fu_272_p1 = data_0_V_read[30:0];

endmodule //relu_ap_fixed_32_16_5_3_0_ap_fixed_32_16_4_0_0_relu_config4_s
